import type { JmProfession } from "./journey-mapper-types";

export const JM_PROFESSIONS: JmProfession[] = [
  // --- OLAHRAGA ---
  { code: "P001", name: "Pesepakbola / Atlet profesional", ecosystem: "Olahraga", description: "Bermain untuk tim profesional, menjalani hidup sebagai atlet penuh waktu.", hardSkillsRequired: ["HS18"], hardSkillsSupporting: ["HS27", "HS14"], softSkillsRequired: ["SS13", "SS21", "SS03"], softSkillsSupporting: ["SS02", "SS07"] },
  { code: "P002", name: "Pelatih kepala (head coach)", ecosystem: "Olahraga", description: "Memimpin strategi dan pengembangan tim secara keseluruhan.", hardSkillsRequired: ["HS18"], hardSkillsSupporting: ["HS24", "HS27"], softSkillsRequired: ["SS02", "SS01", "SS08"], softSkillsSupporting: ["SS11", "SS23"] },
  { code: "P003", name: "Asisten pelatih", ecosystem: "Olahraga", description: "Mendukung pelatih kepala, fokus pada aspek teknis atau posisi tertentu.", hardSkillsRequired: [], hardSkillsSupporting: ["HS18", "HS24"], softSkillsRequired: ["SS03", "SS01"], softSkillsSupporting: ["SS15", "SS07"] },
  { code: "P004", name: "Analis data / Video analyst", ecosystem: "Olahraga", description: "Mengolah statistik dan rekaman video untuk mendukung strategi tim.", hardSkillsRequired: ["HS18", "HS14", "HS15"], hardSkillsSupporting: ["HS03", "HS17"], softSkillsRequired: ["SS15", "SS11"], softSkillsSupporting: ["SS01", "SS12"] },
  { code: "P005", name: "Scout / Pencari bakat", ecosystem: "Olahraga", description: "Mencari dan mengevaluasi pemain berbakat untuk direkrut tim.", hardSkillsRequired: ["HS18"], hardSkillsSupporting: ["HS14", "HS26"], softSkillsRequired: ["SS15", "SS11", "SS20"], softSkillsSupporting: ["SS10", "SS01"] },
  { code: "P006", name: "Fisioterapis tim olahraga", ecosystem: "Olahraga", description: "Memulihkan cedera pemain dan menjaga kondisi fisik tim.", hardSkillsRequired: ["HS33"], hardSkillsSupporting: ["HS32"], softSkillsRequired: ["SS08", "SS01"], softSkillsSupporting: ["SS21", "SS06"] },
  { code: "P007", name: "Dokter tim olahraga", ecosystem: "Olahraga", description: "Menangani kesehatan medis atlet sebelum, selama, dan setelah pertandingan.", hardSkillsRequired: ["HS33"], hardSkillsSupporting: ["HS27", "HS18"], softSkillsRequired: ["SS11", "SS08", "SS06"], softSkillsSupporting: ["SS03", "SS21"] },
  { code: "P008", name: "Manajer / General Manager klub", ecosystem: "Olahraga", description: "Mengelola operasional, keuangan, dan strategi bisnis klub olahraga.", hardSkillsRequired: ["HS19", "HS20", "HS22"], hardSkillsSupporting: ["HS45", "HS21"], softSkillsRequired: ["SS02", "SS23", "SS09"], softSkillsSupporting: ["SS10", "SS01"] },
  { code: "P009", name: "Agen pemain", ecosystem: "Olahraga", description: "Mewakili kepentingan atlet dalam negosiasi kontrak dan transfer.", hardSkillsRequired: ["HS40", "HS22"], hardSkillsSupporting: ["HS27", "HS45"], softSkillsRequired: ["SS09", "SS10", "SS24"], softSkillsSupporting: ["SS23", "SS08"] },
  { code: "P010", name: "Fotografer olahraga", ecosystem: "Olahraga", description: "Mengabadikan momen pertandingan untuk media, klub, dan brand.", hardSkillsRequired: ["HS01", "HS35"], hardSkillsSupporting: ["HS11", "HS22"], softSkillsRequired: ["SS15", "SS14"], softSkillsSupporting: ["SS10", "SS05"] },
  { code: "P011", name: "Videografer / Produser konten olahraga", ecosystem: "Olahraga", description: "Membuat video highlight, dokumenter, dan konten digital bertema olahraga.", hardSkillsRequired: ["HS02", "HS03", "HS11"], hardSkillsSupporting: ["HS01", "HS04", "HS12"], softSkillsRequired: ["SS05", "SS12", "SS21"], softSkillsSupporting: ["SS14", "SS04"] },
  { code: "P012", name: "Jurnalis / Reporter olahraga", ecosystem: "Olahraga", description: "Meliput berita dan peristiwa dunia olahraga untuk media.", hardSkillsRequired: ["HS09", "HS26"], hardSkillsSupporting: ["HS01", "HS24", "HS27"], softSkillsRequired: ["SS01", "SS11", "SS20"], softSkillsSupporting: ["SS10", "SS24"] },
  { code: "P013", name: "Komentator / Pundit olahraga", ecosystem: "Olahraga", description: "Menganalisis dan mengomentari pertandingan di TV, radio, atau digital.", hardSkillsRequired: ["HS24", "HS46"], hardSkillsSupporting: ["HS18", "HS09"], softSkillsRequired: ["SS01", "SS19", "SS12"], softSkillsSupporting: ["SS11", "SS07"] },
  { code: "P014", name: "Social media manager klub", ecosystem: "Olahraga", description: "Mengelola akun media sosial klub dan membangun komunitas digital.", hardSkillsRequired: ["HS11", "HS04", "HS08"], hardSkillsSupporting: ["HS03", "HS12", "HS48"], softSkillsRequired: ["SS05", "SS12", "SS16"], softSkillsSupporting: ["SS14", "SS04"] },
  { code: "P015", name: "Event organizer turnamen", ecosystem: "Olahraga", description: "Merancang dan menjalankan event turnamen olahraga dari kecil hingga besar.", hardSkillsRequired: ["HS23", "HS20"], hardSkillsSupporting: ["HS45", "HS22", "HS11"], softSkillsRequired: ["SS06", "SS04", "SS03"], softSkillsSupporting: ["SS02", "SS09"] },
  { code: "P016", name: "Merchandising & brand olahraga", ecosystem: "Olahraga", description: "Mengembangkan dan menjual produk bermerek tim olahraga.", hardSkillsRequired: ["HS04", "HS21", "HS45"], hardSkillsSupporting: ["HS19", "HS22"], softSkillsRequired: ["SS05", "SS16", "SS23"], softSkillsSupporting: ["SS09", "SS10"] },
  { code: "P017", name: "Manajer komersial / sponsorship", ecosystem: "Olahraga", description: "Mencari dan mengelola hubungan sponsor untuk klub atau atlet.", hardSkillsRequired: ["HS45", "HS22", "HS21"], hardSkillsSupporting: ["HS19", "HS09"], softSkillsRequired: ["SS09", "SS23", "SS10"], softSkillsSupporting: ["SS16", "SS01"] },

  // --- KESEHATAN ---
  { code: "P018", name: "Dokter umum", ecosystem: "Kesehatan", description: "Menangani kondisi medis umum dan merujuk ke spesialis bila perlu.", hardSkillsRequired: [], hardSkillsSupporting: ["HS27", "HS34"], softSkillsRequired: ["SS08", "SS11", "SS06"], softSkillsSupporting: ["SS01", "SS21"] },
  { code: "P019", name: "Dokter spesialis", ecosystem: "Kesehatan", description: "Menangani kondisi medis spesifik (jantung, anak, kulit, dll).", hardSkillsRequired: [], hardSkillsSupporting: ["HS34", "HS27"], softSkillsRequired: ["SS11", "SS15", "SS08"], softSkillsSupporting: ["SS21", "SS06"] },
  { code: "P020", name: "Perawat / Ners", ecosystem: "Kesehatan", description: "Memberikan perawatan langsung kepada pasien di rumah sakit atau klinik.", hardSkillsRequired: ["HS33"], hardSkillsSupporting: [], softSkillsRequired: ["SS08", "SS13", "SS21"], softSkillsSupporting: ["SS03", "SS06"] },
  { code: "P021", name: "Apoteker", ecosystem: "Kesehatan", description: "Meracik dan mendistribusikan obat, edukasi pasien tentang penggunaan obat.", hardSkillsRequired: [], hardSkillsSupporting: ["HS27", "HS43"], softSkillsRequired: ["SS15", "SS08", "SS01"], softSkillsSupporting: ["SS24", "SS06"] },
  { code: "P022", name: "Fisioterapis", ecosystem: "Kesehatan", description: "Membantu pasien pulih dari cedera atau gangguan gerak melalui terapi fisik.", hardSkillsRequired: ["HS33"], hardSkillsSupporting: ["HS32"], softSkillsRequired: ["SS08", "SS01", "SS21"], softSkillsSupporting: ["SS06", "SS13"] },
  { code: "P023", name: "Ahli gizi / Nutrisionist", ecosystem: "Kesehatan", description: "Merancang program makan untuk mendukung kesehatan atau performa seseorang.", hardSkillsRequired: ["HS32"], hardSkillsSupporting: ["HS09", "HS11"], softSkillsRequired: ["SS08", "SS01", "SS15"], softSkillsSupporting: ["SS21", "SS20"] },
  { code: "P024", name: "Bidan", ecosystem: "Kesehatan", description: "Mendampingi kehamilan, persalinan, dan kesehatan reproduksi perempuan.", hardSkillsRequired: ["HS33"], hardSkillsSupporting: [], softSkillsRequired: ["SS08", "SS13", "SS01"], softSkillsSupporting: ["SS21", "SS06"] },
  { code: "P025", name: "Medical writer", ecosystem: "Kesehatan", description: "Menulis artikel ilmiah, panduan klinis, dan konten edukasi kesehatan.", hardSkillsRequired: ["HS09", "HS34"], hardSkillsSupporting: ["HS11", "HS12"], softSkillsRequired: ["SS15", "SS01", "SS20"], softSkillsSupporting: ["SS11", "SS12"] },
  { code: "P026", name: "Health content creator", ecosystem: "Kesehatan", description: "Menyederhanakan informasi medis menjadi konten yang mudah dipahami publik.", hardSkillsRequired: ["HS09", "HS11", "HS03"], hardSkillsSupporting: ["HS12", "HS04", "HS01"], softSkillsRequired: ["SS12", "SS05", "SS08"], softSkillsSupporting: ["SS21", "SS20"] },
  { code: "P027", name: "Founder / CEO healthtech startup", ecosystem: "Kesehatan", description: "Membangun solusi teknologi untuk masalah kesehatan masyarakat.", hardSkillsRequired: ["HS22", "HS20", "HS21"], hardSkillsSupporting: ["HS15", "HS07", "HS19"], softSkillsRequired: ["SS02", "SS23", "SS13"], softSkillsSupporting: ["SS06", "SS09"] },
  { code: "P028", name: "Peneliti medis / Scientist", ecosystem: "Kesehatan", description: "Melakukan riset untuk menemukan obat, vaksin, atau metode pengobatan baru.", hardSkillsRequired: ["HS34", "HS14"], hardSkillsSupporting: ["HS15", "HS27"], softSkillsRequired: ["SS11", "SS15", "SS20"], softSkillsSupporting: ["SS21", "SS06"] },
  { code: "P029", name: "Konsultan kesehatan korporat", ecosystem: "Kesehatan", description: "Merancang program kesehatan untuk karyawan perusahaan.", hardSkillsRequired: ["HS32", "HS22", "HS21"], hardSkillsSupporting: ["HS20", "HS19"], softSkillsRequired: ["SS23", "SS01", "SS08"], softSkillsSupporting: ["SS09", "SS16"] },

  // --- PENDIDIKAN ---
  { code: "P030", name: "Guru SD / SMP / SMA", ecosystem: "Pendidikan", description: "Mengajar dan mendidik siswa di jenjang pendidikan dasar dan menengah.", hardSkillsRequired: ["HS24", "HS25"], hardSkillsSupporting: ["HS43", "HS09"], softSkillsRequired: ["SS08", "SS01", "SS21"], softSkillsSupporting: ["SS06", "SS05"] },
  { code: "P031", name: "Dosen / Akademisi", ecosystem: "Pendidikan", description: "Mengajar di perguruan tinggi dan melakukan penelitian akademis.", hardSkillsRequired: ["HS34", "HS24"], hardSkillsSupporting: ["HS09", "HS27"], softSkillsRequired: ["SS01", "SS11", "SS20"], softSkillsSupporting: ["SS21", "SS08"] },
  { code: "P032", name: "Tutor / Pengajar privat", ecosystem: "Pendidikan", description: "Memberikan bimbingan belajar personal kepada pelajar.", hardSkillsRequired: ["HS24", "HS09"], hardSkillsSupporting: ["HS43"], softSkillsRequired: ["SS08", "SS01", "SS21"], softSkillsSupporting: ["SS06", "SS22"] },
  { code: "P033", name: "Kurikulum developer", ecosystem: "Pendidikan", description: "Merancang struktur dan konten program pembelajaran.", hardSkillsRequired: ["HS09", "HS34"], hardSkillsSupporting: ["HS20", "HS07"], softSkillsRequired: ["SS23", "SS05", "SS15"], softSkillsSupporting: ["SS11", "SS03"] },
  { code: "P034", name: "Psikolog pendidikan", ecosystem: "Pendidikan", description: "Membantu siswa mengatasi hambatan belajar dan masalah emosi di sekolah.", hardSkillsRequired: [], hardSkillsSupporting: ["HS09", "HS25"], softSkillsRequired: ["SS08", "SS18", "SS01"], softSkillsSupporting: ["SS17", "SS06"] },
  { code: "P035", name: "Educational content creator", ecosystem: "Pendidikan", description: "Membuat konten belajar yang menarik untuk platform digital.", hardSkillsRequired: ["HS03", "HS11", "HS09"], hardSkillsSupporting: ["HS04", "HS12", "HS06"], softSkillsRequired: ["SS05", "SS12", "SS21"], softSkillsSupporting: ["SS14", "SS07"] },
  { code: "P036", name: "Founder / CEO edtech", ecosystem: "Pendidikan", description: "Membangun platform teknologi untuk meningkatkan akses dan kualitas pendidikan.", hardSkillsRequired: ["HS22", "HS20", "HS21"], hardSkillsSupporting: ["HS07", "HS16", "HS19"], softSkillsRequired: ["SS02", "SS23", "SS13"], softSkillsSupporting: ["SS08", "SS05"] },
  { code: "P037", name: "Corporate trainer / Fasilitator", ecosystem: "Pendidikan", description: "Melatih keterampilan profesional karyawan di perusahaan.", hardSkillsRequired: ["HS24", "HS25"], hardSkillsSupporting: ["HS09", "HS20"], softSkillsRequired: ["SS01", "SS08", "SS19"], softSkillsSupporting: ["SS07", "SS22"] },
  { code: "P038", name: "Konselor sekolah / BK", ecosystem: "Pendidikan", description: "Membantu siswa menghadapi masalah akademis, sosial, dan karier.", hardSkillsRequired: ["HS25"], hardSkillsSupporting: ["HS09"], softSkillsRequired: ["SS08", "SS18", "SS01"], softSkillsSupporting: ["SS17", "SS06"] },

  // --- SENI, MUSIK & FILM ---
  { code: "P039", name: "Penyanyi / Musisi", ecosystem: "Seni", description: "Tampil secara profesional dan menghasilkan karya musik.", hardSkillsRequired: ["HS37"], hardSkillsSupporting: ["HS36", "HS11"], softSkillsRequired: ["SS05", "SS13", "SS21"], softSkillsSupporting: ["SS12", "SS07"] },
  { code: "P040", name: "Produser musik", ecosystem: "Seni", description: "Merancang aransemen dan produksi rekaman artis lain atau sendiri.", hardSkillsRequired: ["HS36", "HS37"], hardSkillsSupporting: ["HS16"], softSkillsRequired: ["SS05", "SS15", "SS03"], softSkillsSupporting: ["SS08", "SS12"] },
  { code: "P041", name: "Sound engineer", ecosystem: "Seni", description: "Mengelola kualitas suara di studio rekaman atau pertunjukan live.", hardSkillsRequired: ["HS36"], hardSkillsSupporting: ["HS37", "HS43"], softSkillsRequired: ["SS15", "SS06", "SS03"], softSkillsSupporting: ["SS01", "SS07"] },
  { code: "P042", name: "Manajer artis", ecosystem: "Seni", description: "Mengelola karier, jadwal, dan kontrak artis.", hardSkillsRequired: ["HS22", "HS45", "HS20"], hardSkillsSupporting: ["HS40", "HS11"], softSkillsRequired: ["SS09", "SS10", "SS23"], softSkillsSupporting: ["SS08", "SS01"] },
  { code: "P043", name: "Music therapist", ecosystem: "Seni", description: "Menggunakan musik sebagai alat terapi untuk kesehatan mental dan fisik.", hardSkillsRequired: ["HS37", "HS34"], hardSkillsSupporting: ["HS33"], softSkillsRequired: ["SS08", "SS18", "SS01"], softSkillsSupporting: ["SS06", "SS20"] },
  { code: "P044", name: "Penulis lagu (songwriter)", ecosystem: "Seni", description: "Menciptakan lirik dan melodi untuk artis lain atau diri sendiri.", hardSkillsRequired: ["HS37", "HS09"], hardSkillsSupporting: ["HS08", "HS36"], softSkillsRequired: ["SS05", "SS12", "SS15"], softSkillsSupporting: ["SS18", "SS07"] },
  { code: "P045", name: "Guru musik / Dosen seni", ecosystem: "Seni", description: "Mengajarkan teknik dan teori musik kepada murid atau mahasiswa.", hardSkillsRequired: ["HS37", "HS24"], hardSkillsSupporting: ["HS25", "HS34"], softSkillsRequired: ["SS08", "SS01", "SS21"], softSkillsSupporting: ["SS22", "SS05"] },
  { code: "P046", name: "Aktris / Aktor", ecosystem: "Seni", description: "Membawakan peran dalam film, serial, atau pertunjukan teater.", hardSkillsRequired: ["HS38"], hardSkillsSupporting: ["HS46", "HS24", "HS11"], softSkillsRequired: ["SS05", "SS18", "SS13"], softSkillsSupporting: ["SS07", "SS03"] },
  { code: "P047", name: "Sutradara", ecosystem: "Seni", description: "Memimpin visi kreatif keseluruhan sebuah film atau pertunjukan.", hardSkillsRequired: ["HS10", "HS38"], hardSkillsSupporting: ["HS20", "HS22", "HS03"], softSkillsRequired: ["SS02", "SS23", "SS12"], softSkillsSupporting: ["SS05", "SS06"] },
  { code: "P048", name: "Penulis skenario", ecosystem: "Seni", description: "Menciptakan naskah cerita untuk film, serial, atau pertunjukan.", hardSkillsRequired: ["HS10", "HS09"], hardSkillsSupporting: ["HS08"], softSkillsRequired: ["SS05", "SS12", "SS15"], softSkillsSupporting: ["SS18", "SS20"] },
  { code: "P049", name: "Produser film / konten", ecosystem: "Seni", description: "Mengelola proses produksi dari awal hingga distribusi.", hardSkillsRequired: ["HS20", "HS22", "HS23"], hardSkillsSupporting: ["HS19", "HS45", "HS03"], softSkillsRequired: ["SS02", "SS23", "SS06"], softSkillsSupporting: ["SS09", "SS03"] },
  { code: "P050", name: "Casting director", ecosystem: "Seni", description: "Menemukan dan memilih aktor yang tepat untuk setiap peran.", hardSkillsRequired: ["HS38", "HS26"], hardSkillsSupporting: ["HS09", "HS11"], softSkillsRequired: ["SS08", "SS15", "SS10"], softSkillsSupporting: ["SS11", "SS01"] },
  { code: "P051", name: "Desainer kostum", ecosystem: "Seni", description: "Merancang dan menyiapkan pakaian untuk karakter dalam produksi.", hardSkillsRequired: ["HS04", "HS47"], hardSkillsSupporting: ["HS05", "HS35"], softSkillsRequired: ["SS05", "SS15", "SS03"], softSkillsSupporting: ["SS01", "SS22"] },
  { code: "P052", name: "Makeup artist film", ecosystem: "Seni", description: "Merias pemain sesuai karakter dan kebutuhan produksi.", hardSkillsRequired: ["HS47"], hardSkillsSupporting: ["HS35", "HS11"], softSkillsRequired: ["SS05", "SS15", "SS03"], softSkillsSupporting: ["SS07", "SS01"] },

  // --- MEDIA & KOMUNIKASI ---
  { code: "P053", name: "Jurnalis / Wartawan", ecosystem: "Media", description: "Meliput dan melaporkan berita untuk media cetak, online, atau siaran.", hardSkillsRequired: ["HS09", "HS26"], hardSkillsSupporting: ["HS01", "HS24", "HS27"], softSkillsRequired: ["SS01", "SS11", "SS20"], softSkillsSupporting: ["SS10", "SS24"] },
  { code: "P054", name: "Editor media", ecosystem: "Media", description: "Menyunting dan menyeleksi konten yang akan dipublikasikan.", hardSkillsRequired: ["HS09", "HS04"], hardSkillsSupporting: ["HS12", "HS27"], softSkillsRequired: ["SS15", "SS11", "SS01"], softSkillsSupporting: ["SS21", "SS22"] },
  { code: "P055", name: "Penulis buku", ecosystem: "Media", description: "Menulis karya fiksi atau nonfiksi untuk diterbitkan.", hardSkillsRequired: ["HS09"], hardSkillsSupporting: ["HS08", "HS27"], softSkillsRequired: ["SS05", "SS12", "SS21"], softSkillsSupporting: ["SS15", "SS20"] },
  { code: "P056", name: "Konten kreator / Influencer", ecosystem: "Media", description: "Membuat konten di platform digital dan membangun audiens.", hardSkillsRequired: ["HS11", "HS03", "HS09"], hardSkillsSupporting: ["HS01", "HS04", "HS12"], softSkillsRequired: ["SS12", "SS05", "SS21"], softSkillsSupporting: ["SS14", "SS16"] },
  { code: "P057", name: "Podcaster", ecosystem: "Media", description: "Memproduksi program audio reguler untuk platform streaming.", hardSkillsRequired: ["HS36", "HS09", "HS26"], hardSkillsSupporting: ["HS11", "HS12", "HS24"], softSkillsRequired: ["SS12", "SS01", "SS20"], softSkillsSupporting: ["SS05", "SS14"] },
  { code: "P058", name: "Copywriter", ecosystem: "Media", description: "Menulis teks iklan, kampanye, dan materi pemasaran.", hardSkillsRequired: ["HS08", "HS09"], hardSkillsSupporting: ["HS12", "HS04"], softSkillsRequired: ["SS05", "SS16", "SS01"], softSkillsSupporting: ["SS15", "SS07"] },
  { code: "P059", name: "PR specialist / Humas", ecosystem: "Media", description: "Membangun dan menjaga reputasi individu atau organisasi di publik.", hardSkillsRequired: ["HS09", "HS22", "HS11"], hardSkillsSupporting: ["HS24", "HS27"], softSkillsRequired: ["SS01", "SS10", "SS09"], softSkillsSupporting: ["SS17", "SS24"] },
  { code: "P060", name: "Presenter / Broadcaster TV", ecosystem: "Media", description: "Membawakan program di televisi atau platform streaming.", hardSkillsRequired: ["HS46", "HS24"], hardSkillsSupporting: ["HS09", "HS27"], softSkillsRequired: ["SS01", "SS19", "SS07"], softSkillsSupporting: ["SS18", "SS12"] },
  { code: "P061", name: "Social media manager", ecosystem: "Media", description: "Mengelola strategi dan konten media sosial brand atau organisasi.", hardSkillsRequired: ["HS11", "HS08", "HS04"], hardSkillsSupporting: ["HS03", "HS12", "HS48"], softSkillsRequired: ["SS05", "SS12", "SS16"], softSkillsSupporting: ["SS14", "SS04"] },
  { code: "P062", name: "Brand strategist", ecosystem: "Media", description: "Merancang identitas dan posisi kompetitif sebuah merek di pasar.", hardSkillsRequired: ["HS21", "HS08", "HS22"], hardSkillsSupporting: ["HS04", "HS11", "HS14"], softSkillsRequired: ["SS23", "SS12", "SS05"], softSkillsSupporting: ["SS11", "SS16"] },

  // --- BISNIS & KEUANGAN ---
  { code: "P063", name: "Entrepreneur / Founder startup", ecosystem: "Bisnis", description: "Membangun perusahaan dari nol dan memimpin pertumbuhannya.", hardSkillsRequired: ["HS22", "HS19", "HS21"], hardSkillsSupporting: ["HS20", "HS11", "HS14"], softSkillsRequired: ["SS13", "SS02", "SS23"], softSkillsSupporting: ["SS06", "SS09", "SS14"] },
  { code: "P064", name: "Business development manager", ecosystem: "Bisnis", description: "Mengembangkan kemitraan, pasar baru, dan aliran pendapatan baru.", hardSkillsRequired: ["HS22", "HS21", "HS09"], hardSkillsSupporting: ["HS45", "HS20"], softSkillsRequired: ["SS09", "SS10", "SS23"], softSkillsSupporting: ["SS01", "SS14"] },
  { code: "P065", name: "Marketing manager", ecosystem: "Bisnis", description: "Merancang dan menjalankan strategi pemasaran produk atau layanan.", hardSkillsRequired: ["HS11", "HS12", "HS21"], hardSkillsSupporting: ["HS08", "HS04", "HS48"], softSkillsRequired: ["SS23", "SS05", "SS16"], softSkillsSupporting: ["SS02", "SS14"] },
  { code: "P066", name: "Sales manager", ecosystem: "Bisnis", description: "Memimpin tim penjualan dan mencapai target pendapatan.", hardSkillsRequired: ["HS22", "HS09"], hardSkillsSupporting: ["HS19", "HS43"], softSkillsRequired: ["SS09", "SS01", "SS13"], softSkillsSupporting: ["SS10", "SS07"] },
  { code: "P067", name: "Business analyst", ecosystem: "Bisnis", description: "Menganalisis data bisnis untuk mendukung pengambilan keputusan.", hardSkillsRequired: ["HS14", "HS17"], hardSkillsSupporting: ["HS15", "HS21", "HS43"], softSkillsRequired: ["SS11", "SS06", "SS15"], softSkillsSupporting: ["SS01", "SS23"] },
  { code: "P068", name: "Financial analyst", ecosystem: "Bisnis", description: "Menganalisis kondisi keuangan perusahaan atau pasar investasi.", hardSkillsRequired: ["HS19", "HS14"], hardSkillsSupporting: ["HS17", "HS43"], softSkillsRequired: ["SS11", "SS15", "SS06"], softSkillsSupporting: ["SS01", "SS21"] },
  { code: "P069", name: "Akuntan / Auditor", ecosystem: "Bisnis", description: "Mengelola laporan keuangan dan memastikan kepatuhan aturan.", hardSkillsRequired: ["HS19"], hardSkillsSupporting: ["HS14", "HS43", "HS40"], softSkillsRequired: ["SS15", "SS24", "SS21"], softSkillsSupporting: ["SS06", "SS11"] },
  { code: "P070", name: "Konsultan manajemen", ecosystem: "Bisnis", description: "Membantu perusahaan meningkatkan kinerja dan efisiensi.", hardSkillsRequired: ["HS22", "HS21", "HS14"], hardSkillsSupporting: ["HS20", "HS19", "HS27"], softSkillsRequired: ["SS23", "SS11", "SS06"], softSkillsSupporting: ["SS01", "SS19"] },
  { code: "P071", name: "Venture capitalist / Investor", ecosystem: "Bisnis", description: "Menginvestasikan modal ke startup dengan potensi pertumbuhan tinggi.", hardSkillsRequired: ["HS19", "HS22", "HS21"], hardSkillsSupporting: ["HS14", "HS27", "HS40"], softSkillsRequired: ["SS23", "SS09", "SS11"], softSkillsSupporting: ["SS10", "SS06"] },
  { code: "P072", name: "Product manager", ecosystem: "Bisnis", description: "Memimpin pengembangan produk dari riset hingga peluncuran.", hardSkillsRequired: ["HS07", "HS20", "HS14"], hardSkillsSupporting: ["HS16", "HS22", "HS26"], softSkillsRequired: ["SS23", "SS01", "SS06"], softSkillsSupporting: ["SS08", "SS03"] },
  { code: "P073", name: "HR specialist / Talent acquisition", ecosystem: "Bisnis", description: "Mengelola rekrutmen, pengembangan, dan kesejahteraan karyawan.", hardSkillsRequired: ["HS26", "HS25", "HS20"], hardSkillsSupporting: ["HS09", "HS40", "HS11"], softSkillsRequired: ["SS08", "SS01", "SS10"], softSkillsSupporting: ["SS17", "SS24"] },

  // --- TEKNOLOGI ---
  { code: "P074", name: "Software developer / Engineer", ecosystem: "Teknologi", description: "Membangun aplikasi dan sistem perangkat lunak.", hardSkillsRequired: ["HS16"], hardSkillsSupporting: ["HS17", "HS15", "HS27"], softSkillsRequired: ["SS06", "SS21", "SS20"], softSkillsSupporting: ["SS03", "SS07"] },
  { code: "P075", name: "UI/UX designer", ecosystem: "Teknologi", description: "Merancang tampilan dan pengalaman pengguna produk digital.", hardSkillsRequired: ["HS07", "HS26", "HS04"], hardSkillsSupporting: ["HS16", "HS43"], softSkillsRequired: ["SS08", "SS05", "SS15"], softSkillsSupporting: ["SS11", "SS01"] },
  { code: "P076", name: "Data scientist", ecosystem: "Teknologi", description: "Mengolah data besar untuk menemukan pola dan wawasan bisnis.", hardSkillsRequired: ["HS15", "HS14", "HS17"], hardSkillsSupporting: ["HS15", "HS27"], softSkillsRequired: ["SS11", "SS06", "SS15"], softSkillsSupporting: ["SS20", "SS12"] },
  { code: "P077", name: "Data analyst", ecosystem: "Teknologi", description: "Menganalisis data untuk menjawab pertanyaan bisnis spesifik.", hardSkillsRequired: ["HS14", "HS17"], hardSkillsSupporting: ["HS15", "HS43"], softSkillsRequired: ["SS11", "SS15", "SS06"], softSkillsSupporting: ["SS01", "SS20"] },
  { code: "P078", name: "Cybersecurity specialist", ecosystem: "Teknologi", description: "Melindungi sistem dan data dari ancaman digital.", hardSkillsRequired: ["HS16", "HS17"], hardSkillsSupporting: ["HS15", "HS27"], softSkillsRequired: ["SS11", "SS15", "SS06"], softSkillsSupporting: ["SS21", "SS20"] },
  { code: "P079", name: "AI / ML engineer", ecosystem: "Teknologi", description: "Membangun model kecerdasan buatan dan machine learning.", hardSkillsRequired: ["HS15", "HS17"], hardSkillsSupporting: ["HS16", "HS27", "HS14"], softSkillsRequired: ["SS11", "SS06", "SS20"], softSkillsSupporting: ["SS15", "SS21"] },
  { code: "P080", name: "DevOps engineer", ecosystem: "Teknologi", description: "Mengelola infrastruktur dan proses deployment perangkat lunak.", hardSkillsRequired: ["HS16", "HS17"], hardSkillsSupporting: ["HS15", "HS27"], softSkillsRequired: ["SS06", "SS15", "SS21"], softSkillsSupporting: ["SS03", "SS07"] },
  { code: "P081", name: "Technical writer", ecosystem: "Teknologi", description: "Menulis dokumentasi teknis dan panduan pengguna produk digital.", hardSkillsRequired: ["HS09", "HS16"], hardSkillsSupporting: ["HS07", "HS27"], softSkillsRequired: ["SS01", "SS15", "SS20"], softSkillsSupporting: ["SS11", "SS21"] },
  { code: "P082", name: "IT consultant", ecosystem: "Teknologi", description: "Memberikan saran kepada organisasi tentang solusi teknologi yang tepat.", hardSkillsRequired: ["HS16", "HS22", "HS20"], hardSkillsSupporting: ["HS17", "HS14", "HS27"], softSkillsRequired: ["SS01", "SS06", "SS23"], softSkillsSupporting: ["SS10", "SS11"] },
  { code: "P083", name: "Game designer", ecosystem: "Teknologi", description: "Merancang mekanik, cerita, dan pengalaman bermain game.", hardSkillsRequired: ["HS07", "HS10", "HS06"], hardSkillsSupporting: ["HS16", "HS04", "HS37"], softSkillsRequired: ["SS05", "SS12", "SS15"], softSkillsSupporting: ["SS03", "SS06"] },

  // --- KULINER ---
  { code: "P084", name: "Chef / Koki profesional", ecosystem: "Kuliner", description: "Memasak dan memimpin dapur restoran atau katering profesional.", hardSkillsRequired: ["HS30", "HS31"], hardSkillsSupporting: ["HS32", "HS20"], softSkillsRequired: ["SS05", "SS21", "SS02"], softSkillsSupporting: ["SS03", "SS06"] },
  { code: "P085", name: "Pastry chef / Baker", ecosystem: "Kuliner", description: "Spesialis pembuatan kue, roti, dan hidangan penutup.", hardSkillsRequired: ["HS30", "HS31"], hardSkillsSupporting: ["HS32"], softSkillsRequired: ["SS15", "SS05", "SS21"], softSkillsSupporting: ["SS08", "SS03"] },
  { code: "P086", name: "Food stylist", ecosystem: "Kuliner", description: "Menata makanan agar terlihat sempurna untuk foto dan video.", hardSkillsRequired: ["HS31", "HS01", "HS35"], hardSkillsSupporting: ["HS11", "HS04"], softSkillsRequired: ["SS05", "SS15", "SS07"], softSkillsSupporting: ["SS03", "SS01"] },
  { code: "P087", name: "Food content creator", ecosystem: "Kuliner", description: "Membuat konten kuliner — review, resep, street food — di platform digital.", hardSkillsRequired: ["HS11", "HS03", "HS01"], hardSkillsSupporting: ["HS31", "HS09", "HS35"], softSkillsRequired: ["SS05", "SS12", "SS21"], softSkillsSupporting: ["SS14", "SS15"] },
  { code: "P088", name: "Food product developer", ecosystem: "Kuliner", description: "Menciptakan produk makanan baru untuk industri F&B.", hardSkillsRequired: ["HS30", "HS32", "HS21"], hardSkillsSupporting: ["HS34", "HS22"], softSkillsRequired: ["SS05", "SS06", "SS15"], softSkillsSupporting: ["SS11", "SS03"] },
  { code: "P089", name: "Restaurant / F&B manager", ecosystem: "Kuliner", description: "Mengelola operasional restoran atau bisnis makanan dan minuman.", hardSkillsRequired: ["HS20", "HS19", "HS89"], hardSkillsSupporting: ["HS22", "HS11", "HS21"], softSkillsRequired: ["SS02", "SS06", "SS16"], softSkillsSupporting: ["SS04", "SS09"] },
  { code: "P090", name: "Chef tim olahraga / institusi", ecosystem: "Kuliner", description: "Memasak khusus untuk kebutuhan nutrisi atlet, RS, atau institusi besar.", hardSkillsRequired: ["HS30", "HS32"], hardSkillsSupporting: ["HS20", "HS33"], softSkillsRequired: ["SS21", "SS15", "SS03"], softSkillsSupporting: ["SS06", "SS08"] },
  { code: "P091", name: "Food photographer", ecosystem: "Kuliner", description: "Mengambil foto makanan profesional untuk menu, iklan, dan konten.", hardSkillsRequired: ["HS01", "HS35", "HS44"], hardSkillsSupporting: ["HS31", "HS04", "HS11"], softSkillsRequired: ["SS15", "SS05", "SS14"], softSkillsSupporting: ["SS03", "SS01"] },
  { code: "P092", name: "Barista / Coffee specialist", ecosystem: "Kuliner", description: "Menyeduh kopi secara profesional dan mengelola pengalaman pelanggan kafe.", hardSkillsRequired: ["HS30"], hardSkillsSupporting: ["HS42", "HS11", "HS19"], softSkillsRequired: ["SS08", "SS01", "SS15"], softSkillsSupporting: ["SS14", "SS21"] },

  // --- DESAIN & KREATIF ---
  { code: "P093", name: "Desainer grafis", ecosystem: "Kreatif", description: "Menciptakan visual untuk brand, iklan, media, dan komunikasi.", hardSkillsRequired: ["HS04", "HS05"], hardSkillsSupporting: ["HS07", "HS08"], softSkillsRequired: ["SS05", "SS15", "SS22"], softSkillsSupporting: ["SS01", "SS04"] },
  { code: "P094", name: "Illustrator / Komikus", ecosystem: "Kreatif", description: "Membuat karya ilustrasi untuk buku, webtoon, atau media visual.", hardSkillsRequired: ["HS05", "HS04"], hardSkillsSupporting: ["HS11", "HS09"], softSkillsRequired: ["SS05", "SS15", "SS12"], softSkillsSupporting: ["SS21", "SS20"] },
  { code: "P095", name: "Animator", ecosystem: "Kreatif", description: "Menghidupkan karakter dan objek melalui animasi 2D atau 3D.", hardSkillsRequired: ["HS06", "HS04"], hardSkillsSupporting: ["HS05", "HS12"], softSkillsRequired: ["SS05", "SS15", "SS21"], softSkillsSupporting: ["SS03", "SS06"] },
  { code: "P096", name: "Art director", ecosystem: "Kreatif", description: "Memimpin visi visual kampanye iklan atau proyek kreatif.", hardSkillsRequired: ["HS04", "HS07", "HS22"], hardSkillsSupporting: ["HS01", "HS06", "HS21"], softSkillsRequired: ["SS02", "SS05", "SS23"], softSkillsSupporting: ["SS01", "SS22"] },
  { code: "P097", name: "Desainer interior", ecosystem: "Kreatif", description: "Merancang ruang dalam untuk menciptakan fungsi dan estetika yang baik.", hardSkillsRequired: ["HS04", "HS07"], hardSkillsSupporting: ["HS05", "HS20", "HS22"], softSkillsRequired: ["SS05", "SS15", "SS08"], softSkillsSupporting: ["SS01", "SS06"] },
  { code: "P098", name: "Desainer fashion", ecosystem: "Kreatif", description: "Merancang pakaian dan aksesori untuk produksi massal atau haute couture.", hardSkillsRequired: ["HS47", "HS04", "HS05"], hardSkillsSupporting: ["HS11", "HS35", "HS22"], softSkillsRequired: ["SS05", "SS15", "SS07"], softSkillsSupporting: ["SS10", "SS01"] },
  { code: "P099", name: "Fotografer umum / komersial", ecosystem: "Kreatif", description: "Mengambil foto untuk berbagai keperluan — portrait, produk, event, editorial.", hardSkillsRequired: ["HS01", "HS35", "HS44"], hardSkillsSupporting: ["HS04", "HS11", "HS22"], softSkillsRequired: ["SS15", "SS05", "SS14"], softSkillsSupporting: ["SS10", "SS01"] },
  { code: "P100", name: "Creative director", ecosystem: "Kreatif", description: "Memimpin arah kreatif keseluruhan brand atau kampanye.", hardSkillsRequired: ["HS04", "HS08", "HS22"], hardSkillsSupporting: ["HS07", "HS21", "HS06"], softSkillsRequired: ["SS02", "SS23", "SS05"], softSkillsSupporting: ["SS01", "SS10"] },

  // --- HUKUM & SOSIAL ---
  { code: "P101", name: "Pengacara / Advokat", ecosystem: "Hukum", description: "Mewakili klien dalam sengketa hukum dan memberikan nasihat legal.", hardSkillsRequired: ["HS40", "HS09", "HS24"], hardSkillsSupporting: ["HS27", "HS26"], softSkillsRequired: ["SS11", "SS09", "SS01"], softSkillsSupporting: ["SS24", "SS06"] },
  { code: "P102", name: "Notaris", ecosystem: "Hukum", description: "Membuat dan mensahkan dokumen hukum resmi.", hardSkillsRequired: ["HS40", "HS19"], hardSkillsSupporting: ["HS43", "HS09"], softSkillsRequired: ["SS15", "SS24", "SS01"], softSkillsSupporting: ["SS21", "SS06"] },
  { code: "P103", name: "HR & People development", ecosystem: "Sosial", description: "Mengembangkan kapasitas manusia dalam organisasi.", hardSkillsRequired: ["HS26", "HS25", "HS20"], hardSkillsSupporting: ["HS09", "HS40", "HS11"], softSkillsRequired: ["SS08", "SS01", "SS10"], softSkillsSupporting: ["SS17", "SS24"] },
  { code: "P104", name: "Community developer", ecosystem: "Sosial", description: "Membangun dan memberdayakan komunitas — lokal maupun digital.", hardSkillsRequired: ["HS41", "HS11", "HS23"], hardSkillsSupporting: ["HS09", "HS22", "HS25"], softSkillsRequired: ["SS08", "SS10", "SS01"], softSkillsSupporting: ["SS02", "SS17"] },
];

export function getJmProfession(code: string): JmProfession | undefined {
  return JM_PROFESSIONS.find((p) => p.code === code);
}

export function getJmProfessionsByEcosystem(ecosystem: string): JmProfession[] {
  return JM_PROFESSIONS.filter((p) => p.ecosystem === ecosystem);
}
