import type { DreamTemplate } from "@beautifio/types";

export const ADDITIONAL_TEMPLATES: DreamTemplate[] = [
  {
    slug: "pro-badminton",
    title: "Pemain Bulutangkis Profesional",
    emoji: "🏸",
    color: "from-red-600 to-rose-500",
    category: "sports",
    duration: "8-12 tahun",
    description: "Jalur jadi atlet bulutangkis dari klub sampai Pelatnas. Cocok buat yang mau ngebawa nama Indonesia ke kancah dunia.",
    why_matters: "Bulutangkis andalan Indonesia di kancah internasional. Jadi atlet bukan cuma soal menang — lo ngewakilin bangsa dan ngelanjutin legenda.",
    career_options: ["Atlet Bulutangkis Nasional", "Atlet Bulutangkis Internasional", "Pelatih Bulutangkis", "Manajer Klub", "Komentator", "Pengusaha Perlengkapan"],
    success_examples: [],
    big_wins: [
      { title: "Gabung Klub", description: "Latihan terstruktur klub resmi", why_it_matters: "Footwork, grip, pukulan dasar harus bener", alternative_path: "Les privat atau komunitas", order: 1 },
      { title: "Juara Kota", description: "Menang turnamen kota pertama", why_it_matters: "Kemenangan bukti mental juara", alternative_path: "Fokus peringkat PBSI", order: 2 },
      { title: "Masuk Pelatda", description: "Lolos Pelatda provinsi", why_it_matters: "Batu loncatan Pelatnas", alternative_path: "Les privat intensif", order: 3 },
      { title: "Masuk Pelatnas", description: "Lolos Pelatnas PBSI", why_it_matters: "Puncak pembinaan", alternative_path: "Liga profesional luar negeri", order: 4 },
      { title: "Medali Internasional", description: "Medali BWF atau SEA Games", why_it_matters: "Bukti bisa bersaing dunia", alternative_path: "Jadi pelatih atau buka klub", order: 5 },
    ],
    small_wins: [
      { big_win_title: "Gabung Klub", title: "Survey Klub", description: "Cek 3 klub", order: 1 },
      { big_win_title: "Gabung Klub", title: "Latihan Perdana", description: "Daftar dan latihan", order: 2 },
      { big_win_title: "Juara Kota", title: "Daftar Turnamen", description: "Cari turnamen kota", order: 3 },
      { big_win_title: "Juara Kota", title: "Menang Babak 1", description: "Menang pertandingan pertama", order: 4 },
      { big_win_title: "Masuk Pelatda", title: "Siapkan Dokumen", description: "Surat rekomendasi", order: 5 },
      { big_win_title: "Masuk Pelatda", title: "Lolos Seleksi", description: "Lolos tahapan Pelatda", order: 6 },
      { big_win_title: "Masuk Pelatnas", title: "Konsultasi Pelatih", description: "Diskusi strategi", order: 7 },
      { big_win_title: "Masuk Pelatnas", title: "Daftar Seleksi", description: "Kirim portofolio PBSI", order: 8 },
      { big_win_title: "Medali Internasional", title: "Turun Grade 3", description: "Ikut BWF Future Series", order: 9 },
      { big_win_title: "Medali Internasional", title: "Podium", description: "Dapat medali BWF pertama", order: 10 },
    ],
    daily_activities: {
      spiritual: ["Sholat 5 waktu", "Doa sebelum tanding", "Baca Al-Quran"],
      physical: ["Footwork 30 menit", "Lari interval", "Core 15 menit"],
      knowledge: ["Analisis video lawan", "Teknik bulutangkis", "Belajar bahasa asing"],
      social: ["Diskusi strategi pelatih", "Support teman klub", "Komunikasi orang tua"],
      character: ["Catat progres", "Jurnal evaluasi", "Jaga pola makan"],
      dream_skill: ["Netting & dropshot", "Smash", "Defense & counter"],
    },
    alternative_futures: [
      { title: "Pelatih Bulutangkis", description: "Banyak mantan atlet jadi pelatih sukses. PBSI butuh pelatih muda.", skills: ["Kepelatihan", "Analisis teknik", "Manajemen atlet", "Komunikasi"] },
      { title: "Komentator", description: "Analis bulutangkis di TV atau YouTube.", skills: ["Pengetahuan", "Public speaking", "Suara", "Penulisan"] },
      { title: "Pengusaha", description: "Buka brand perlengkapan bulutangkis.", skills: ["Bisnis ritel", "Marketing", "Supplier", "Stok"] },
    ],
    min_age: 8,
    max_age: 35,
  },
  {
    slug: "pro-basketball",
    title: "Pemain Basket Profesional",
    emoji: "🏀",
    color: "from-orange-600 to-yellow-600",
    category: "sports",
    duration: "6-12 tahun",
    description: "Jalur jadi pemain basket dari latihan dasar sampai main di IBL.",
    why_matters: "Basket ngajarin kerja tim dan keputusan cepat. IBL makin populer dan basket Indonesia naik daun.",
    career_options: ["Pemain IBL", "Pemain Tim Nasional", "Pelatih Basket", "Wasit Profesional", "Manajer Klub", "Scout"],
    success_examples: [],
    big_wins: [
      { title: "Latihan Basket", description: "Gabung klub basket resmi", why_it_matters: "Dribbling, passing, shooting harus bener", alternative_path: "Komunitas basket", order: 1 },
      { title: "Tembus Tim Inti", description: "Jadi bagian tim kompetisi", why_it_matters: "Main tim ngajarin rotasi", alternative_path: "Fokus 3x3 basketball", order: 2 },
      { title: "Turnamen Resmi", description: "Main turnamen provinsi Perbasi", why_it_matters: "Mental tanding ga dari latihan aja", alternative_path: "Event komunitas", order: 3 },
      { title: "Akademi Elite", description: "Program pembinaan nasional", why_it_matters: "Akselerasi karir", alternative_path: "Tryout IBL sambil kuliah", order: 4 },
      { title: "Rookie IBL", description: "Dikontrak klub IBL", why_it_matters: "Gerbang ke pro Indonesia", alternative_path: "Main luar negeri atau pelatih", order: 5 },
    ],
    small_wins: [
      { big_win_title: "Latihan Basket", title: "Cari Klub & Trial", description: "Survey 3 klub", order: 1 },
      { big_win_title: "Latihan Basket", title: "Latihan Rutin 3x", description: "Latihan klub 3x seminggu", order: 2 },
      { big_win_title: "Tembus Tim Inti", title: "Seleksi Tim", description: "Lolos seleksi", order: 3 },
      { big_win_title: "Tembus Tim Inti", title: "Scrimmage", description: "Main lawan tim lain", order: 4 },
      { big_win_title: "Turnamen Resmi", title: "Daftar Turnamen", description: "Daftar turnamen Perbasi", order: 5 },
      { big_win_title: "Turnamen Resmi", title: "Menang 1 Laga", description: "Menang pertandingan pertama", order: 6 },
      { big_win_title: "Akademi Elite", title: "Riset Akademi", description: "Cari info akademi elite", order: 7 },
      { big_win_title: "Akademi Elite", title: "Lolos Akademi", description: "Lolos seleksi", order: 8 },
      { big_win_title: "Rookie IBL", title: "Tryout IBL", description: "Open recruitment IBL", order: 9 },
      { big_win_title: "Rookie IBL", title: "Kontrak Rookie", description: "Teken kontrak IBL", order: 10 },
    ],
    daily_activities: {
      spiritual: ["Sholat 5 waktu", "Baca doa", "Refleksi"],
      physical: ["Dribbling & footwork", "Sprint interval", "Strength training"],
      knowledge: ["Strategi basket", "Analisis pertandingan", "Tonton NBA/IBL"],
      social: ["Team bonding", "Komunikasi lapangan", "Instruksi"],
      character: ["Catat progres", "Jaga disiplin", "Mental juara"],
      dream_skill: ["Shooting & layup", "Ball handling", "Defense & rebounding"],
    },
    alternative_futures: [
      { title: "Pelatih Basket", description: "Jadi pelatih tim basket sekolah atau klub.", skills: ["Kepelatihan", "Analisis", "Manajemen tim", "Teknik"] },
      { title: "Wasit Profesional", description: "Wasit IBL atau turnamen resmi.", skills: ["Peraturan", "Pengambilan keputusan", "Fisik", "Sertifikasi"] },
      { title: "Konten Basket", description: "Konten basket di YouTube atau TikTok.", skills: ["Content creation", "Video editing", "Public speaking", "Pengetahuan"] },
    ],
    min_age: 10,
    max_age: 35,
  },
  {
    slug: "swimmer",
    title: "Atlet Renang Profesional",
    emoji: "🏊",
    color: "from-sky-600 to-cyan-500",
    category: "sports",
    duration: "5-10 tahun",
    description: "Jalur jadi atlet renang dari klub sampai ke Olimpiade. Buat lo yang udah jatuh cinta sama air sejak kecil.",
    why_matters: "Renang unik — lo lawan diri sendiri, bukan orang lain. Setiap split detik berharga. Atlet renang Indonesia udah banyak ngebuktiin diri di SEA Games.",
    career_options: ["Atlet Renang Nasional", "Atlet Renang Internasional", "Pelatih Renang", "Fisioterapis", "Manajer Akuatik", "Komentator"],
    success_examples: [],
    big_wins: [
      { title: "Kuasai 4 Gaya", description: "Bebas, punggung, dada, kupu-kupu", why_it_matters: "Teknik benar cegah cedera", alternative_path: "Fokus 1-2 gaya", order: 1 },
      { title: "Gabung Klub", description: "Masuk klub PRSI", why_it_matters: "Program periodisasi profesional", alternative_path: "Les privat", order: 2 },
      { title: "Kompetisi Pertama", description: "Lomba level kota/provinsi", why_it_matters: "Mental bertanding skill sendiri", alternative_path: "Event renang komunitas", order: 3 },
      { title: "Raih Limit Nasional", description: "Waktu sesuai limit PRSI", why_it_matters: "Gerbang Kejurnas", alternative_path: "Fokus open water", order: 4 },
      { title: "Event Internasional", description: "Wakili Indonesia SEA Games", why_it_matters: "Puncak karir atlet renang", alternative_path: "Pelatih atau sekolah renang", order: 5 },
    ],
    small_wins: [
      { big_win_title: "Kuasai 4 Gaya", title: "Gaya Bebas 50m", description: "Renang 50m bebas", order: 1 },
      { big_win_title: "Kuasai 4 Gaya", title: "4 Gaya 25m", description: "Masing-masing 25m", order: 2 },
      { big_win_title: "Gabung Klub", title: "Trial Klub", description: "Kunjungi 3 klub", order: 3 },
      { big_win_title: "Gabung Klub", title: "Anggota Resmi", description: "Daftar jadi anggota", order: 4 },
      { big_win_title: "Kompetisi Pertama", title: "Daftar Lomba", description: "Daftar event pemula", order: 5 },
      { big_win_title: "Kompetisi Pertama", title: "Finish Tanpa DQ", description: "Selesai tanpa diskualifikasi", order: 6 },
      { big_win_title: "Raih Limit Nasional", title: "Catat Target", description: "Cari limit nasional", order: 7 },
      { big_win_title: "Raih Limit Nasional", title: "Break Limit", description: "Waktu di bawah limit", order: 8 },
      { big_win_title: "Event Internasional", title: "Seleksi Timnas", description: "Ikut seleksi Pelatnas", order: 9 },
      { big_win_title: "Event Internasional", title: "Tiket SEA Games", description: "Masuk tim Indonesia", order: 10 },
    ],
    daily_activities: {
      spiritual: ["Sholat 5 waktu", "Doa sebelum lomba", "Baca Al-Quran"],
      physical: ["Renang 2 jam", "Dryland", "Stretching"],
      knowledge: ["Video teknik", "Gizi olahraga", "Studi lawan"],
      social: ["Diskusi pelatih", "Support teman", "Komunikasi keluarga"],
      character: ["Catat waktu", "Jurnal harian", "Jaga jam tidur"],
      dream_skill: ["Start & turn", "Teknik pernapasan", "Sprint finish"],
    },
    alternative_futures: [
      { title: "Pelatih Renang", description: "Bina generasi baru perenang.", skills: ["Kepelatihan", "Analisis", "Manajemen atlet", "Lisensi"] },
      { title: "Fisioterapis Akuatik", description: "Spesialis fisioterapi di air.", skills: ["Fisioterapi", "Anatomi", "Terapi air", "Sertifikasi"] },
      { title: "Pengusaha", description: "Buka sekolah renang atau bisnis perlengkapan.", skills: ["Kewirausahaan", "Manajemen", "Marketing", "Pelayanan"] },
    ],
    min_age: 8,
    max_age: 35,
  },
  {
    slug: "martial-artist",
    title: "Atlet Bela Diri Profesional",
    emoji: "🥋",
    color: "from-stone-800 to-slate-700",
    category: "sports",
    duration: "5-15 tahun",
    description: "Jalur jadi atlet bela diri — dari silat, karate, taekwondo, sampai MMA. Buat lo yang pengen jago dan ngebawa nama Indonesia.",
    why_matters: "Bela diri bukan cuma bertarung — ini disiplin, hormat, dan kontrol diri. Indonesia punya tradisi silat diakui UNESCO.",
    career_options: ["Atlet Silat Nasional", "Atlet Taekwondo Nasional", "Petarung MMA", "Pelatih Bela Diri", "Wasit", "Pengusaha Dojo"],
    success_examples: [],
    big_wins: [
      { title: "Mulai Perguruan", description: "Gabung perguruan resmi", why_it_matters: "Pilih aliran yang tepat", alternative_path: "Online training", order: 1 },
      { title: "Sparing Internal", description: "Sparing & kompetisi internal", why_it_matters: "Teknik diuji biar ga ilang", alternative_path: "Fokus jurus non-tanding", order: 2 },
      { title: "Juara Wilayah", description: "Kejuaraan kota/provinsi", why_it_matters: "Kemenangan bukti metode kerja", alternative_path: "Exhibition dulu", order: 3 },
      { title: "Masuk Pelatnas", description: "Lolos seleksi Pelatnas", why_it_matters: "Puncak pembinaan", alternative_path: "Jalur pelatih atau juri", order: 4 },
      { title: "Medali Internasional", description: "SEA Games, Asian Games, atau kejuaraan dunia", why_it_matters: "Inspirasi generasi muda", alternative_path: "Buka sanggar", order: 5 },
    ],
    small_wins: [
      { big_win_title: "Mulai Perguruan", title: "Survey 3 Tempat", description: "Cek 3 dojo", order: 1 },
      { big_win_title: "Mulai Perguruan", title: "Latihan Perdana", description: "Daftar dan latihan", order: 2 },
      { big_win_title: "Sparing Internal", title: "Sparing Pertama", description: "Sparing ringan", order: 3 },
      { big_win_title: "Sparing Internal", title: "Kompetisi Internal", description: "Ikut kompetisi dojo", order: 4 },
      { big_win_title: "Juara Wilayah", title: "Daftar Turnamen", description: "Daftar kejuraan", order: 5 },
      { big_win_title: "Juara Wilayah", title: "Juara 2", description: "Medali regional", order: 6 },
      { big_win_title: "Masuk Pelatnas", title: "Persiapan Seleksi", description: "Intensif 3 bulan", order: 7 },
      { big_win_title: "Masuk Pelatnas", title: "Lolos Pelatnas", description: "SK resmi", order: 8 },
      { big_win_title: "Medali Internasional", title: "Turun Internasional", description: "Wakili Indonesia", order: 9 },
      { big_win_title: "Medali Internasional", title: "Naik Podium", description: "Dapat medali internasional", order: 10 },
    ],
    daily_activities: {
      spiritual: ["Meditasi 15 menit", "Doa sebelum latihan", "Baca kitab suci"],
      physical: ["Pemanasan & stretching", "Teknik 1 jam", "Cardio"],
      knowledge: ["Filosofi aliran", "Teknik pertarungan", "Tonton pertandingan"],
      social: ["Hormat senior", "Bantu junior", "Diskusi teknik"],
      character: ["Catat progres", "Jurnal disiplin", "Jaga pola makan"],
      dream_skill: ["Kombinasi jurus", "Bantingan", "Kuncian & submission"],
    },
    alternative_futures: [
      { title: "Pelatih", description: "Buka perguruan sendiri atau ngajar.", skills: ["Kepelatihan", "Teknik", "Manajemen kelas", "Sertifikasi"] },
      { title: "Keamanan", description: "Bodyguard atau konsultan keamanan.", skills: ["Sistem keamanan", "Pengawalan", "Risiko", "Bela diri praktis"] },
      { title: "Aktor Laga", description: "Koreografer laga atau stuntman.", skills: ["Akting", "Koreografi", "Stunt", "Fisik"] },
    ],
    min_age: 8,
    max_age: 35,
  },
  {
    slug: "fashion-designer",
    title: "Fashion Designer",
    emoji: "👗",
    color: "from-violet-600 to-purple-500",
    category: "creative",
    duration: "2-4 tahun",
    description: "Jalur dari belajar desain sampe punya brand fashion sendiri. Buat lo yang tertarik dunia mode.",
    why_matters: "Mode ekspresi diri dan identitas budaya. Indonesia kaya wastra tradisional yang jadi inspirasi ga terbatas.",
    career_options: ["Fashion Designer RTW", "Fashion Stylist", "Pattern Maker", "Creative Director", "Fashion Buyer", "Tekstil Desainer"],
    success_examples: [],
    big_wins: [
      { title: "Desain & Pola", description: "Fashion illustration, pola dasar", why_it_matters: "Skill teknis fondasi", alternative_path: "Desain digital CLO 3D", order: 1 },
      { title: "Jahit & Tekstil", description: "Karakteristik kain", why_it_matters: "Penentuan hasil akhir", alternative_path: "Kerja sama konveksi", order: 2 },
      { title: "Koleksi Mini 5", description: "5 outfit tema jelas", why_it_matters: "Identitas lo sebagai desainer", alternative_path: "1-2 outfit signature", order: 3 },
      { title: "Fashion Show", description: "Bazaar atau fashion show", why_it_matters: "Exposure segalanya", alternative_path: "Marketplace fashion", order: 4 },
      { title: "Launch Brand", description: "Brand dengan koleksi reguler", why_it_matters: "Transisi ke entrepreneur", alternative_path: "Kerja di brand existing", order: 5 },
    ],
    small_wins: [
      { big_win_title: "Desain & Pola", title: "Fashion Illustration", description: "Proporsi 9 kepala", order: 1 },
      { big_win_title: "Desain & Pola", title: "10 Croquis", description: "10 sketch", order: 2 },
      { big_win_title: "Jahit & Tekstil", title: "Jahit Sederhana", description: "Rok atau kemeja", order: 3 },
      { big_win_title: "Jahit & Tekstil", title: "5 Jenis Kain", description: "Katun, sutra, denim, satin, jersey", order: 4 },
      { big_win_title: "Koleksi Mini 5", title: "Moodboard", description: "Tema dan narasi", order: 5 },
      { big_win_title: "Koleksi Mini 5", title: "5 Outfit Jadi", description: "Produksi lengkap", order: 6 },
      { big_win_title: "Fashion Show", title: "Sewa Booth", description: "Booth bazaar", order: 7 },
      { big_win_title: "Fashion Show", title: "Fashion Show", description: "Show mini", order: 8 },
      { big_win_title: "Launch Brand", title: "Urus Legalitas", description: "Merek, SIUP", order: 9 },
      { big_win_title: "Launch Brand", title: "Launch Brand", description: "Resmi launch", order: 10 },
    ],
    daily_activities: {
      spiritual: ["Refleksi kreatif", "Doa desain", "Apresiasi alam"],
      physical: ["Posture jahit", "Stretching leher", "Jaga tangan"],
      knowledge: ["Tren fashion", "Sejarah mode", "Tekstil"],
      social: ["Networking", "Komunitas mode", "Kolaborasi"],
      character: ["Sketsa tiap hari", "Terima kritik", "Eksperimen"],
      dream_skill: ["Pattern drafting", "Draping", "CLO 3D"],
    },
    alternative_futures: [
      { title: "Fashion Stylist", description: "Stylist artis atau majalah.", skills: ["Styling", "Tren", "Networking", "Wardrobe"] },
      { title: "Tekstil Desainer", description: "Desain batik dan motif printing.", skills: ["Desain motif", "Pewarnaan", "Serat", "Printing"] },
      { title: "Fashion Buyer", description: "Pembeli untuk butik.", skills: ["Market analysis", "Negosiasi", "Forecasting", "Logistik"] },
    ],
    min_age: 14,
    max_age: 35,
  },
  {
    slug: "animator",
    title: "Animator Profesional",
    emoji: "🎬",
    color: "from-indigo-600 to-blue-600",
    category: "creative",
    duration: "1-3 tahun",
    description: "Jalur jadi animator dari dasar gambar sampe produksi animasi. Buat lo yang suka menggambar dan bercerita.",
    why_matters: "Animasi ngejelasin konsep rumit secara visual. Industri animasi Indonesia lagi naik — banyak film lokal tembus internasional.",
    career_options: ["Animator 2D/3D", "Character Designer", "Storyboard Artist", "VFX Artist", "Game Animator", "Animation Director"],
    success_examples: [],
    big_wins: [
      { title: "12 Prinsip Animasi", description: "Praktek prinsip dasar", why_it_matters: "Hukum animasi biar hidup", alternative_path: "Stop motion dulu", order: 1 },
      { title: "Animasi 5 Detik", description: "Loop 5 detik", why_it_matters: "Timing, spacing, easing", alternative_path: "Motion graphics", order: 2 },
      { title: "Character & Rigging", description: "Desain karakter+rig", why_it_matters: "Karakter kuat personality", alternative_path: "Pake template", order: 3 },
      { title: "Animasi 30 Detik", description: "Narasi jelas", why_it_matters: "Storytelling skill penting", alternative_path: "Music video", order: 4 },
      { title: "Rilis ke Publik", description: "Upload atau project bayaran", why_it_matters: "Feedback publik beda", alternative_path: "Freelance Fiverr", order: 5 },
    ],
    small_wins: [
      { big_win_title: "12 Prinsip Animasi", title: "Software Siap", description: "Blender atau Maya", order: 1 },
      { big_win_title: "12 Prinsip Animasi", title: "Bouncing Ball", description: "Squash & stretch", order: 2 },
      { big_win_title: "Animasi 5 Detik", title: "Walk Cycle", description: "Animasi jalan natural", order: 3 },
      { big_win_title: "Animasi 5 Detik", title: "5 Detik Jadi", description: "2 objek interaksi", order: 4 },
      { big_win_title: "Character & Rigging", title: "Character Sheet", description: "3 view + 5 ekspresi", order: 5 },
      { big_win_title: "Character & Rigging", title: "Rigging Selesai", description: "10 kontrol points", order: 6 },
      { big_win_title: "Animasi 30 Detik", title: "Storyboard", description: "5-8 panel", order: 7 },
      { big_win_title: "Animasi 30 Detik", title: "30 Detik Jadi", description: "Render dengan audio", order: 8 },
      { big_win_title: "Rilis ke Publik", title: "Upload Portfolio", description: "YouTube & website", order: 9 },
      { big_win_title: "Rilis ke Publik", title: "Project Bayaran", description: "Dapet project berbayar", order: 10 },
    ],
    daily_activities: {
      spiritual: ["Meditasi", "Doa", "Bersyukur"],
      physical: ["Stretching tangan", "Posture", "Olahraga"],
      knowledge: ["Software baru", "Analisis film", "12 prinsip"],
      social: ["Forum animasi", "Kolaborasi", "Feedback"],
      character: ["30 menit/hari", "Rewrite", "Terima kritik"],
      dream_skill: ["Char animation", "Lip sync", "Compositing"],
    },
    alternative_futures: [
      { title: "Game Animator", description: "Animasi karakter game.", skills: ["Game animation", "Rigging", "Unity/Unreal", "Optimization"] },
      { title: "VFX Artist", description: "Efek visual film atau iklan.", skills: ["Particle", "Compositing", "Node", "Shaders"] },
      { title: "Animation Director", description: "Pimpin tim animator.", skills: ["Kepemimpinan", "Storytelling", "Proyek", "Art direction"] },
    ],
    min_age: 14,
    max_age: 35,
  },
  {
    slug: "ux-designer",
    title: "UX Designer",
    emoji: "🎨",
    color: "from-cyan-600 to-teal-500",
    category: "business",
    duration: "6-12 bulan",
    description: "Jalur dari fundamental desain sampe portfolio siap kerja. Buat lo yang mikirin gimana bikin produk digital yang enak dipake.",
    why_matters: "UX design jembatan teknologi dan manusia. Setiap aplikasi enak dipake ada UX designer-nya. Demand terus naik.",
    career_options: ["UX Designer", "UI Designer", "Product Designer", "UX Researcher", "Interaction Designer", "Design Lead"],
    success_examples: [],
    big_wins: [
      { title: "Dasar UX", description: "Design thinking, riset, prototype", why_it_matters: "Design thinking bedain dari graphic design", alternative_path: "Google UX Certificate", order: 1 },
      { title: "3 Case Study", description: "Dokumentasi 3 project proses", why_it_matters: "Portofolio tunjukin proses", alternative_path: "Daily UI challenge", order: 2 },
      { title: "Feedback Mentor", description: "Konsultasi UX senior", why_it_matters: "Feedback dari industri", alternative_path: "Behance review", order: 3 },
      { title: "Project Kolaborasi", description: "Kerja bareng developer", why_it_matters: "UX ga sendiri", alternative_path: "Hackathon", order: 4 },
      { title: "Dapet Kerja", description: "Job pertama sebagai UX", why_it_matters: "Transisi belajar ke pro", alternative_path: "Graphic designer dulu", order: 5 },
    ],
    small_wins: [
      { big_win_title: "Dasar UX", title: "Design Thinking", description: "5 tahap empathize-test", order: 1 },
      { big_win_title: "Dasar UX", title: "Figma Kuasai", description: "Wireframe, prototype, system", order: 2 },
      { big_win_title: "3 Case Study", title: "CS E-commerce", description: "Redesign e-commerce", order: 3 },
      { big_win_title: "3 Case Study", title: "CS Edukasi", description: "Aplikasi edukasi", order: 4 },
      { big_win_title: "3 Case Study", title: "CS Fintech", description: "Aplikasi finansial", order: 5 },
      { big_win_title: "Feedback Mentor", title: "Cari 3 Mentor", description: "UX senior di LinkedIn", order: 6 },
      { big_win_title: "Feedback Mentor", title: "Revisi Portfolio", description: "Perbaiki feedback", order: 7 },
      { big_win_title: "Project Kolaborasi", title: "Kolab Developer", description: "Project bareng dev", order: 8 },
      { big_win_title: "Project Kolaborasi", title: "Presentasi", description: "Presentasi di depan", order: 9 },
      { big_win_title: "Dapet Kerja", title: "20 Lamaran", description: "Kirim ke perusahaan", order: 10 },
    ],
    daily_activities: {
      spiritual: ["Meditasi", "Doa desain", "Bersyukur"],
      physical: ["Posture", "Stretching tangan", "Olahraga"],
      knowledge: ["Artikel UX", "Design system", "Tren UI"],
      social: ["User interview", "Usability testing", "Desain review"],
      character: ["Terima feedback", "Ga ego", "Growth mindset"],
      dream_skill: ["Figma advance", "UX writing", "Design system"],
    },
    alternative_futures: [
      { title: "Product Designer", description: "Strategi produk end-to-end.", skills: ["UX", "Product strategy", "Analytics", "Stakeholder"] },
      { title: "UX Researcher", description: "User interview dan usability.", skills: ["Metode riset", "Data analysis", "User psychology", "Writing"] },
      { title: "Design Lead", description: "Pimpin tim desain.", skills: ["Kepemimpinan", "Direction", "Mentoring", "System thinking"] },
    ],
    min_age: 16,
    max_age: 35,
  },
  {
    slug: "product-manager",
    title: "Product Manager",
    emoji: "📋",
    color: "from-blue-700 to-indigo-700",
    category: "business",
    duration: "1-2 tahun",
    description: "Jalur dari fundamental sampe ngelola produk digital. Buat lo yang suka strategic thinking.",
    why_matters: "PM jembatan bisnis, teknis, desain. Lo nentuin fitur apa, kenapa, ganti ukurnya. Peran kunci produk.",
    career_options: ["Product Manager", "Product Owner", "Associate PM", "Technical PM", "Product Operations", "Growth PM"],
    success_examples: [],
    big_wins: [
      { title: "Fundamental PM", description: "Product lifecycle, prioritas", why_it_matters: "RICE, MoSCoW, OKR wajib", alternative_path: "Baca buku Inspired", order: 1 },
      { title: "Project Mini Produk", description: "PRD, prioritas, timeline", why_it_matters: "Portofolio tunjukin case study", alternative_path: "Open source product", order: 2 },
      { title: "Lead Stakeholder", description: "Cross-functional team", why_it_matters: "Lead tanpa otoritas langsung", alternative_path: "Asisten PM", order: 3 },
      { title: "Launch Fitur", description: "End-to-end launch", why_it_matters: "Koordinasi semua tim", alternative_path: "Launch plan dummy", order: 4 },
      { title: "Ukur Dampak", description: "Impact & iterasi", why_it_matters: "PM tanggung jawab outcome", alternative_path: "Product ops", order: 5 },
    ],
    small_wins: [
      { big_win_title: "Fundamental PM", title: "Framework PM", description: "RICE, MoSCoW, OKR", order: 1 },
      { big_win_title: "Fundamental PM", title: "PRD Pertama", description: "Tulis PRD 1 fitur", order: 2 },
      { big_win_title: "Project Mini Produk", title: "Case Study", description: "Analisis produk existing", order: 3 },
      { big_win_title: "Project Mini Produk", title: "Roadmap 3 Bulan", description: "Buat roadmap", order: 4 },
      { big_win_title: "Lead Stakeholder", title: "Lead Meeting", description: "Cross-functional meeting", order: 5 },
      { big_win_title: "Lead Stakeholder", title: "Buy-in", description: "Yakinkan stakeholder", order: 6 },
      { big_win_title: "Launch Fitur", title: "Launch Plan", description: "Go-to-market plan", order: 7 },
      { big_win_title: "Launch Fitur", title: "Fitur Launch", description: "Fitur berhasil launch", order: 8 },
      { big_win_title: "Ukur Dampak", title: "Impact Report", description: "Sebelum vs sesudah", order: 9 },
      { big_win_title: "Ukur Dampak", title: "Iterasi Plan", description: "Rencana iterasi", order: 10 },
    ],
    daily_activities: {
      spiritual: ["Doa", "Refleksi", "Bersyukur"],
      physical: ["Jalan sela meeting", "Jaga tidur", "Minum air"],
      knowledge: ["Strategi produk", "Tren tech", "Data analytics"],
      social: ["1-on-1 stakeholder", "Sinkron tim", "User interview"],
      character: ["Prioritasi", "Evaluasi keputusan", "Jurnal belajar"],
      dream_skill: ["Strategic thinking", "Data analysis", "Komunikasi"],
    },
    alternative_futures: [
      { title: "Product Owner", description: "Fokus execution & backlog.", skills: ["Agile", "Backlog", "Stakeholder", "Tech literacy"] },
      { title: "Growth PM", description: "Fokus metrik growth.", skills: ["Growth loops", "A/B testing", "Analytics", "Eksperimen"] },
      { title: "Head of Product", description: "Pimpin tim PM.", skills: ["Leadership", "Vision", "Org design", "Strategy"] },
    ],
    min_age: 18,
    max_age: 35,
  },
  {
    slug: "e-commerce-owner",
    title: "Pemilik Toko Online",
    emoji: "🛒",
    color: "from-yellow-600 to-orange-500",
    category: "business",
    duration: "3-6 bulan",
    description: "Jalur dari riset produk sampe bisnis e-commerce jalan. Cocok buat yang mau jualan di Shopee atau Tokopedia.",
    why_matters: "E-commerce booming di Indonesia. Modal kecil udah bisa mulai. Yang bikin beda strategi dan konsistensi.",
    career_options: ["Toko Online Owner", "Dropshipper", "Brand Owner", "E-commerce Manager", "Digital Distributor", "Social Seller"],
    success_examples: [],
    big_wins: [
      { title: "Riset Produk", description: "Temuin produk laku margin bagus", why_it_matters: "Produk jantung bisnis", alternative_path: "Affiliate dulu", order: 1 },
      { title: "Buka Toko", description: "Toko marketplace/website", why_it_matters: "Foto deskripsi nentuin konversi", alternative_path: "IG/TikTok Shop dulu", order: 2 },
      { title: "Transaksi Pertama", description: "Order dari pembeli ga dikenal", why_it_matters: "Bukti produk laku", alternative_path: "Jual ke teman", order: 3 },
      { title: "100 Transaksi", description: "Rating 4.8", why_it_matters: "Naik seller premium", alternative_path: "Produk digital", order: 4 },
      { title: "Bisnis Otomatis", description: "Sistem dan tim jalan", why_it_matters: "Bisnis bukan freelance", alternative_path: "Fokus 1 channel", order: 5 },
    ],
    small_wins: [
      { big_win_title: "Riset Produk", title: "Riset 20 Produk", description: "Cek margin kompetitor", order: 1 },
      { big_win_title: "Riset Produk", title: "Survey Supplier", description: "Hubungi 5 supplier", order: 2 },
      { big_win_title: "Buka Toko", title: "Akun Marketplace", description: "Buka seller Tokopedia", order: 3 },
      { big_win_title: "Buka Toko", title: "Upload 10 Produk", description: "Foto & deskripsi", order: 4 },
      { big_win_title: "Transaksi Pertama", title: "Order Pertama", description: "Packing dan kirim", order: 5 },
      { big_win_title: "Transaksi Pertama", title: "Review 5 Bintang", description: "Dapet rating 5", order: 6 },
      { big_win_title: "100 Transaksi", title: "25 Transaksi", description: "Rating > 4.5", order: 7 },
      { big_win_title: "100 Transaksi", title: "100 Transaksi", description: "Rating > 4.8", order: 8 },
      { big_win_title: "Bisnis Otomatis", title: "Rekrut Admin", description: "Bantu packing", order: 9 },
      { big_win_title: "Bisnis Otomatis", title: "Sistem Operasional", description: "SOP selesai", order: 10 },
    ],
    daily_activities: {
      spiritual: ["Doa", "Bersyukur", "Sedekah"],
      physical: ["Posture", "Stretching", "Atur jam"],
      knowledge: ["Pricing", "Algoritma marketplace", "Foto produk"],
      social: ["Service pelanggan", "Follow up", "Negosiasi"],
      character: ["Catat keuangan", "Packing disiplin", "Review bulanan"],
      dream_skill: ["Foto produk", "Copywriting", "Inventory"],
    },
    alternative_futures: [
      { title: "Brand Owner", description: "Bikin brand dengan margin lebih.", skills: ["Branding", "Produksi", "Marketing", "Legalitas"] },
      { title: "E-commerce Manager", description: "Kelola toko orang lain.", skills: ["Marketplace", "Leadership", "Analytics", "Ads"] },
      { title: "Digital Distributor", description: "Distributor resmi brand.", skills: ["Supply chain", "Sales", "Negosiasi", "Inventory"] },
    ],
    min_age: 16,
    max_age: 35,
  },
  {
    slug: "nurse",
    title: "Perawat Profesional",
    emoji: "👩‍⚕️",
    color: "from-cyan-500 to-blue-500",
    category: "health",
    duration: "3-4 tahun",
    description: "Jalur dari pendidikan sampai praktik. Buat lo yang punya hati besar dan pengen ngerawat orang lain.",
    why_matters: "Perawat pahlawan paling dekat sama pasien. 24 jam nemenin dan support. Tanpa perawat sistem kesehatan ga jalan.",
    career_options: ["Perawat RS", "Perawat Komunitas", "Perawat Home Care", "Perawat Pendidik", "Perawat Forensik", "Manajer Keperawatan"],
    success_examples: [],
    big_wins: [
      { title: "Lulus Ners", description: "S1 + Profesi Ners", why_it_matters: "Kompetensi klinis", alternative_path: "D3 Keperawatan dulu", order: 1 },
      { title: "STR & SIPP", description: "Surat Tanda Registrasi", why_it_matters: "Lisensi legal", alternative_path: "Luar negeri", order: 2 },
      { title: "Kerja Perawat", description: "Praktik di RS", why_it_matters: "Pengalaman langsung", alternative_path: "Perawat komunitas", order: 3 },
      { title: "Spesialisasi", description: "ICU, anak, jiwa", why_it_matters: "Gaji lebih baik", alternative_path: "Manajemen", order: 4 },
      { title: "Pelatih", description: "Ngajar atau instruktur", why_it_matters: "Bentuk generasi baru", alternative_path: "Kepala ruangan", order: 5 },
    ],
    small_wins: [
      { big_win_title: "Lulus Ners", title: "IPK 3.0+", description: "S1 Keperawatan", order: 1 },
      { big_win_title: "Lulus Ners", title: "Lulus Ners", description: "Profesi selesai", order: 2 },
      { big_win_title: "STR & SIPP", title: "Urus STR", description: "Surat Registrasi", order: 3 },
      { big_win_title: "STR & SIPP", title: "Dapat SIPP", description: "Izin Praktik", order: 4 },
      { big_win_title: "Kerja Perawat", title: "Apply 10 RS", description: "Lamaran RS", order: 5 },
      { big_win_title: "Kerja Perawat", title: "Mulai Dinas", description: "Hari pertama", order: 6 },
      { big_win_title: "Spesialisasi", title: "Pilih Unit", description: "Tentukan spesialis", order: 7 },
      { big_win_title: "Spesialisasi", title: "Ikut Diklat", description: "Sertifikasi", order: 8 },
      { big_win_title: "Pelatih", title: "Workshop", description: "Metode pengajaran", order: 9 },
      { big_win_title: "Pelatih", title: "Mulai Ngajar", description: "Instruktur klinik", order: 10 },
    ],
    daily_activities: {
      spiritual: ["Doa shift", "Baca kitab", "Bersyukur"],
      physical: ["Kebugaran", "Stretching", "Tidur cukup"],
      knowledge: ["Jurnal keperawatan", "Update SOP", "Prosedur baru"],
      social: ["Komunikasi pasien", "Empati", "Kolaborasi dokter"],
      character: ["Catat pengalaman", "Manajemen stres", "Profesionalisme"],
      dream_skill: ["Prosedur klinis", "Komunikasi", "Critical thinking"],
    },
    alternative_futures: [
      { title: "Perawat Home Care", description: "Rawat pasien di rumah.", skills: ["Mandiri", "Komunikasi", "Jadwal", "Kewirausahaan"] },
      { title: "Manajer", description: "Pimpin tim perawat.", skills: ["Kepemimpinan", "SDM", "Quality control", "SOP"] },
      { title: "Perawat Forensik", description: "Bantu investigasi kriminal.", skills: ["Forensik", "Dokumentasi", "Polisi", "Trauma"] },
    ],
    min_age: 16,
    max_age: 35,
  },
  {
    slug: "psychologist",
    title: "Psikolog",
    emoji: "🧠",
    color: "from-indigo-500 to-purple-500",
    category: "health",
    duration: "5-6 tahun",
    description: "Jalur dari S1 Psikologi sampe lulus profesi. Buat lo yang tertarik cara kerja pikiran manusia.",
    why_matters: "Kesehatan mental makin penting. Psikolog dibutuhin di sekolah, perusahaan, RS. Lo bisa ubah hidup orang.",
    career_options: ["Psikolog Klinis", "Psikolog Pendidikan", "Psikolog Industri", "Psikolog Anak", "Konselor", "Peneliti"],
    success_examples: [],
    big_wins: [
      { title: "Lulus S1 Psikologi", description: "Konsentrasi sesuai minat", why_it_matters: "Fundamental teori", alternative_path: "S1 lain + minor", order: 1 },
      { title: "Program Profesi", description: "S2 Profesi Psikolog", why_it_matters: "Gelar psikolog dari profesi", alternative_path: "S2 Magister Terapan", order: 2 },
      { title: "SIP Psikolog", description: "Izin dari HIMPSI", why_it_matters: "Lisensi legal", alternative_path: "Asisten psikolog", order: 3 },
      { title: "Praktik", description: "Klinik/sekolah/pribadi", why_it_matters: "Belajar ke praktik", alternative_path: "Psikolog Industri", order: 4 },
      { title: "Spesialisasi", description: "Sertifikasi terapi", why_it_matters: "Expert dan rate naik", alternative_path: "Content creator mental health", order: 5 },
    ],
    small_wins: [
      { big_win_title: "Lulus S1 Psikologi", title: "IPK 3.4+", description: "Buat S2 kompetitif", order: 1 },
      { big_win_title: "Lulus S1 Psikologi", title: "Lulus S1", description: "S1 tuntas", order: 2 },
      { big_win_title: "Program Profesi", title: "Lulus S2 Profesi", description: "Profesi selesai", order: 3 },
      { big_win_title: "Program Profesi", title: "UKP Lulus", description: "Uji Kompetensi", order: 4 },
      { big_win_title: "SIP Psikolog", title: "Urus HIMPSI", description: "Dokumen", order: 5 },
      { big_win_title: "SIP Psikolog", title: "SIP Terbit", description: "Resmi psikolog!", order: 6 },
      { big_win_title: "Praktik", title: "Supervisi Awal", description: "Diskusi praktik", order: 7 },
      { big_win_title: "Praktik", title: "10 Klien", description: "Tangani 10 klien", order: 8 },
      { big_win_title: "Spesialisasi", title: "Pilih Metode", description: "CBT, DBT, EMDR", order: 9 },
      { big_win_title: "Spesialisasi", title: "Sertifikasi", description: "Training dan sertifikasi", order: 10 },
    ],
    daily_activities: {
      spiritual: ["Meditasi", "Refleksi", "Doa"],
      physical: ["Olahraga", "Jaga energi", "Tidur"],
      knowledge: ["Jurnal psikologi", "Update DSM", "Terapi baru"],
      social: ["Active listening", "Komunikasi", "HIMPSI"],
      character: ["Supervisi", "Profesionalisme", "Self-care"],
      dream_skill: ["Asesmen", "Konseling", "Intervensi"],
    },
    alternative_futures: [
      { title: "Konselor Karir", description: "Bantu milih jurusan/karir.", skills: ["Konseling", "Asesmen", "Pengetahuan industri", "Komunikasi"] },
      { title: "HR & People Dev", description: "Rekrutmen, training.", skills: ["Psikologi industri", "Rekrutmen", "Training", "Org dev"] },
      { title: "Content Creator Mental Health", description: "Edukasi di media sosial.", skills: ["Konten", "Public speaking", "Penulisan", "Klinis"] },
    ],
    min_age: 16,
    max_age: 35,
  },
  {
    slug: "nutritionist",
    title: "Ahli Gizi",
    emoji: "🥗",
    color: "from-green-500 to-emerald-600",
    category: "health",
    duration: "4-5 tahun",
    description: "Jalur dari kuliah Ilmu Gizi sampe praktik konsultasi. Buat lo yang percaya makanan adalah obat terbaik.",
    why_matters: "Gizi fondasi kesehatan. Di era penyakit degeneratif, ahli gizi makin dibutuhin bantu orang hidup lebih sehat.",
    career_options: ["Ahli Gizi RS", "Konsultan Gizi", "Ahli Gizi Olahraga", "Food Service Manager", "Peneliti Gizi", "Nutrition Creator"],
    success_examples: [],
    big_wins: [
      { title: "Lulus S1 Ilmu Gizi", description: "Ilmu pangan metabolisme", why_it_matters: "Biokimia bedain dari influencer", alternative_path: "D3 Gizi dulu", order: 1 },
      { title: "Profesi Dietisien", description: "Pendidikan profesi + UKOM", why_it_matters: "Lisensi praktik klinis", alternative_path: "Nutrisionis industri", order: 2 },
      { title: "STR & SIPP", description: "Registrasi ahli gizi", why_it_matters: "Lisensi legal", alternative_path: "R&D makanan", order: 3 },
      { title: "Konsultasi", description: "Klinik RS atau pribadi", why_it_matters: "Skill assessment terasah", alternative_path: "Gizi olahraga", order: 4 },
      { title: "Spesialisasi", description: "Gizi klinis/olahraga", why_it_matters: "Value naik", alternative_path: "Food blogger", order: 5 },
    ],
    small_wins: [
      { big_win_title: "Lulus S1 Ilmu Gizi", title: "IPK 3.2+", description: "Target S1", order: 1 },
      { big_win_title: "Lulus S1 Ilmu Gizi", title: "Praktikum", description: "Praktikum gizi klinis", order: 2 },
      { big_win_title: "Profesi Dietisien", title: "Lulus Profesi", description: "Pendidikan profesi", order: 3 },
      { big_win_title: "Profesi Dietisien", title: "UKOM Gizi", description: "Uji kompetensi", order: 4 },
      { big_win_title: "STR & SIPP", title: "Urus STR", description: "Registrasi", order: 5 },
      { big_win_title: "STR & SIPP", title: "Dapat SIPP", description: "Izin praktik", order: 6 },
      { big_win_title: "Konsultasi", title: "Praktik Pertama", description: "Konsultasi klien", order: 7 },
      { big_win_title: "Konsultasi", title: "10 Klien", description: "Hasil baik", order: 8 },
      { big_win_title: "Spesialisasi", title: "Pilih Area", description: "Gizi klinis/olahraga", order: 9 },
      { big_win_title: "Spesialisasi", title: "Sertifikasi", description: "Training", order: 10 },
    ],
    daily_activities: {
      spiritual: ["Doa", "Bersyukur", "Mindful"],
      physical: ["Olahraga", "Cek kesehatan", "Minum"],
      knowledge: ["Update gizi", "Jurnal dietetik", "Tren pangan"],
      social: ["Edukasi pasien", "Komunitas", "Kolaborasi dokter"],
      character: ["Catat kasus", "Evaluasi diet", "Detail"],
      dream_skill: ["Assessment", "Diet planning", "Edukasi"],
    },
    alternative_futures: [
      { title: "Food Service Manager", description: "Kelola gizi di RS atau hotel.", skills: ["Dapur", "HACCP", "Budgeting", "Menu"] },
      { title: "Peneliti Gizi", description: "Riset pangan dan gizi.", skills: ["Metodologi", "Data", "Publikasi", "Lab"] },
      { title: "Content Creator Gizi", description: "Edukasi gizi di sosmed.", skills: ["Konten", "Ilmu gizi", "Komunikasi", "Foto"] },
    ],
    min_age: 16,
    max_age: 35,
  },
  {
    slug: "pharmacist",
    title: "Apoteker",
    emoji: "💊",
    color: "from-emerald-600 to-teal-600",
    category: "health",
    duration: "4-5 tahun",
    description: "Jalur dari kuliah farmasi sampe praktik di apotek atau industri. Garda terakhir keamanan obat.",
    why_matters: "Apoteker pastiin pasien dapet obat tepat, dosis tepat. Peran krusial yang ngga bisa diganti.",
    career_options: ["Apoteker RS", "Apoteker Komunitas", "Apoteker Industri", "Peneliti Obat", "Regulatory Affairs", "Dosen Farmasi"],
    success_examples: [],
    big_wins: [
      { title: "Lulus S1 Farmasi", description: "Ilmu obat, kimia farmasi", why_it_matters: "Fundamental kefarmasian", alternative_path: "D3 Farmasi dulu", order: 1 },
      { title: "Profesi Apoteker", description: "Pendidikan + sumpah", why_it_matters: "Gelar dari profesi", alternative_path: "Kerja industri", order: 2 },
      { title: "STR & SIPA", description: "Registrasi apoteker", why_it_matters: "Lisensi legal", alternative_path: "Regulatory affairs", order: 3 },
      { title: "Praktik", description: "Apotek/RS", why_it_matters: "Konseling obat", alternative_path: "QC produksi", order: 4 },
      { title: "Spesialisasi", description: "Farmasi klinik atau R&D", why_it_matters: "Buka peluang", alternative_path: "Distributor", order: 5 },
    ],
    small_wins: [
      { big_win_title: "Lulus S1 Farmasi", title: "IPK 3.0+", description: "Farmasi butuh IPK", order: 1 },
      { big_win_title: "Lulus S1 Farmasi", title: "Praktikum Lab", description: "Semua lab selesai", order: 2 },
      { big_win_title: "Profesi Apoteker", title: "Lulus Profesi", description: "Pendidikan selesai", order: 3 },
      { big_win_title: "Profesi Apoteker", title: "Sumpah", description: "Sumpah apoteker", order: 4 },
      { big_win_title: "STR & SIPA", title: "Urus STR", description: "Registrasi", order: 5 },
      { big_win_title: "STR & SIPA", title: "Dapat SIPA", description: "Izin praktik", order: 6 },
      { big_win_title: "Praktik", title: "Kerja di Apotek", description: "Mulai praktik", order: 7 },
      { big_win_title: "Praktik", title: "Racik & Konseling", description: "Resep pertama", order: 8 },
      { big_win_title: "Spesialisasi", title: "Spesialisasi", description: "Farmasi klinik", order: 9 },
      { big_win_title: "Spesialisasi", title: "Sertifikasi", description: "Training", order: 10 },
    ],
    daily_activities: {
      spiritual: ["Doa", "Bersyukur", "Baca kitab"],
      physical: ["Stamina", "Tidur", "Asupan"],
      knowledge: ["Jurnal farmasi", "Update DIO", "Obat baru"],
      social: ["Konseling", "Kolaborasi dokter", "Edukasi"],
      character: ["Teliti", "Etika", "Rahasia"],
      dream_skill: ["Farmakologi", "Manajemen apotek", "Regulasi"],
    },
    alternative_futures: [
      { title: "Regulatory Affairs", description: "Urus izin edar obat BPOM.", skills: ["Regulasi", "Dokumentasi", "Standarisasi", "Komunikasi"] },
      { title: "Peneliti Farmasi", description: "R&D obat baru.", skills: ["R&D", "Formulasi", "Uji klinis", "Lab"] },
      { title: "Distributor Obat", description: "Supply chain obat.", skills: ["Supply chain", "Logistik", "Warehouse", "Cold chain"] },
    ],
    min_age: 16,
    max_age: 35,
  },
  {
    slug: "cybersecurity",
    title: "Ahli Keamanan Siber",
    emoji: "🔐",
    color: "from-red-700 to-slate-900",
    category: "tech",
    duration: "1-2 tahun",
    description: "Jalur dari dasar networking sampe penetration testing. Buat lo yang suka hacking etis.",
    why_matters: "Digitalisasi bikin data berharga dan rawan bocor. Cybersecurity expert makin kritis dan demand tinggi.",
    career_options: ["Security Analyst", "Penetration Tester", "SOC Analyst", "Security Engineer", "Incident Responder", "CISO"],
    success_examples: [],
    big_wins: [
      { title: "Networking & Security", description: "TCP/IP, firewall, VPN", why_it_matters: "Tanpa jaringan ga ngerti security", alternative_path: "CompTIA Security+", order: 1 },
      { title: "Linux & Scripting", description: "Linux command line", why_it_matters: "Tools jalan di Linux", alternative_path: "Windows security", order: 2 },
      { title: "Tools Security", description: "Nmap, Wireshark, Burp Suite", why_it_matters: "Tools utama pentester", alternative_path: "Blue team", order: 3 },
      { title: "Lab & Sertifikasi", description: "CTF, HackTheBox, CEH", why_it_matters: "Sertifikasi buktiin skill", alternative_path: "Portofolio write-up", order: 4 },
      { title: "Kerja Security", description: "Job pertama cybersecurity", why_it_matters: "Mulai karir resmi", alternative_path: "Bug bounty freelance", order: 5 },
    ],
    small_wins: [
      { big_win_title: "Networking & Security", title: "OSI Model", description: "7 layer protokol", order: 1 },
      { big_win_title: "Networking & Security", title: "Firewall & VPN", description: "Konfigurasi dasar", order: 2 },
      { big_win_title: "Linux & Scripting", title: "Linux Master", description: "Command line", order: 3 },
      { big_win_title: "Linux & Scripting", title: "Bash/Python", description: "Script otomasi", order: 4 },
      { big_win_title: "Tools Security", title: "Nmap & Wireshark", description: "Scan network", order: 5 },
      { big_win_title: "Tools Security", title: "Burp Suite", description: "Web security testing", order: 6 },
      { big_win_title: "Lab & Sertifikasi", title: "HackTheBox", description: "50 box completed", order: 7 },
      { big_win_title: "Lab & Sertifikasi", title: "Sertif eJPT", description: "eLearnSecurity JPT", order: 8 },
      { big_win_title: "Kerja Security", title: "Apply 20", description: "Kirim lamaran", order: 9 },
      { big_win_title: "Kerja Security", title: "Job Offer", description: "Offer pertama", order: 10 },
    ],
    daily_activities: {
      spiritual: ["Doa", "Etika hacking", "Refleksi"],
      physical: ["Posture", "Stretching", "Tidur"],
      knowledge: ["Update CVE", "Security blog", "Threat intel"],
      social: ["Komunitas hacker", "Forum", "Reporting"],
      character: ["Etis & jawab", "Teliti", "Continuous learning"],
      dream_skill: ["Penetration testing", "Reverse engineering", "Incident response"],
    },
    alternative_futures: [
      { title: "SOC Analyst", description: "Monitor ancaman di SOC.", skills: ["SIEM", "Incident response", "Log analysis", "Threat hunting"] },
      { title: "Security Engineer", description: "Bangun sistem keamanan.", skills: ["Hardening", "Cloud security", "IAC", "Identity"] },
      { title: "Bug Bounty Hunter", description: "Cari vuln dibayar.", skills: ["Web security", "Mobile security", "Recon", "Reporting"] },
    ],
    min_age: 16,
    max_age: 35,
  },
  {
    slug: "data-scientist",
    title: "Data Scientist",
    emoji: "📊",
    color: "from-blue-600 to-violet-600",
    category: "tech",
    duration: "1-2 tahun",
    description: "Jalur dari statistika sampe machine learning. Buat lo yang suka bedah data.",
    why_matters: "Data minyak baru. Perusahaan butuh orang bedah data buat keputusan. Data scientist profesi paling dicari.",
    career_options: ["Data Scientist", "Data Analyst", "ML Engineer", "Data Engineer", "BI Analyst", "AI Engineer"],
    success_examples: [],
    big_wins: [
      { title: "Statistika", description: "Probabilitas, linear algebra", why_it_matters: "ML tanpa statistik = magic", alternative_path: "Data analyst dulu", order: 1 },
      { title: "Python & Tools", description: "Pandas, NumPy, Scikit-learn", why_it_matters: "Stack utama", alternative_path: "R dulu", order: 2 },
      { title: "SQL & Database", description: "Query kompleks, join", why_it_matters: "Data di database", alternative_path: "Excel dulu", order: 3 },
      { title: "ML Project", description: "Data gathering-deployment", why_it_matters: "Portofolio dari project", alternative_path: "Kaggle", order: 4 },
      { title: "Portofolio & Job", description: "Solid portfolio", why_it_matters: "Bidang kompetitif", alternative_path: "Freelance analytics", order: 5 },
    ],
    small_wins: [
      { big_win_title: "Statistika", title: "Probabilitas", description: "Distribusi, Bayesian", order: 1 },
      { big_win_title: "Statistika", title: "Linear Algebra", description: "Matriks & vector", order: 2 },
      { big_win_title: "Python & Tools", title: "Python Dasar", description: "Pandas & NumPy", order: 3 },
      { big_win_title: "Python & Tools", title: "Scikit-learn", description: "Klasifikasi, regresi", order: 4 },
      { big_win_title: "SQL & Database", title: "SQL Mahir", description: "Join, window function", order: 5 },
      { big_win_title: "SQL & Database", title: "DB Design", description: "Normalisasi", order: 6 },
      { big_win_title: "ML Project", title: "ML Project 1", description: "Gathering, EDA, model", order: 7 },
      { big_win_title: "ML Project", title: "Kaggle", description: "Submit kompetisi", order: 8 },
      { big_win_title: "Portofolio & Job", title: "3 Project", description: "Portofolio", order: 9 },
      { big_win_title: "Portofolio & Job", title: "Apply & Offer", description: "Job offer", order: 10 },
    ],
    daily_activities: {
      spiritual: ["Doa", "Fokus", "Bersyukur"],
      physical: ["Posture", "Stretching", "Jalan"],
      knowledge: ["Update ML/DL", "Baca paper", "Teknik baru"],
      social: ["Diskusi", "Sharing", "Mentoring"],
      character: ["Teliti data", "Skeptis", "Curiosity"],
      dream_skill: ["Machine learning", "Deep learning", "Data engineering"],
    },
    alternative_futures: [
      { title: "ML Engineer", description: "Implementasi ML ke production.", skills: ["ML engineering", "MLOps", "Deployment", "Cloud"] },
      { title: "Data Engineer", description: "Pipeline data & infrastructure.", skills: ["ETL", "Spark", "Airflow", "Warehouse"] },
      { title: "AI Engineer", description: "NLP, computer vision.", skills: ["Deep learning", "NLP/CV", "LLM", "PyTorch"] },
    ],
    min_age: 16,
    max_age: 35,
  },
  {
    slug: "game-developer",
    title: "Game Developer",
    emoji: "🎮",
    color: "from-rose-600 to-purple-600",
    category: "tech",
    duration: "1-2 tahun",
    description: "Jalur dari dasar programming sampe bikin game sendiri. Buat lo yang suka main game dan pengin bikinnya.",
    why_matters: "Industri game Indonesia makin ngebut. Kerja di studio, indie, atau ekspor game ke luar. Kreativitas + teknologi.",
    career_options: ["Game Programmer", "Game Designer", "Game Artist", "Game Producer", "Indie Developer", "Technical Artist"],
    success_examples: [],
    big_wins: [
      { title: "Dasar Game Dev", description: "Pilih engine, logic dasar", why_it_matters: "Engine tepat buat tujuan", alternative_path: "Text-based game dulu", order: 1 },
      { title: "Game Sederhana", description: "Pong/Snake/Flappy Bird", why_it_matters: "Game loop & logic", alternative_path: "Game jam 48 jam", order: 2 },
      { title: "Asset & Desain", description: "Asset visual + UI", why_it_matters: "Visual dan audio penting", alternative_path: "Asset store", order: 3 },
      { title: "Game Jadi & Rilis", description: "Rilis di itch.io/Play Store", why_it_matters: "Portofolio riil", alternative_path: "Prototyping terus", order: 4 },
      { title: "Kontrak/Job", description: "Kerja di studio atau project", why_it_matters: "Mulai karir pro", alternative_path: "Indie publish", order: 5 },
    ],
    small_wins: [
      { big_win_title: "Dasar Game Dev", title: "Unity/Unreal", description: "Engine siap", order: 1 },
      { big_win_title: "Dasar Game Dev", title: "C# atau C++", description: "Bahasa scripting", order: 2 },
      { big_win_title: "Game Sederhana", title: "Game Pertama", description: "Pong atau Snake", order: 3 },
      { big_win_title: "Game Sederhana", title: "Game 2D", description: "Score & game over", order: 4 },
      { big_win_title: "Asset & Desain", title: "Asset Game", description: "Karakter background audio", order: 5 },
      { big_win_title: "Asset & Desain", title: "UI Game", description: "Main menu, pause", order: 6 },
      { big_win_title: "Game Jadi & Rilis", title: "Build Game", description: "Build desktop/mobile", order: 7 },
      { big_win_title: "Game Jadi & Rilis", title: "Rilis Itch.io", description: "Game bisa didownload", order: 8 },
      { big_win_title: "Kontrak/Job", title: "Portfolio Siap", description: "3 game di portofolio", order: 9 },
      { big_win_title: "Kontrak/Job", title: "Job/Project", description: "Project bayaran", order: 10 },
    ],
    daily_activities: {
      spiritual: ["Doa", "Fokus", "Bersyukur"],
      physical: ["Posture", "Stretching", "Olahraga"],
      knowledge: ["Game design theory", "Engine update", "Optimasi"],
      social: ["Game jam", "Komunitas indie", "Feedback tester"],
      character: ["Iterasi", "Terima kritik", "Problem solving"],
      dream_skill: ["Gameplay programming", "Shader & VFX", "Optimasi"],
    },
    alternative_futures: [
      { title: "Game Designer", description: "Rancang mekanik & level.", skills: ["Game design", "Level design", "Narrative", "Balancing"] },
      { title: "Technical Artist", description: "Jembatan artis-programmer.", skills: ["Shader", "Pipeline", "Python/tools", "Rigging"] },
      { title: "Indie Studio", description: "Bikin studio game sendiri.", skills: ["Entrepreneurship", "Full-stack", "Marketing", "Project mgmt"] },
    ],
    min_age: 14,
    max_age: 35,
  },
  {
    slug: "chef",
    title: "Koki Profesional",
    emoji: "👨‍🍳",
    color: "from-red-600 to-orange-600",
    category: "lifestyle",
    duration: "2-4 tahun",
    description: "Jalur dari masak dasar sampe kerja di restoran atau punya usaha kuliner.",
    why_matters: "Kuliner passion yang ga pernah mati. Koki bukan cuma masak enak — lo bikin orang bahagia lewat makanan.",
    career_options: ["Chef Restoran", "Pastry Chef", "Personal Chef", "Food Stylist", "Konsultan Kuliner", "Pemilik Restoran"],
    success_examples: [],
    big_wins: [
      { title: "Teknik Dasar Masak", description: "Knife skills, stock, sauce", why_it_matters: "Dasar nentuin hasil", alternative_path: "Kursus online", order: 1 },
      { title: "Dapur Profesional", description: "Magang restoran commis", why_it_matters: "Beda 180 derajat", alternative_path: "Catering kecil", order: 2 },
      { title: "Spesialisasi", description: "Pastry/asian/western", why_it_matters: "Nilai lebih & gaji tinggi", alternative_path: "Food stylist", order: 3 },
      { title: "Chef de Partie", description: "Pimpin 1 section", why_it_matters: "Promosi pertama", alternative_path: "Bisnis sendiri", order: 4 },
      { title: "Chef Eksekutif", description: "Head chef atau buka resto", why_it_matters: "Puncak karir", alternative_path: "Konsultan", order: 5 },
    ],
    small_wins: [
      { big_win_title: "Teknik Dasar Masak", title: "Knife Skills", description: "Cincang, julienne", order: 1 },
      { big_win_title: "Teknik Dasar Masak", title: "5 Sauce Ibu", description: "Bechamel, veloute, dll", order: 2 },
      { big_win_title: "Dapur Profesional", title: "Magang", description: "Magang 3 bulan resto", order: 3 },
      { big_win_title: "Dapur Profesional", title: "Survive Shift", description: "Shift pertama", order: 4 },
      { big_win_title: "Spesialisasi", title: "Pilih Spesialisasi", description: "Pastry/asian/western", order: 5 },
      { big_win_title: "Spesialisasi", title: "Signature Dish", description: "Menu signature", order: 6 },
      { big_win_title: "Chef de Partie", title: "Lead Section", description: "Pimpin stasiun", order: 7 },
      { big_win_title: "Chef de Partie", title: "Train Junior", description: "Ngajari commis", order: 8 },
      { big_win_title: "Chef Eksekutif", title: "Sous Chef", description: "Naik sous chef", order: 9 },
      { big_win_title: "Chef Eksekutif", title: "Buka Resto", description: "Buka bisnis kuliner", order: 10 },
    ],
    daily_activities: {
      spiritual: ["Doa masak", "Bersyukur", "Mindful"],
      physical: ["Stamina dapur", "Posture berdiri", "Stretching"],
      knowledge: ["Resep baru", "Food science", "Safety"],
      social: ["Team dapur", "FOH komunkasi", "Feedback"],
      character: ["Speed teliti", "Calm pressure", "Kebersihan"],
      dream_skill: ["Cooking techniques", "Plating", "Menu development"],
    },
    alternative_futures: [
      { title: "Pastry Chef", description: "Spesialis dessert dan roti.", skills: ["Pastry", "Baking", "Gula", "Krim"] },
      { title: "Food Stylist", description: "Styling makanan foto/video.", skills: ["Styling", "Fotografi", "Prop", "Tren"] },
      { title: "Konsultan Kuliner", description: "Bantu bisnis F&B.", skills: ["Menu development", "Operation", "Training", "Cost control"] },
    ],
    min_age: 16,
    max_age: 35,
  },
  {
    slug: "travel-vlogger",
    title: "Travel Vlogger",
    emoji: "🌍",
    color: "from-cyan-500 to-sky-500",
    category: "lifestyle",
    duration: "6-12 bulan",
    description: "Jalur dari nol jadi travel vlogger yang bisa jalan-jalan dan dibayar buat itu.",
    why_matters: "Travel vlogger bukan cuma jalan-jalan — lo bercerita, ngasih tips, dan ngenalin budaya ke dunia.",
    career_options: ["Travel Vlogger", "Travel Blogger", "Videographer", "Tour Guide", "Travel Agent", "Destination Marketer"],
    success_examples: [],
    big_wins: [
      { title: "Niche & Gaya", description: "Tentukan niche travel", why_it_matters: "Bikin identitas unik", alternative_path: "Vlog lokal dulu", order: 1 },
      { title: "Konten Perjalanan", description: "Rekam edit travel pertama", why_it_matters: "Edit cerita penting", alternative_path: "Photo blogging", order: 2 },
      { title: "1000 Subscriber", description: "Dapetin 1000 subscriber", why_it_matters: "Monetisasi YPP", alternative_path: "Afiliasi travel", order: 3 },
      { title: "Kerja Sama", description: "Hotel/tourism board collab", why_it_matters: "Kolab pertama", alternative_path: "Couchsurfing", order: 4 },
      { title: "Full-time Travel", description: "Hidup dari travel", why_it_matters: "Mimpi jadi nyata", alternative_path: "Freelance videographer", order: 5 },
    ],
    small_wins: [
      { big_win_title: "Niche & Gaya", title: "Riset 10 Travel Vlogger", description: "Analisis niche", order: 1 },
      { big_win_title: "Niche & Gaya", title: "Buat Branding", description: "Nama, logo, style", order: 2 },
      { big_win_title: "Konten Perjalanan", title: "Trip Pertama", description: "Trip lokal 3 hari", order: 3 },
      { big_win_title: "Konten Perjalanan", title: "Video Pertama", description: "Upload vlog perjalanan", order: 4 },
      { big_win_title: "1000 Subscriber", title: "Konsisten 30 Hari", description: "Upload 2x seminggu", order: 5 },
      { big_win_title: "1000 Subscriber", title: "1000 Subs", description: "Subscriber organik", order: 6 },
      { big_win_title: "Kerja Sama", title: "Media Kit", description: "Buat media kit", order: 7 },
      { big_win_title: "Kerja Sama", title: "Kolab Pertama", description: "Hotel/homestay collab", order: 8 },
      { big_win_title: "Full-time Travel", title: "Monetisasi", description: "Ads sponsorship", order: 9 },
      { big_win_title: "Full-time Travel", title: "Trip Luar Negeri", description: "Trip internasional", order: 10 },
    ],
    daily_activities: {
      spiritual: ["Doa travel", "Bersyukur", "Menikmati"],
      physical: ["Jalan kaki banyak", "Jaga kesehatan", "Packing"],
      knowledge: ["Destinasi baru", "Tips travel", "Budaya lokal"],
      social: ["Interaksi lokal", "Networking traveler", "Storytelling"],
      character: ["Adaptif", "Flexible", "Keluar zona nyaman"],
      dream_skill: ["Video editing", "Photography", "Storytelling"],
    },
    alternative_futures: [
      { title: "Travel Blogger", description: "Tulis blog perjalanan.", skills: ["Penulisan", "Fotografi", "SEO", "Media sosial"] },
      { title: "Tour Guide", description: "Pemandu wisata lokal.", skills: ["Pengetahuan lokal", "Komunikasi", "Organisasi", "Bahasa"] },
      { title: "Destination Marketer", description: "Promosi destinasi.", skills: ["Marketing", "Content creation", "Networking", "Analytics"] },
    ],
    min_age: 16,
    max_age: 35,
  },
  {
    slug: "fitness-coach",
    title: "Fitness Coach",
    emoji: "💪",
    color: "from-amber-600 to-red-600",
    category: "lifestyle",
    duration: "6-12 bulan",
    description: "Jalur dari fitness enthusiast jadi coach profesional yang bisa bantu orang capai tujuan fitnes mereka.",
    why_matters: "Fitness bukan cuma fisik — ini mental dan gaya hidup. Jadi coach berarti lo bantu orang jadi versi terbaik diri mereka.",
    career_options: ["Personal Trainer", "Fitness Content Creator", "Online Coach", "Gym Manager", "Nutrition Coach", "Fitness Entrepreneur"],
    success_examples: [],
    big_wins: [
      { title: "Dasar Fitness", description: "Anatomi, biomekanik, nutrisi", why_it_matters: "Fundamental coach", alternative_path: "Jadi client dulu", order: 1 },
      { title: "Sertifikasi", description: "ACE/NASM/ISSA", why_it_matters: "Kredibilitas sertifikasi", alternative_path: "Pengalaman otodidak", order: 2 },
      { title: "Client Pertama", description: "Klien bayaran pertama", why_it_matters: "Transisi hobby ke pro", alternative_path: "Training teman gratis", order: 3 },
      { title: "Spesialisasi", description: "Weight loss/strength/sport", why_it_matters: "Niche lebih mahal", alternative_path: "General coach", order: 4 },
      { title: "Bisnis Fitness", description: "Online coaching atau gym", why_it_matters: "Skalasi bisnis", alternative_path: "Content creator fitness", order: 5 },
    ],
    small_wins: [
      { big_win_title: "Dasar Fitness", title: "Anatomi Dasar", description: "Otot dan gerakan", order: 1 },
      { big_win_title: "Dasar Fitness", title: "Program Pertama", description: "Buat program sendiri", order: 2 },
      { big_win_title: "Sertifikasi", title: "Cari Sertifikasi", description: "ACE atau NASM", order: 3 },
      { big_win_title: "Sertifikasi", title: "Lulus Sertifikasi", description: "Sertifikasi dapat", order: 4 },
      { big_win_title: "Client Pertama", title: "Free Trial", description: "Training teman gratis", order: 5 },
      { big_win_title: "Client Pertama", title: "Client Bayaran", description: "Klien pertama bayar", order: 6 },
      { big_win_title: "Spesialisasi", title: "Pilih Niche", description: "Weight loss/strength", order: 7 },
      { big_win_title: "Spesialisasi", title: "Program Spesifik", description: "Buat program niche", order: 8 },
      { big_win_title: "Bisnis Fitness", title: "Online Program", description: "Jual program online", order: 9 },
      { big_win_title: "Bisnis Fitness", title: "Launch Brand", description: "Launch brand fitness", order: 10 },
    ],
    daily_activities: {
      spiritual: ["Doa", "Syukur", "Mindful"],
      physical: ["Latihan rutin", "Cardio", "Stretching"],
      knowledge: ["Ilmu anatomi", "Nutrisi", "Teknik baru"],
      social: ["Komunikasi klien", "Komunitas gym", "Feedback"],
      character: ["Disiplin", "Konsisten", "Teladan"],
      dream_skill: ["Program design", "Teknik latihan", "Coaching"],
    },
    alternative_futures: [
      { title: "Fitness Content Creator", description: "Konten fitnes di sosmed.", skills: ["Content creation", "Fitness knowledge", "Public speaking", "Editing"] },
      { title: "Nutrition Coach", description: "Fokus gizi dan diet.", skills: ["Nutrition", "Diet planning", "Conseling", "Behavior change"] },
      { title: "Gym Manager", description: "Kelola operasional gym.", skills: ["Manajemen", "Sales", "Customer service", "Equipment"] },
    ],
    min_age: 16,
    max_age: 35,
  },
  {
    slug: "fashion-model",
    title: "Fashion Model",
    emoji: "🧍",
    color: "from-violet-600 to-pink-500",
    category: "lifestyle",
    duration: "3-12 bulan",
    description: "Jalur jadi fashion model dari portfolio sampe runway. Buat lo yang percaya diri dan tertarik dunia modeling.",
    why_matters: "Modeling bukan cuma wajah dan badan — ini soal profesionalisme dan personal brand. Industri fashion butuh talent diverse.",
    career_options: ["Fashion Model", "Editorial Model", "Commercial Model", "Runway Model", "Brand Ambassador", "Model Influencer"],
    success_examples: [],
    big_wins: [
      { title: "Portfolio Dasar", description: "Bikin portfolio dengan fotografer", why_it_matters: "Portfolio passport ke industri", alternative_path: "TFCD dulu", order: 1 },
      { title: "Komposit Siap", description: "Bikin comp card & digit branding", why_it_matters: "CV model", alternative_path: "Bikin IG portfolio", order: 2 },
      { title: "Casting Pertama", description: "Ikut casting resmi pertama", why_it_matters: "Exposure & pengalaman", alternative_path: "Submit online", order: 3 },
      { title: "Job Bayaran", description: "Dapet job bayaran pertama", why_it_matters: "Transisi ke pro", alternative_path: "Fitting model", order: 4 },
      { title: "Agensi & Karir", description: "Gabung agensi resmi", why_it_matters: "Scaling karir", alternative_path: "Freelance model", order: 5 },
    ],
    small_wins: [
      { big_win_title: "Portfolio Dasar", title: "Cari Fotografer", description: "Cari TFCD fotografer", order: 1 },
      { big_win_title: "Portfolio Dasar", title: "Shoot Portfolio", description: "Photo shoot 3 looks", order: 2 },
      { big_win_title: "Komposit Siap", title: "Buat Comp Card", description: "Front, profile, 3/4", order: 3 },
      { big_win_title: "Komposit Siap", title: "Digit Branding", description: "IG portfolio siap", order: 4 },
      { big_win_title: "Casting Pertama", title: "Cari Casting", description: "Info casting terdekat", order: 5 },
      { big_win_title: "Casting Pertama", title: "Dateng Casting", description: "Dateng ke casting", order: 6 },
      { big_win_title: "Job Bayaran", title: "Job Pertama", description: "Dapet job bayaran", order: 7 },
      { big_win_title: "Job Bayaran", title: "3 Job", description: "3 job dengan referral", order: 8 },
      { big_win_title: "Agensi & Karir", title: "Apply Agensi", description: "Daftar ke agensi", order: 9 },
      { big_win_title: "Agensi & Karir", title: "Gabung Agensi", description: "Resmi di agensi", order: 10 },
    ],
    daily_activities: {
      spiritual: ["Doa", "Syukur", "Afirmasi"],
      physical: ["Jaga badan", "Skincare", "Olahraga"],
      knowledge: ["Tren fashion", "Posing", "Catwalk"],
      social: ["Networking", "Follow up", "Interaksi"],
      character: ["Profesional", "Disiplin", "On time"],
      dream_skill: ["Posing", "Catwalk", "Expression"],
    },
    alternative_futures: [
      { title: "Brand Ambassador", description: "Wakilin brand di event.", skills: ["Public speaking", "Personal branding", "Social media", "Sales"] },
      { title: "Model Influencer", description: "Model + konten kreator.", skills: ["Content creation", "Personal brand", "Photography", "Engagement"] },
      { title: "Fashion Stylist", description: "Pindah ke belakang layar.", skills: ["Styling", "Wardrobe", "Tren", "Visi kreatif"] },
    ],
    min_age: 16,
    max_age: 35,
  },
  {
    slug: "photographer",
    title: "Fotografer Profesional",
    emoji: "📸",
    color: "from-gray-700 to-gray-900",
    category: "lifestyle",
    duration: "6-12 bulan",
    description: "Jalur dari hobi foto jadi fotografer profesional yang dibayar buat mengabadikan momen.",
    why_matters: "Fotografi ngajarin lo liat dunia dari sudut pandang beda. Jadi fotografer lo ngerekam sejarah dan emosi yang ga terulang.",
    career_options: ["Wedding Photographer", "Commercial Photographer", "Portrait Photographer", "Editorial Photographer", "Videographer", "Photo Editor"],
    success_examples: [],
    big_wins: [
      { title: "Kuasai Kamera", description: "Segitiga exposure, komposisi", why_it_matters: "Fundamental nentuin kualitas", alternative_path: "HP dulu", order: 1 },
      { title: "Lighting & Edit", description: "Natural & artificial light", why_it_matters: "Lighting bedain amatir-pro", alternative_path: "Filter aja dulu", order: 2 },
      { title: "Portofolio", description: "10 foto strong dengan niche", why_it_matters: "Portfolio nentuin klien", alternative_path: "Project 365", order: 3 },
      { title: "Client Pertama", description: "Dapet client bayaran", why_it_matters: "Transisi hobi ke pro", alternative_path: "Shoot teman gratis", order: 4 },
      { title: "Studio/Bisnis", description: "Buka studio atau full-time", why_it_matters: "Karir profesional", alternative_path: "Wedding vendor", order: 5 },
    ],
    small_wins: [
      { big_win_title: "Kuasai Kamera", title: "Segitiga Exposure", description: "ISO aperture shutter", order: 1 },
      { big_win_title: "Kuasai Kamera", title: "Komposisi", description: "Rule of thirds, lines", order: 2 },
      { big_win_title: "Lighting & Edit", title: "Lighting", description: "Natural + flash dasar", order: 3 },
      { big_win_title: "Lighting & Edit", title: "Lightroom/PS", description: "Editing dasar", order: 4 },
      { big_win_title: "Portofolio", title: "Pilih Niche", description: "Wedding/portrait/commercial", order: 5 },
      { big_win_title: "Portofolio", title: "10 Foto Kuat", description: "Portofolio siap", order: 6 },
      { big_win_title: "Client Pertama", title: "Shoot Portfolio", description: "Shoot gratis portofolio", order: 7 },
      { big_win_title: "Client Pertama", title: "Client Bayaran", description: "Job bayaran pertama", order: 8 },
      { big_win_title: "Studio/Bisnis", title: "Branding", description: "Buat nama & website", order: 9 },
      { big_win_title: "Studio/Bisnis", title: "Launch", description: "Launch jasa fotografi", order: 10 },
    ],
    daily_activities: {
      spiritual: ["Doa", "Syukur", "Apresiasi"],
      physical: ["Jaga stamina", "Posture", "Jalan"],
      knowledge: ["Teknik baru", "Edit terbaru", "Fotografer inspirasi"],
      social: ["Client komunikasi", "Kolaborasi", "Networking"],
      character: ["Rutin motret", "Evaluasi hasil", "Terima kritik"],
      dream_skill: ["Composition", "Lighting", "Editing"],
    },
    alternative_futures: [
      { title: "Videographer", description: "Video untuk wedding/event.", skills: ["Video", "Stabilization", "Editing", "Storytelling"] },
      { title: "Photo Editor", description: "Edit foto profesional.", skills: ["Photoshop", "Capture One", "Color grading", "Retouching"] },
      { title: "Creative Director", description: "Arahkan visi kreatif.", skills: ["Art direction", "Leadership", "Visual concept", "Client mgmt"] },
    ],
    min_age: 14,
    max_age: 35,
  },
  {
    slug: "writer",
    title: "Penulis Profesional",
    emoji: "📝",
    color: "from-stone-600 to-amber-800",
    category: "lifestyle",
    duration: "6-12 bulan",
    description: "Jalur jadi penulis dari blog pribadi sampe buku terbit. Buat lo yang suka nulis dan punya cerita.",
    why_matters: "Kata-kata punya kekuatan. Penulis bisa ngerubah cara pandang orang, nginspirasi, dan ninggalin warisan lewat tulisan yang abadi.",
    career_options: ["Penulis Buku", "Content Writer", "Copywriter", "Jurnalis", "Penulis Skenario", "Technical Writer"],
    success_examples: [],
    big_wins: [
      { title: "Rutin Menulis", description: "Konsisten nulis tiap hari", why_it_matters: "Skill nulis cuma dapet dari nulis", alternative_path: "Nulis diary", order: 1 },
      { title: "Blog/Platform", description: "Blog, Medium, atau platform", why_it_matters: "Publish karya pertama", alternative_path: "Ghostwriting", order: 2 },
      { title: "100 Artikel", description: "100 artikel terbit", why_it_matters: "Bukti konsistensi", alternative_path: "Kualitas > kuantitas", order: 3 },
      { title: "Umpan Balik", description: "Dapet feedback editor", why_it_matters: "Naikin level nulis", alternative_path: "Komunitas nulis", order: 4 },
      { title: "Buku/Penghasilan", description: "Terbit buku atau nulis bayaran", why_it_matters: "Transisi ke penulis pro", alternative_path: "Freelance writer", order: 5 },
    ],
    small_wins: [
      { big_win_title: "Rutin Menulis", title: "Nulis 100 Kata/Hari", description: "Konsisten 100 kata", order: 1 },
      { big_win_title: "Rutin Menulis", title: "Nulis 30 Hari", description: "Challenge 30 hari", order: 2 },
      { big_win_title: "Blog/Platform", title: "Buka Blog", description: "Blog atau Medium", order: 3 },
      { big_win_title: "Blog/Platform", title: "Artikel Pertama", description: "Publish artikel pertama", order: 4 },
      { big_win_title: "100 Artikel", title: "10 Artikel", description: "10 artikel terbit", order: 5 },
      { big_win_title: "100 Artikel", title: "100 Artikel", description: "100 artikel", order: 6 },
      { big_win_title: "Umpan Balik", title: "Cari Editor", description: "Kirim ke editor", order: 7 },
      { big_win_title: "Umpan Balik", title: "Revisi Naskah", description: "Revisi feedback", order: 8 },
      { big_win_title: "Buku/Penghasilan", title: "Naskah Buku", description: "Selesai naskah buku", order: 9 },
      { big_win_title: "Buku/Penghasilan", title: "Job Nulis", description: "Job nulis bayaran", order: 10 },
    ],
    daily_activities: {
      spiritual: ["Doa", "Syukur", "Renung"],
      physical: ["Jaga posture", "Jalan", "Stretching"],
      knowledge: ["Baca buku", "Teknik nulis", "Grammar"],
      social: ["Komunitas nulis", "Feedback", "Berbagi"],
      character: ["Rutin nulis", "Disiplin", "Tahan kritik"],
      dream_skill: ["Storytelling", "Penulisan kreatif", "Editing"],
    },
    alternative_futures: [
      { title: "Content Writer", description: "Nulis konten website/brand.", skills: ["SEO", "Research", "Adaptasi tone", "Deadline"] },
      { title: "Copywriter", description: "Nulis iklan dan marketing.", skills: ["Persuasive writing", "Brand voice", "Headline", "AIDA"] },
      { title: "Penulis Skenario", description: "Nulis film atau series.", skills: ["Story structure", "Dialogue", "Character", "Format"] },
    ],
    min_age: 14,
    max_age: 35,
  },
];
