export interface Quote {
  id: string;
  text: string;
  author: string;
  title: string;
  category: string;
}

export const QUOTE_CATEGORIES: { slug: string; label: string; emoji: string }[] = [
  { slug: "kepemimpinan", label: "Kepemimpinan", emoji: "👑" },
  { slug: "bisnis", label: "Bisnis & Kewirausahaan", emoji: "📈" },
  { slug: "inovasi", label: "Inovasi & Teknologi", emoji: "💡" },
  { slug: "kegagalan", label: "Kegagalan & Kebangkitan", emoji: "💪" },
  { slug: "kerja-keras", label: "Kerja Keras & Disiplin", emoji: "🔥" },
  { slug: "pendidikan", label: "Pendidikan & Pengetahuan", emoji: "📚" },
  { slug: "mimpi", label: "Mimpi & Visi", emoji: "✨" },
  { slug: "kehidupan", label: "Kehidupan & Kebijaksanaan", emoji: "🌿" },
  { slug: "keberanian", label: "Keberanian & Tekad", emoji: "🦁" },
  { slug: "olahraga", label: "Olahraga & Semangat Juara", emoji: "🏆" },
  { slug: "tanah-air", label: "Cinta Tanah Air & Kebangsaan", emoji: "🇮🇩" },
  { slug: "kreativitas", label: "Kreativitas & Seni", emoji: "🎨" },
  { slug: "perubahan", label: "Perubahan & Adaptasi", emoji: "🔄" },
  { slug: "integritas", label: "Kerendahan Hati & Integritas", emoji: "🤝" },
  { slug: "waktu", label: "Manajemen Waktu & Produktivitas", emoji: "⏰" },
  { slug: "persahabatan", label: "Persahabatan & Hubungan", emoji: "❤️" },
  { slug: "percaya-diri", label: "Kepercayaan Diri & Jati Diri", emoji: "🌟" },
  { slug: "lintas-bangsa", label: "Kebijaksanaan Lintas Bangsa", emoji: "🌏" },
  { slug: "harapan", label: "Semangat & Harapan", emoji: "🕊️" },
  { slug: "pelengkap", label: "Pelengkap", emoji: "📌" },
];

export const ALL_QUOTES: Quote[] = [
  // Bagian 1: Kepemimpinan
  { id: "Q001", text: "Pendidikan adalah senjata paling ampuh untuk mengubah dunia.", author: "Nelson Mandela", title: "Presiden Afrika Selatan & Tokoh Anti-Apartheid", category: "kepemimpinan" },
  { id: "Q002", text: "Jika tindakanmu menginspirasi orang lain untuk bermimpi lebih banyak, belajar lebih banyak, melakukan lebih banyak, dan menjadi lebih baik, maka kamu adalah seorang pemimpin.", author: "John Quincy Adams", title: "Presiden ke-6 Amerika Serikat", category: "kepemimpinan" },
  { id: "Q003", text: "Kepemimpinan adalah soal memengaruhi orang lain, tidak lebih, tidak kurang.", author: "John C. Maxwell", title: "Penulis & Pakar Kepemimpinan, Amerika Serikat", category: "kepemimpinan" },
  { id: "Q004", text: "Jangan sekali-kali meninggalkan sejarah.", author: "Ir. Soekarno", title: "Presiden Pertama Indonesia", category: "kepemimpinan" },
  { id: "Q005", text: "Bahkan dari ranjang kematian saya, jika saya merasa ada yang salah, saya akan bangkit.", author: "Lee Kuan Yew", title: "Perdana Menteri Pertama Singapura", category: "kepemimpinan" },
  { id: "Q006", text: "Cara terbaik untuk menemukan diri sendiri adalah dengan melebur diri dalam melayani orang lain.", author: "Mahatma Gandhi", title: "Tokoh Kemerdekaan India", category: "kepemimpinan" },
  { id: "Q007", text: "Hal yang membuat pemimpin hebat bukan kekuatannya, melainkan kemampuannya membuat orang lain merasa kuat.", author: "Sheryl Sandberg", title: "Mantan COO Meta (Facebook), Amerika Serikat", category: "kepemimpinan" },
  { id: "Q008", text: "Manajemen adalah melakukan sesuatu dengan benar; kepemimpinan adalah melakukan hal yang benar.", author: "Peter Drucker", title: "Pakar Manajemen, Austria-Amerika", category: "kepemimpinan" },
  { id: "Q009", text: "Saya tidak pernah kehilangan, saya hanya belajar bagaimana caranya menang.", author: "Nelson Mandela", title: "Presiden Afrika Selatan", category: "kepemimpinan" },
  { id: "Q010", text: "Negara ini bukan dibangun oleh orang-orang yang bermimpi besar, tetapi oleh orang-orang yang berani bekerja untuk mewujudkan mimpinya.", author: "Mohammad Hatta", title: "Wakil Presiden Pertama Indonesia", category: "kepemimpinan" },
  { id: "Q011", text: "Tugas seorang pemimpin bukan untuk mengisi orang dengan lebih banyak pengetahuan, tetapi membangkitkan rasa lapar mereka akan pengetahuan.", author: "John Naisbitt", title: "Penulis & Futuris, Amerika Serikat", category: "kepemimpinan" },
  { id: "Q012", text: "Kekuasaan yang sesungguhnya bukan diukur dari berapa banyak yang kamu kuasai, tetapi berapa banyak yang kamu layani.", author: "Joko Widodo", title: "Presiden ke-7 Indonesia", category: "kepemimpinan" },
  { id: "Q013", text: "Pemimpin terbaik adalah pemimpin yang paling sedikit terlihat memerintah, namun rakyatnya merasa semua itu pencapaian mereka sendiri.", author: "Lao Tzu", title: "Filsuf, Tiongkok", category: "kepemimpinan" },
  { id: "Q014", text: "Sebelum kamu menjadi pemimpin, sukses adalah tentang mengembangkan dirimu sendiri. Setelah kamu menjadi pemimpin, sukses adalah tentang mengembangkan orang lain.", author: "Jack Welch", title: "Mantan CEO General Electric, Amerika Serikat", category: "kepemimpinan" },
  { id: "Q015", text: "Saya tidak memimpin dengan tangan besi, saya memimpin dengan keyakinan bahwa setiap orang punya potensi yang sama untuk berubah.", author: "B.J. Habibie", title: "Presiden ke-3 Indonesia", category: "kepemimpinan" },
  { id: "Q016", text: "Optimisme adalah keyakinan yang membawa pada pencapaian. Tidak ada yang bisa diraih tanpa harapan dan keyakinan.", author: "Helen Keller", title: "Penulis & Aktivis, Amerika Serikat", category: "kepemimpinan" },
  { id: "Q017", text: "Kepemimpinan dan pembelajaran tidak terpisahkan satu sama lain.", author: "John F. Kennedy", title: "Presiden ke-35 Amerika Serikat", category: "kepemimpinan" },
  { id: "Q018", text: "Saya bukan pemimpin yang sempurna, tapi saya berusaha menjadi pemimpin yang jujur pada rakyatnya.", author: "Abdurrahman Wahid (Gus Dur)", title: "Presiden ke-4 Indonesia", category: "kepemimpinan" },
  { id: "Q019", text: "Tidak ada yang bisa membuatmu merasa rendah diri tanpa persetujuanmu sendiri.", author: "Eleanor Roosevelt", title: "Ibu Negara Amerika Serikat & Aktivis Hak Asasi Manusia", category: "kepemimpinan" },
  { id: "Q020", text: "Kekuatan sebuah bangsa terletak pada karakter rakyatnya, bukan pada kekayaan alamnya.", author: "Mahatma Gandhi", title: "Tokoh Kemerdekaan India", category: "kepemimpinan" },
  { id: "Q021", text: "Pemimpin sejati tidak mencari pengikut, mereka menciptakan lebih banyak pemimpin.", author: "Ratan Tata", title: "Mantan Ketua Tata Group, India", category: "kepemimpinan" },
  { id: "Q022", text: "Saya selalu percaya bahwa jika kamu bekerja keras cukup lama dan cukup baik, hal-hal baik akan terjadi.", author: "Barack Obama", title: "Presiden ke-44 Amerika Serikat", category: "kepemimpinan" },
  { id: "Q023", text: "Hidup adalah 10 persen apa yang terjadi pada kita dan 90 persen bagaimana kita merespons hal itu.", author: "Lou Holtz", title: "Pelatih Sepak Bola Amerika, Amerika Serikat", category: "kepemimpinan" },
  { id: "Q024", text: "Memimpin dari belakang dan membuat orang lain percaya bahwa merekalah yang memimpin di depan adalah seni yang langka.", author: "Nelson Mandela", title: "Presiden Afrika Selatan", category: "kepemimpinan" },
  { id: "Q025", text: "Jangan menilai keberhasilan saya, tetapi nilailah berapa kali saya terjatuh dan bangkit kembali.", author: "Nelson Mandela", title: "Presiden Afrika Selatan", category: "kepemimpinan" },
  { id: "Q026", text: "Tujuan dari kekuasaan adalah kemampuan untuk mewujudkan kebaikan yang lebih besar bagi sebanyak mungkin orang.", author: "Soekarno", title: "Presiden Pertama Indonesia", category: "kepemimpinan" },
  { id: "Q027", text: "Pemimpin yang baik membangun kepercayaan, pemimpin yang hebat membangun pemimpin baru.", author: "Indra Nooyi", title: "Mantan CEO PepsiCo, India-Amerika Serikat", category: "kepemimpinan" },
  { id: "Q028", text: "Kepemimpinan bukan tentang menjadi yang bertanggung jawab, melainkan tentang menjaga orang-orang yang menjadi tanggung jawabmu.", author: "Simon Sinek", title: "Penulis & Pembicara, Inggris-Amerika Serikat", category: "kepemimpinan" },
  { id: "Q029", text: "Saya tidak pernah berhenti belajar karena seorang pemimpin yang berhenti belajar berhenti memimpin.", author: "Rick Warren", title: "Penulis, Amerika Serikat", category: "kepemimpinan" },
  { id: "Q030", text: "Bangsa yang besar adalah bangsa yang menghormati jasa para pahlawannya dan mau belajar dari sejarah.", author: "Soekarno", title: "Presiden Pertama Indonesia", category: "kepemimpinan" },
  { id: "Q031", text: "Pemimpin yang menginspirasi bukan yang paling pintar, tetapi yang paling tulus.", author: "Sri Mulyani Indrawati", title: "Menteri Keuangan Republik Indonesia", category: "kepemimpinan" },
  { id: "Q032", text: "Saya percaya kekuatan terbesar sebuah organisasi adalah kepercayaan timnya terhadap satu sama lain.", author: "Satya Nadella", title: "CEO Microsoft, India-Amerika Serikat", category: "kepemimpinan" },
  { id: "Q033", text: "Demokrasi bukan tentang siapa yang menang, melainkan tentang bagaimana suara rakyat kecil tetap didengar.", author: "Megawati Soekarnoputri", title: "Presiden ke-5 Indonesia", category: "kepemimpinan" },
  { id: "Q034", text: "Jadilah pemimpin yang ketika orang lain melihatmu, mereka melihat harapan, bukan ketakutan.", author: "Desmond Tutu", title: "Uskup & Aktivis Hak Asasi Manusia, Afrika Selatan", category: "kepemimpinan" },
  { id: "Q035", text: "Saya tidak pernah memimpin dengan rasa takut. Saya memimpin dengan keyakinan bahwa kebenaran pada akhirnya akan menang.", author: "Aung San Suu Kyi", title: "Tokoh Demokrasi, Myanmar", category: "kepemimpinan" },

  // Bagian 2: Bisnis & Kewirausahaan
  { id: "Q036", text: "Cara terbaik untuk memulai sesuatu adalah berhenti membicarakannya dan mulai melakukannya.", author: "Walt Disney", title: "Pendiri The Walt Disney Company, Amerika Serikat", category: "bisnis" },
  { id: "Q037", text: "Satu-satunya cara untuk melakukan pekerjaan besar adalah dengan mencintai apa yang kamu kerjakan.", author: "Steve Jobs", title: "Pendiri Apple Inc., Amerika Serikat", category: "bisnis" },
  { id: "Q038", text: "Jika kamu tidak mendefinisikan dirimu sendiri, orang lain akan melakukannya untukmu.", author: "Oprah Winfrey", title: "Presenter & Pengusaha Media, Amerika Serikat", category: "bisnis" },
  { id: "Q039", text: "Bisnis yang baik adalah bisnis yang paling menarik, jenis kewirausahaan terbaik adalah yang membuat dunia menjadi tempat yang lebih baik.", author: "Richard Branson", title: "Pendiri Virgin Group, Inggris", category: "bisnis" },
  { id: "Q040", text: "Saya tidak pernah berpikir tentang kegagalan, saya hanya berpikir, 'Apa yang saya coba lakukan?'", author: "Thomas Edison", title: "Penemu, Amerika Serikat", category: "bisnis" },
  { id: "Q041", text: "Pelanggan tidak peduli seberapa keras kamu bekerja, mereka hanya peduli seberapa baik kamu melayani mereka.", author: "Jeff Bezos", title: "Pendiri Amazon, Amerika Serikat", category: "bisnis" },
  { id: "Q042", text: "Hidup itu seperti mengendarai sepeda, kamu tidak akan jatuh selama kamu terus mengayuh.", author: "Albert Einstein", title: "Fisikawan, Jerman-Amerika Serikat", category: "bisnis" },
  { id: "Q043", text: "Kesempatan tidak datang dua kali, tapi kesempatan baru selalu datang bagi mereka yang terus mencoba.", author: "Bob Sadino", title: "Pengusaha & Pendiri Kemfood-Kemchick, Indonesia", category: "bisnis" },
  { id: "Q044", text: "Saya tidak pernah bermimpi menjadi sukses, saya hanya bekerja keras dan sukses mengikuti.", author: "Estée Lauder", title: "Pendiri Estée Lauder Companies, Amerika Serikat", category: "bisnis" },
  { id: "Q045", text: "Bisnis adalah tentang orang, keuangan hanyalah alat untuk mengukur seberapa baik kamu memperlakukan orang.", author: "Richard Branson", title: "Pendiri Virgin Group, Inggris", category: "bisnis" },
  { id: "Q046", text: "Harga adalah apa yang kamu bayar, nilai adalah apa yang kamu dapatkan.", author: "Warren Buffett", title: "CEO Berkshire Hathaway, Amerika Serikat", category: "bisnis" },
  { id: "Q047", text: "Saya tidak mengukur kesuksesan dari uang yang dihasilkan, tetapi dari dampak yang ditinggalkan.", author: "Chairul Tanjung", title: "Pendiri CT Corp, Indonesia", category: "bisnis" },
  { id: "Q048", text: "Jangan menabung sisa dari yang kamu belanjakan, tetapi belanjakan sisa dari yang kamu tabung.", author: "Warren Buffett", title: "CEO Berkshire Hathaway, Amerika Serikat", category: "bisnis" },
  { id: "Q049", text: "Inovasi membedakan seorang pemimpin dari seorang pengikut.", author: "Steve Jobs", title: "Pendiri Apple Inc., Amerika Serikat", category: "bisnis" },
  { id: "Q050", text: "Risiko terbesar adalah tidak mengambil risiko sama sekali. Di dunia yang berubah sangat cepat, satu-satunya strategi yang dijamin gagal adalah tidak mengambil risiko.", author: "Mark Zuckerberg", title: "Pendiri Meta (Facebook), Amerika Serikat", category: "bisnis" },
  { id: "Q051", text: "Saya membangun usaha dari nol, modal saya hanya kepercayaan dan kerja keras tanpa henti.", author: "William Tanuwijaya", title: "Pendiri Tokopedia, Indonesia", category: "bisnis" },
  { id: "Q052", text: "Kesuksesan bukanlah kunci kebahagiaan. Kebahagiaan adalah kunci kesuksesan. Jika kamu menyukai apa yang kamu kerjakan, kamu akan sukses.", author: "Albert Schweitzer", title: "Filsuf & Dokter, Jerman-Prancis", category: "bisnis" },
  { id: "Q053", text: "Cara terbaik untuk memprediksi masa depan adalah dengan menciptakannya.", author: "Peter Drucker", title: "Pakar Manajemen, Austria-Amerika Serikat", category: "bisnis" },
  { id: "Q054", text: "Pekerjaan akan mengisi sebagian besar hidupmu, dan satu-satunya cara untuk benar-benar puas adalah melakukan apa yang menurutmu hebat.", author: "Steve Jobs", title: "Pendiri Apple Inc., Amerika Serikat", category: "bisnis" },
  { id: "Q055", text: "Jangan mulai bisnis kecuali kamu obsesif terhadapnya. Jika kamu tidak siap mengabdikan hidupmu untuk usahamu, jangan mulai dari sekarang.", author: "Mark Cuban", title: "Pengusaha & Investor, Amerika Serikat", category: "bisnis" },
  { id: "Q056", text: "Saya percaya kunci kewirausahaan adalah keberanian untuk gagal lebih cepat dari orang lain.", author: "Nadiem Makarim", title: "Pendiri Gojek & Menteri Pendidikan Indonesia", category: "bisnis" },
  { id: "Q057", text: "Visi tanpa eksekusi hanyalah halusinasi.", author: "Henry Ford", title: "Pendiri Ford Motor Company, Amerika Serikat", category: "bisnis" },
  { id: "Q058", text: "Jangan terlalu fokus pada kompetitor, fokuslah pada pelanggan.", author: "Jack Ma", title: "Pendiri Alibaba Group, Tiongkok", category: "bisnis" },
  { id: "Q059", text: "Hari ini sulit, besok akan lebih sulit, tetapi lusa akan indah. Namun kebanyakan orang menyerah besok malam.", author: "Jack Ma", title: "Pendiri Alibaba Group, Tiongkok", category: "bisnis" },
  { id: "Q060", text: "Saya tidak takut gagal, saya hanya takut tidak mencoba.", author: "Dahlan Iskan", title: "Mantan Menteri BUMN & Pengusaha Media, Indonesia", category: "bisnis" },
  { id: "Q061", text: "Uang adalah alat, bukan tujuan. Tujuan sebenarnya adalah memberi manfaat sebanyak-banyaknya bagi orang lain.", author: "Aliko Dangote", title: "Pengusaha & Konglomerat, Nigeria", category: "bisnis" },
  { id: "Q062", text: "Jika kamu menginginkan sesuatu yang belum pernah kamu miliki, kamu harus melakukan sesuatu yang belum pernah kamu lakukan.", author: "Thomas Jefferson", title: "Presiden ke-3 Amerika Serikat", category: "bisnis" },
  { id: "Q063", text: "Saya membangun perusahaan bukan untuk menjadi kaya, tapi untuk membangun sesuatu yang bertahan lebih lama dari saya.", author: "Akio Morita", title: "Pendiri Sony Corporation, Jepang", category: "bisnis" },
  { id: "Q064", text: "Kunci sukses berbisnis adalah konsistensi kecil yang dilakukan setiap hari, bukan langkah besar yang dilakukan sesekali.", author: "Sam Walton", title: "Pendiri Walmart, Amerika Serikat", category: "bisnis" },
  { id: "Q065", text: "Pelanggan hanya membutuhkan satu pengalaman buruk untuk pergi selamanya, jadi jangan pernah meremehkan layanan.", author: "Howard Schultz", title: "Mantan CEO Starbucks, Amerika Serikat", category: "bisnis" },
  { id: "Q066", text: "Bisnis yang hebat dibangun dari masalah yang diselesaikan dengan tulus, bukan sekadar mengejar keuntungan.", author: "Mukesh Ambani", title: "Ketua Reliance Industries, India", category: "bisnis" },
  { id: "Q067", text: "Saya tidak pernah melihat kompetisi sebagai musuh, melainkan sebagai pengingat untuk terus memperbaiki diri.", author: "Carlos Slim", title: "Pengusaha & Konglomerat, Meksiko", category: "bisnis" },
  { id: "Q068", text: "Modal terbesar seorang pengusaha bukan uang, melainkan reputasi dan kepercayaan yang dijaga bertahun-tahun.", author: "Tan Sri Tony Fernandes", title: "Pendiri AirAsia, Malaysia", category: "bisnis" },
  { id: "Q069", text: "Bisnis itu sederhana: layani pelanggan lebih baik dari pesaingmu dan kamu akan sukses.", author: "Jack Welch", title: "Mantan CEO General Electric, Amerika Serikat", category: "bisnis" },
  { id: "Q070", text: "Saya membangun usaha ini dengan keyakinan bahwa kecantikan sejati datang dari rasa percaya diri, bukan dari kesempurnaan.", author: "Estée Lauder", title: "Pendiri Estée Lauder Companies, Amerika Serikat", category: "bisnis" },
  { id: "Q071", text: "Diversifikasi adalah perlindungan terhadap ketidaktahuan. Itu tidak terlalu masuk akal jika kamu tahu apa yang kamu lakukan.", author: "Warren Buffett", title: "CEO Berkshire Hathaway, Amerika Serikat", category: "bisnis" },
  { id: "Q072", text: "Jangan menunggu kesempatan langka dalam hidup. Ambil kesempatan biasa dan jadikan itu luar biasa.", author: "Napoleon Hill", title: "Penulis, Amerika Serikat", category: "bisnis" },
  { id: "Q073", text: "Pasar selalu berubah, tetapi prinsip melayani pelanggan dengan tulus tidak pernah berubah.", author: "Lo Kheng Hong", title: "Investor Saham, Indonesia", category: "bisnis" },
  { id: "Q074", text: "Saya belajar bahwa keberanian bukan tidak adanya rasa takut, tetapi tekad untuk tetap melangkah meski takut.", author: "Sandiaga Uno", title: "Pengusaha & Wakil Menteri Pariwisata Indonesia", category: "bisnis" },
  { id: "Q075", text: "Bisnis terbaik adalah bisnis yang memecahkan masalah nyata bagi banyak orang, bukan yang sekadar terlihat keren.", author: "Larry Page", title: "Salah Satu Pendiri Google, Amerika Serikat", category: "bisnis" },
  { id: "Q076", text: "Saya tidak pernah membandingkan diri dengan kompetitor, saya membandingkan diri dengan versi terbaik diri saya kemarin.", author: "Sundar Pichai", title: "CEO Alphabet & Google, India-Amerika Serikat", category: "bisnis" },
  { id: "Q077", text: "Setiap rupiah yang kamu hasilkan harus mencerminkan nilai yang kamu berikan, bukan sekadar harga yang kamu pasang.", author: "Chairul Tanjung", title: "Pendiri CT Corp, Indonesia", category: "bisnis" },
  { id: "Q078", text: "Wirausahawan bersedia bekerja 80 jam seminggu untuk menghindari bekerja 40 jam seminggu untuk orang lain.", author: "Lori Greiner", title: "Pengusaha & Investor, Amerika Serikat", category: "bisnis" },
  { id: "Q079", text: "Saya tidak membangun bisnis untuk hari ini, saya membangunnya untuk anak cucu saya kelak.", author: "Eka Tjipta Widjaja", title: "Pendiri Sinar Mas Group, Indonesia", category: "bisnis" },
  { id: "Q080", text: "Pekerjaan terbaik bukan yang paling dibayar tinggi, melainkan yang membuatmu bangun pagi dengan semangat.", author: "Indra Nooyi", title: "Mantan CEO PepsiCo, India-Amerika Serikat", category: "bisnis" },
  { id: "Q081", text: "Saya percaya, bisnis yang baik pada akhirnya adalah bisnis yang baik untuk masyarakat sekitarnya.", author: "Anita Roddick", title: "Pendiri The Body Shop, Inggris", category: "bisnis" },

  // Bagian 3: Inovasi & Teknologi
  { id: "Q082", text: "Inovasi adalah membedakan antara seorang pemimpin dan seorang pengikut.", author: "Steve Jobs", title: "Pendiri Apple Inc., Amerika Serikat", category: "inovasi" },
  { id: "Q083", text: "Saya tidak gagal seribu kali, saya berhasil menemukan seribu cara yang tidak berfungsi.", author: "Thomas Edison", title: "Penemu Lampu Pijar, Amerika Serikat", category: "inovasi" },
  { id: "Q084", text: "Teknologi tidak ada artinya jika tidak membuat hidup manusia lebih baik.", author: "Tim Cook", title: "CEO Apple Inc., Amerika Serikat", category: "inovasi" },
  { id: "Q085", text: "Masa depan adalah milik mereka yang mempersiapkan diri hari ini.", author: "Malcolm X", title: "Aktivis Hak Sipil, Amerika Serikat", category: "inovasi" },
  { id: "Q086", text: "Kita selalu melebih-lebihkan perubahan yang akan terjadi dalam satu tahun dan meremehkan perubahan yang terjadi dalam sepuluh tahun.", author: "Bill Gates", title: "Pendiri Microsoft, Amerika Serikat", category: "inovasi" },
  { id: "Q087", text: "Internet akan menjadi kekuatan paling besar dalam mendemokratisasi akses informasi sepanjang sejarah manusia.", author: "Larry Page", title: "Salah Satu Pendiri Google, Amerika Serikat", category: "inovasi" },
  { id: "Q088", text: "Saya ingin mati di Mars, hanya bukan saat mendarat.", author: "Elon Musk", title: "CEO Tesla & SpaceX, Amerika Serikat", category: "inovasi" },
  { id: "Q089", text: "Imajinasi lebih penting daripada pengetahuan, karena pengetahuan terbatas sedangkan imajinasi melingkupi seluruh dunia.", author: "Albert Einstein", title: "Fisikawan, Jerman-Amerika Serikat", category: "inovasi" },
  { id: "Q090", text: "Setiap masalah adalah kesempatan tersembunyi untuk berinovasi.", author: "Sundar Pichai", title: "CEO Alphabet & Google, India-Amerika Serikat", category: "inovasi" },
  { id: "Q091", text: "Teknologi terbaik adalah teknologi yang tidak terasa seperti teknologi, ia hanya menyelesaikan masalah dengan mulus.", author: "Jony Ive", title: "Mantan Chief Design Officer Apple, Inggris", category: "inovasi" },
  { id: "Q092", text: "Kecerdasan buatan adalah hal paling penting yang sedang dikerjakan manusia, lebih penting daripada listrik atau api.", author: "Sundar Pichai", title: "CEO Alphabet & Google, India-Amerika Serikat", category: "inovasi" },
  { id: "Q093", text: "Saya tidak menciptakan sesuatu yang baru, saya hanya menggabungkan hal-hal lama dengan cara baru.", author: "Steve Jobs", title: "Pendiri Apple Inc., Amerika Serikat", category: "inovasi" },
  { id: "Q094", text: "Robot tidak akan mengambil pekerjaan kita, mereka akan mengambil tugas-tugas yang membosankan dari pekerjaan kita.", author: "Jack Ma", title: "Pendiri Alibaba Group, Tiongkok", category: "inovasi" },
  { id: "Q095", text: "Inovasi datang dari mengatakan tidak pada seribu hal untuk memastikan kita tidak salah arah.", author: "Steve Jobs", title: "Pendiri Apple Inc., Amerika Serikat", category: "inovasi" },
  { id: "Q096", text: "Saya percaya, setiap anak Indonesia berhak mendapat akses teknologi yang sama dengan anak-anak di negara maju.", author: "Nadiem Makarim", title: "Pendiri Gojek & Menteri Pendidikan Indonesia", category: "inovasi" },
  { id: "Q097", text: "Komputer tidak ada gunanya, mereka hanya bisa memberi jawaban.", author: "Pablo Picasso", title: "Pelukis, Spanyol", category: "inovasi" },
  { id: "Q098", text: "Jika kamu menilai ikan dari kemampuannya memanjat pohon, ia akan selamanya merasa bodoh.", author: "Albert Einstein", title: "Fisikawan, Jerman-Amerika Serikat", category: "inovasi" },
  { id: "Q099", text: "Teknologi adalah alat. Yang lebih penting adalah memastikan murid-murid saling memotivasi dan saling peduli.", author: "Bill Gates", title: "Pendiri Microsoft, Amerika Serikat", category: "inovasi" },
  { id: "Q100", text: "Visi tanpa pelaksanaan adalah ilusi, dan pelaksanaan tanpa visi hanyalah aktivitas yang sia-sia.", author: "Tony Robbins", title: "Penulis & Motivator, Amerika Serikat", category: "inovasi" },
  { id: "Q101", text: "Saya merancang produk yang ingin saya gunakan sendiri, bukan yang menurut riset pasar diinginkan orang.", author: "Steve Jobs", title: "Pendiri Apple Inc., Amerika Serikat", category: "inovasi" },
  { id: "Q102", text: "Data adalah minyak baru, tetapi seperti minyak, ia tidak berguna kecuali sudah diolah.", author: "Clive Humby", title: "Ahli Matematika & Data, Inggris", category: "inovasi" },
  { id: "Q103", text: "Ponsel pintar bukan sekadar alat komunikasi, ia adalah perpanjangan dari diri kita sendiri di era digital.", author: "Akio Morita", title: "Pendiri Sony Corporation, Jepang", category: "inovasi" },
  { id: "Q104", text: "Disrupsi bukan ancaman, melainkan kesempatan bagi yang berani beradaptasi lebih cepat.", author: "William Tanuwijaya", title: "Pendiri Tokopedia, Indonesia", category: "inovasi" },
  { id: "Q105", text: "Saya tidak menunggu masa depan datang, saya membangunnya sekarang, bata demi bata, baris kode demi baris kode.", author: "Mark Zuckerberg", title: "Pendiri Meta (Facebook), Amerika Serikat", category: "inovasi" },

  // Bagian 4: Kegagalan & Kebangkitan
  { id: "Q106", text: "Kesuksesan adalah guru yang buruk. Ia menggoda orang pintar untuk berpikir mereka tidak bisa kalah.", author: "Bill Gates", title: "Pendiri Microsoft, Amerika Serikat", category: "kegagalan" },
  { id: "Q107", text: "Saya telah gagal lebih dari yang berhasil saya lakukan, tetapi saya tidak pernah berhenti mencoba.", author: "Michael Jordan", title: "Legenda Basket NBA, Amerika Serikat", category: "kegagalan" },
  { id: "Q108", text: "Kegagalan adalah kesempatan untuk mulai lagi dengan lebih cerdas.", author: "Henry Ford", title: "Pendiri Ford Motor Company, Amerika Serikat", category: "kegagalan" },
  { id: "Q109", text: "Berdirilah delapan kali, jika kamu jatuh tujuh kali.", author: "Pepatah Jepang", title: "Kebijaksanaan Populer, Jepang", category: "kegagalan" },
  { id: "Q110", text: "Kegagalan terbesar dalam hidup bukan saat kita jatuh, melainkan saat kita memilih untuk tidak bangkit kembali.", author: "Nelson Mandela", title: "Presiden Afrika Selatan", category: "kegagalan" },
  { id: "Q111", text: "Saya dipecat dari perusahaan yang saya dirikan sendiri, tetapi itu adalah hal terbaik yang pernah terjadi pada saya.", author: "Steve Jobs", title: "Pendiri Apple Inc., Amerika Serikat", category: "kegagalan" },
  { id: "Q112", text: "Saya tidak pernah kalah. Saya menang, atau saya belajar.", author: "Nelson Mandela", title: "Presiden Afrika Selatan", category: "kegagalan" },
  { id: "Q113", text: "Banyak kegagalan dalam hidup terjadi karena orang tidak menyadari betapa dekat mereka dengan kesuksesan saat mereka menyerah.", author: "Thomas Edison", title: "Penemu, Amerika Serikat", category: "kegagalan" },
  { id: "Q114", text: "Jatuh adalah bagian dari hidup, bangkit kembali adalah yang membuat kita hidup.", author: "Bob Sadino", title: "Pengusaha & Pendiri Kemfood-Kemchick, Indonesia", category: "kegagalan" },
  { id: "Q115", text: "Hidup ini seperti naik sepeda roda satu, kamu harus terus bergerak agar tidak jatuh, dan kamu harus berani jatuh dulu sebelum bisa seimbang.", author: "Claude Bristol", title: "Penulis Motivasi, Amerika Serikat", category: "kegagalan" },
  { id: "Q116", text: "Saya pernah bangkrut total, tidur di lantai kantor saya sendiri, sebelum akhirnya membangun kembali dari nol.", author: "Howard Schultz", title: "Mantan CEO Starbucks, Amerika Serikat", category: "kegagalan" },
  { id: "Q117", text: "Kekalahan bukanlah akhir, kecuali kamu memutuskan untuk berhenti.", author: "Richard Nixon", title: "Presiden ke-37 Amerika Serikat", category: "kegagalan" },
  { id: "Q118", text: "Saya tidak peduli berapa kali saya jatuh, saya hanya peduli berapa kali saya berdiri lagi.", author: "Muhammad Ali", title: "Petinju Legendaris, Amerika Serikat", category: "kegagalan" },
  { id: "Q119", text: "Setiap kali pintu tertutup di depan saya, saya menganggapnya sebagai tanda bahwa pintu yang lebih baik sedang menunggu untuk dibuka.", author: "Oprah Winfrey", title: "Presenter & Pengusaha Media, Amerika Serikat", category: "kegagalan" },
  { id: "Q120", text: "Saya telah merasakan kebangkrutan, penolakan, dan kegagalan, tetapi semua itu membuat saya menjadi penulis yang lebih kuat.", author: "J.K. Rowling", title: "Penulis Harry Potter, Inggris", category: "kegagalan" },
  { id: "Q121", text: "Kesulitan terbesar dalam hidup saya justru menjadi guru terbaik yang pernah saya miliki.", author: "Walt Disney", title: "Pendiri The Walt Disney Company, Amerika Serikat", category: "kegagalan" },
  { id: "Q122", text: "Jangan takut gagal, takutlah jika kamu tidak pernah mencoba.", author: "Chairul Tanjung", title: "Pendiri CT Corp, Indonesia", category: "kegagalan" },
  { id: "Q123", text: "Saya kehilangan segalanya dalam krisis moneter 1998, tetapi krisis itu mengajarkan saya cara membangun bisnis yang benar-benar tahan banting.", author: "Sandiaga Uno", title: "Pengusaha & Wakil Menteri Pariwisata Indonesia", category: "kegagalan" },
  { id: "Q124", text: "Keberhasilan adalah hasil dari kegagalan yang ditangani dengan benar dan tidak pernah diulangi dua kali.", author: "Soichiro Honda", title: "Pendiri Honda Motor Company, Jepang", category: "kegagalan" },
  { id: "Q125", text: "Kegagalan hanyalah kesempatan untuk memulai lagi, kali ini dengan cara yang lebih cerdas.", author: "Henry Ford", title: "Pendiri Ford Motor Company, Amerika Serikat", category: "kegagalan" },

  // Bagian 5: Kerja Keras & Disiplin
  { id: "Q126", text: "Tidak ada jalan pintas menuju tempat yang layak untuk dituju.", author: "Beverly Sills", title: "Penyanyi Opera, Amerika Serikat", category: "kerja-keras" },
  { id: "Q127", text: "Bekerja keras dalam diam, biarkan kesuksesanmu yang berbicara dengan suara nyaring.", author: "Frank Ocean", title: "Musisi, Amerika Serikat", category: "kerja-keras" },
  { id: "Q128", text: "Disiplin adalah jembatan antara tujuan dan pencapaian.", author: "Jim Rohn", title: "Penulis & Motivator, Amerika Serikat", category: "kerja-keras" },
  { id: "Q129", text: "Kerja keras mengalahkan talenta ketika talenta tidak bekerja keras.", author: "Tim Notke", title: "Pelatih Basket, Amerika Serikat", category: "kerja-keras" },
  { id: "Q130", text: "Saya percaya bahwa keberuntungan adalah hasil dari kerja keras yang bertemu dengan kesempatan yang tepat.", author: "Oprah Winfrey", title: "Presenter & Pengusaha Media, Amerika Serikat", category: "kerja-keras" },
  { id: "Q131", text: "Saya tidur empat jam sehari selama bertahun-tahun untuk membangun bisnis ini dari nol.", author: "Jack Ma", title: "Pendiri Alibaba Group, Tiongkok", category: "kerja-keras" },
  { id: "Q132", text: "Kebiasaan kecil yang dilakukan konsisten setiap hari akan mengalahkan motivasi besar yang hanya sesekali muncul.", author: "James Clear", title: "Penulis Atomic Habits, Amerika Serikat", category: "kerja-keras" },
  { id: "Q133", text: "Genius adalah satu persen inspirasi dan sembilan puluh sembilan persen kerja keras.", author: "Thomas Edison", title: "Penemu, Amerika Serikat", category: "kerja-keras" },
  { id: "Q134", text: "Saya tidak punya bakat khusus, saya hanya sangat penasaran dan bekerja sangat keras.", author: "Albert Einstein", title: "Fisikawan, Jerman-Amerika Serikat", category: "kerja-keras" },
  { id: "Q135", text: "Jangan menunggu, waktu yang tepat tidak akan pernah benar-benar datang.", author: "Napoleon Hill", title: "Penulis, Amerika Serikat", category: "kerja-keras" },
  { id: "Q136", text: "Disiplin lebih penting daripada motivasi, karena motivasi datang dan pergi, sementara disiplin tetap ada.", author: "Cristiano Ronaldo", title: "Pesepak Bola, Portugal", category: "kerja-keras" },
  { id: "Q137", text: "Saya berlatih ribuan kali tembakan yang sama agar terlihat mudah saat pertandingan.", author: "Kobe Bryant", title: "Legenda Basket NBA, Amerika Serikat", category: "kerja-keras" },
  { id: "Q138", text: "Bekerja keras untuk sesuatu yang tidak kita pedulikan disebut stres, bekerja keras untuk sesuatu yang kita cintai disebut passion.", author: "Simon Sinek", title: "Penulis & Pembicara, Inggris-Amerika Serikat", category: "kerja-keras" },
  { id: "Q139", text: "Tidak ada pengganti untuk kerja keras yang dilakukan dengan konsisten setiap hari.", author: "Indra Nooyi", title: "Mantan CEO PepsiCo, India-Amerika Serikat", category: "kerja-keras" },
  { id: "Q140", text: "Saya selalu bangun pukul empat pagi karena saya tahu kompetitor saya masih tertidur.", author: "Dwayne Johnson", title: "Aktor & Pengusaha, Amerika Serikat", category: "kerja-keras" },
  { id: "Q141", text: "Keberhasilan yang instan hanya terlihat instan bagi yang tidak melihat kerja keras di baliknya.", author: "Bob Sadino", title: "Pengusaha & Pendiri Kemfood-Kemchick, Indonesia", category: "kerja-keras" },
  { id: "Q142", text: "Tidak ada elevator menuju kesuksesan, kamu harus menggunakan tangga, satu per satu.", author: "Zig Ziglar", title: "Penulis & Motivator, Amerika Serikat", category: "kerja-keras" },
  { id: "Q143", text: "Saya bekerja bukan karena saya harus, tetapi karena saya memilih untuk menjadi yang terbaik di bidang saya.", author: "Serena Williams", title: "Petenis, Amerika Serikat", category: "kerja-keras" },
  { id: "Q144", text: "Konsistensi adalah apa yang mengubah rata-rata menjadi luar biasa.", author: "Lionel Messi", title: "Pesepak Bola, Argentina", category: "kerja-keras" },
  { id: "Q145", text: "Setiap pagi di Afrika, seekor rusa bangun dan tahu ia harus berlari lebih cepat dari singa, atau ia akan mati.", author: "Pepatah Afrika", title: "Kebijaksanaan Populer, Afrika", category: "kerja-keras" },

  // Bagian 6: Pendidikan & Pengetahuan
  { id: "Q146", text: "Pendidikan adalah paspor menuju masa depan, karena hari esok adalah milik mereka yang mempersiapkannya hari ini.", author: "Malcolm X", title: "Aktivis Hak Sipil, Amerika Serikat", category: "pendidikan" },
  { id: "Q147", text: "Investasi pada ilmu pengetahuan selalu membayar bunga yang terbaik.", author: "Benjamin Franklin", title: "Salah Satu Pendiri Amerika Serikat", category: "pendidikan" },
  { id: "Q148", text: "Berikan saya 10 pemuda, maka akan saya guncangkan dunia.", author: "Ir. Soekarno", title: "Presiden Pertama & Founding Father Indonesia", category: "pendidikan" },
  { id: "Q149", text: "Bangsa yang kalah perang masih bisa bangkit, tetapi bangsa yang kehilangan generasi terdidik akan kehilangan masa depannya.", author: "Mohammad Hatta", title: "Wakil Presiden Pertama Indonesia", category: "pendidikan" },
  { id: "Q150", text: "Pendidikan bukan persiapan untuk hidup, pendidikan adalah hidup itu sendiri.", author: "John Dewey", title: "Filsuf & Pendidik, Amerika Serikat", category: "pendidikan" },
  { id: "Q151", text: "Atlet yang berhenti sekolah demi olahraga sering kali menutup separuh masa depannya sendiri tanpa sadar.", author: "Susy Susanti", title: "Legenda Bulu Tangkis, Indonesia", category: "pendidikan" },
  { id: "Q152", text: "Belajarlah seolah kamu akan hidup selamanya, hiduplah seolah kamu akan mati besok.", author: "Mahatma Gandhi", title: "Tokoh Kemerdekaan India", category: "pendidikan" },
  { id: "Q153", text: "Satu buku, satu pena, satu anak, dan satu guru dapat mengubah dunia.", author: "Malala Yousafzai", title: "Aktivis Pendidikan, Pakistan", category: "pendidikan" },
  { id: "Q154", text: "Tujuan pendidikan bukan untuk mengisi pikiran dengan fakta, melainkan untuk membuka pikiran agar berpikir secara mandiri.", author: "Ki Hajar Dewantara", title: "Bapak Pendidikan Indonesia", category: "pendidikan" },
  { id: "Q155", text: "Ilmu pengetahuan tanpa agama lumpuh, agama tanpa ilmu pengetahuan buta.", author: "Albert Einstein", title: "Fisikawan, Jerman-Amerika Serikat", category: "pendidikan" },
  { id: "Q156", text: "Saya tidak pernah berpikir saya cukup pintar, saya hanya membaca lebih banyak dan bertanya lebih sering.", author: "Elon Musk", title: "CEO Tesla & SpaceX, Amerika Serikat", category: "pendidikan" },
  { id: "Q157", text: "Pikiran yang terbuka karena pengalaman baru tidak akan pernah bisa kembali ke ukurannya semula.", author: "Oliver Wendell Holmes", title: "Hakim Agung, Amerika Serikat", category: "pendidikan" },
  { id: "Q158", text: "Pendidikan adalah senjata yang paling kuat yang bisa kamu gunakan untuk mengubah dunia.", author: "Nelson Mandela", title: "Presiden Afrika Selatan", category: "pendidikan" },
  { id: "Q159", text: "Kami tidak boleh membiarkan anak-anak Indonesia hanya menjadi penonton di tengah kemajuan zaman, mereka harus jadi pemain utama.", author: "B.J. Habibie", title: "Presiden ke-3 Indonesia", category: "pendidikan" },
  { id: "Q160", text: "Belajar adalah satu-satunya hal yang tidak melemahkan pikiran, melainkan terus mengisinya dengan energi baru.", author: "Leonardo da Vinci", title: "Seniman & Ilmuwan, Italia", category: "pendidikan" },
  { id: "Q161", text: "Saya selalu mengatakan, sekolahlah setinggi mungkin, lalu pakai ilmumu untuk menyelesaikan masalah nyata di sekitarmu.", author: "Sri Mulyani Indrawati", title: "Menteri Keuangan Republik Indonesia", category: "pendidikan" },
  { id: "Q162", text: "Anak perempuan punya hak yang sama untuk bermimpi dan belajar setinggi langit seperti anak laki-laki.", author: "R.A. Kartini", title: "Pelopor Emansipasi Perempuan Indonesia", category: "pendidikan" },
  { id: "Q163", text: "Membaca adalah jendela menuju dunia yang lebih luas daripada yang bisa kita bayangkan sendiri.", author: "Buya Hamka", title: "Ulama & Sastrawan, Indonesia", category: "pendidikan" },
  { id: "Q164", text: "Saya tidak pernah berhenti menjadi murid, sekalipun saya sudah menjadi presiden direktur.", author: "Dahlan Iskan", title: "Mantan Menteri BUMN & Pengusaha Media, Indonesia", category: "pendidikan" },
  { id: "Q165", text: "Pengetahuan adalah satu-satunya harta yang bertambah ketika dibagikan, bukan berkurang.", author: "A.P.J. Abdul Kalam", title: "Presiden ke-11 India", category: "pendidikan" },
  { id: "Q166", text: "Pendidikan dan olahraga seharusnya berjalan beriringan, bukan saling mengalahkan satu sama lain.", author: "Taufik Hidayat", title: "Legenda Bulu Tangkis, Indonesia", category: "pendidikan" },
  { id: "Q167", text: "Tidak ada investasi yang lebih menguntungkan daripada investasi pada diri sendiri melalui ilmu pengetahuan.", author: "Warren Buffett", title: "CEO Berkshire Hathaway, Amerika Serikat", category: "pendidikan" },
  { id: "Q168", text: "Saya ingin generasi muda Indonesia paham bahwa gelar sarjana dan medali olahraga bisa diraih dalam waktu yang sama.", author: "Susy Susanti", title: "Legenda Bulu Tangkis, Indonesia", category: "pendidikan" },
  { id: "Q169", text: "Ilmu adalah cahaya, dan kebodohan adalah kegelapan, maka carilah cahaya itu kemanapun ia berada.", author: "Buya Hamka", title: "Ulama & Sastrawan, Indonesia", category: "pendidikan" },
  { id: "Q170", text: "Belajar tanpa berpikir adalah sia-sia, berpikir tanpa belajar adalah berbahaya.", author: "Konfusius", title: "Filsuf, Tiongkok", category: "pendidikan" },

  // Bagian 7: Mimpi & Visi
  { id: "Q171", text: "Masa depan adalah milik mereka yang percaya pada keindahan mimpinya sendiri.", author: "Eleanor Roosevelt", title: "Ibu Negara & Aktivis Hak Asasi Manusia, Amerika Serikat", category: "mimpi" },
  { id: "Q172", text: "Semua mimpi kita bisa menjadi nyata jika kita memiliki keberanian untuk mengejarnya.", author: "Walt Disney", title: "Pendiri The Walt Disney Company, Amerika Serikat", category: "mimpi" },
  { id: "Q173", text: "Jangan biarkan mimpimu hanya menjadi mimpi, bangun setiap pagi dan kerjakan sesuatu untuk mewujudkannya.", author: "Paulo Coelho", title: "Penulis Sang Alkemis, Brasil", category: "mimpi" },
  { id: "Q174", text: "Indonesia tidak boleh hanya jadi pasar bagi industri olahraga dunia, kita harus jadi pusat produksinya.", author: "Erick Thohir", title: "Menteri BUMN & Pengusaha, Indonesia", category: "mimpi" },
  { id: "Q175", text: "Mimpi tidak pernah menjadi kenyataan melalui sihir, ia membutuhkan keringat, tekad, dan kerja keras.", author: "Colin Powell", title: "Mantan Menteri Luar Negeri Amerika Serikat", category: "mimpi" },
  { id: "Q176", text: "Visi tanpa tindakan hanyalah lamunan, tindakan tanpa visi hanyalah membuang waktu.", author: "Joel A. Barker", title: "Futuris, Amerika Serikat", category: "mimpi" },
  { id: "Q177", text: "Saya bermimpi suatu hari nanti bangsa ini bangkit dan menjalani makna sebenarnya dari prinsip bahwa semua manusia diciptakan setara.", author: "Martin Luther King Jr.", title: "Tokoh Hak Sipil, Amerika Serikat", category: "mimpi" },
  { id: "Q178", text: "Jangan terlalu kecil bermimpi, karena mimpi besar membutuhkan usaha yang sama dengan mimpi kecil.", author: "Donald Trump", title: "Pengusaha & Presiden ke-45 Amerika Serikat", category: "mimpi" },
  { id: "Q179", text: "Saya selalu membayangkan masa depan yang saya inginkan, lalu bekerja mundur ke hari ini untuk mewujudkannya.", author: "Elon Musk", title: "CEO Tesla & SpaceX, Amerika Serikat", category: "mimpi" },
  { id: "Q180", text: "Setiap bangunan besar pernah hanya berupa gambar di atas kertas dan keyakinan di kepala penggagasnya.", author: "I.M. Pei", title: "Arsitek, Amerika Serikat (kelahiran Tiongkok)", category: "mimpi" },
  { id: "Q181", text: "Daerah mana pun bisa melahirkan ekosistem olahraga kelas dunia jika diberi infrastruktur dan kepercayaan yang tepat.", author: "Ridwan Kamil", title: "Mantan Gubernur Jawa Barat, Indonesia", category: "mimpi" },
  { id: "Q182", text: "Cara terbaik untuk mewujudkan masa depan adalah dengan menciptakannya sendiri, bukan menunggunya datang.", author: "Abraham Lincoln", title: "Presiden ke-16 Amerika Serikat", category: "mimpi" },
  { id: "Q183", text: "Saya tidak hanya bermimpi menjadi juara, saya bermimpi menjadi inspirasi bagi yang datang setelah saya.", author: "Serena Williams", title: "Petenis, Amerika Serikat", category: "mimpi" },
  { id: "Q184", text: "Hidup ini terlalu singkat untuk bermimpi kecil.", author: "Tony Hsieh", title: "Mantan CEO Zappos, Amerika Serikat", category: "mimpi" },
  { id: "Q185", text: "Saya percaya, anak muda Indonesia bisa menjadi pemain global jika diberi ruang dan kepercayaan sejak dini.", author: "Erick Thohir", title: "Menteri BUMN & Pengusaha, Indonesia", category: "mimpi" },

  // Bagian 8: Kehidupan & Kebijaksanaan
  { id: "Q186", text: "Hidup adalah apa yang terjadi padamu ketika kamu sibuk membuat rencana lain.", author: "John Lennon", title: "Musisi, Inggris", category: "kehidupan" },
  { id: "Q187", text: "Hari terbaik dalam hidupmu adalah ketika kamu menyadari bahwa hanya kamu sendiri yang bertanggung jawab atas kebahagiaanmu.", author: "Andrew Matthews", title: "Penulis & Ilustrator, Australia", category: "kehidupan" },
  { id: "Q188", text: "Hidup bukan tentang menemukan dirimu sendiri, hidup adalah tentang menciptakan dirimu sendiri.", author: "George Bernard Shaw", title: "Penulis, Irlandia", category: "kehidupan" },
  { id: "Q189", text: "Waktu adalah satu-satunya hal yang tidak bisa kamu beli kembali, jadi pakailah dengan bijak.", author: "Steve Jobs", title: "Pendiri Apple Inc., Amerika Serikat", category: "kehidupan" },
  { id: "Q190", text: "Kebahagiaan bukan sesuatu yang kamu cari di luar, ia adalah pilihan yang kamu buat setiap hari.", author: "Abraham Lincoln", title: "Presiden ke-16 Amerika Serikat", category: "kehidupan" },
  { id: "Q191", text: "Kesederhanaan adalah bentuk kecerdasan tertinggi.", author: "Leonardo da Vinci", title: "Seniman & Ilmuwan, Italia", category: "kehidupan" },
  { id: "Q192", text: "Hidup yang tidak diuji bukanlah hidup yang layak dijalani.", author: "Socrates", title: "Filsuf, Yunani", category: "kehidupan" },
  { id: "Q193", text: "Saya tidak takut mati, saya hanya tidak ingin berada di sana saat itu terjadi.", author: "Woody Allen", title: "Sutradara & Aktor, Amerika Serikat", category: "kehidupan" },
  { id: "Q194", text: "Jangan menghitung hari, buatlah hari itu bermakna.", author: "Muhammad Ali", title: "Petinju Legendaris, Amerika Serikat", category: "kehidupan" },
  { id: "Q195", text: "Hidup ini sepuluh persen tentang apa yang terjadi, sembilan puluh persen tentang bagaimana kamu meresponsnya.", author: "Charles R. Swindoll", title: "Pendeta & Penulis, Amerika Serikat", category: "kehidupan" },
  { id: "Q196", text: "Kebijaksanaan datang bukan dari banyaknya usia, tetapi dari banyaknya pelajaran yang diambil dari kesalahan.", author: "Confucius", title: "Filsuf, Tiongkok", category: "kehidupan" },
  { id: "Q197", text: "Apa yang ada di belakang kita dan apa yang ada di depan kita adalah hal kecil dibandingkan dengan apa yang ada di dalam diri kita.", author: "Ralph Waldo Emerson", title: "Penulis & Filsuf, Amerika Serikat", category: "kehidupan" },
  { id: "Q198", text: "Tidak ada angin yang baik bagi pelaut yang tidak tahu ke mana ia ingin berlayar.", author: "Seneca", title: "Filsuf, Romawi", category: "kehidupan" },
  { id: "Q199", text: "Kekayaan sejati bukan diukur dari apa yang kamu miliki, tetapi dari apa yang kamu bisa berikan tanpa merasa kekurangan.", author: "Buya Hamka", title: "Ulama & Sastrawan, Indonesia", category: "kehidupan" },
  { id: "Q200", text: "Hiduplah hari ini sepenuhnya, karena kemarin sudah berlalu dan esok belum tentu datang.", author: "Mother Teresa", title: "Biarawati & Aktivis Sosial, Albania-India", category: "kehidupan" },
  { id: "Q201", text: "Saya percaya hidup ini terlalu singkat untuk dihabiskan dengan menyimpan dendam.", author: "Nelson Mandela", title: "Presiden Afrika Selatan", category: "kehidupan" },
  { id: "Q202", text: "Kebahagiaan tidak datang dari memiliki banyak, tetapi dari memberi banyak dengan tulus.", author: "Mother Teresa", title: "Biarawati & Aktivis Sosial, Albania-India", category: "kehidupan" },
  { id: "Q203", text: "Yang penting bukan tahun-tahun dalam hidupmu, tetapi hidup dalam tahun-tahunmu.", author: "Abraham Lincoln", title: "Presiden ke-16 Amerika Serikat", category: "kehidupan" },
  { id: "Q204", text: "Kesabaran adalah pahit, tetapi buahnya manis.", author: "Jean-Jacques Rousseau", title: "Filsuf, Swiss-Prancis", category: "kehidupan" },
  { id: "Q205", text: "Hidup yang baik adalah hidup yang diinspirasi oleh cinta dan dipimpin oleh ilmu pengetahuan.", author: "Bertrand Russell", title: "Filsuf, Inggris", category: "kehidupan" },
  { id: "Q206", text: "Kamu tidak bisa mengubah arah angin, tetapi kamu bisa menyesuaikan layarmu untuk selalu mencapai tujuanmu.", author: "Jimmy Dean", title: "Musisi & Pengusaha, Amerika Serikat", category: "kehidupan" },
  { id: "Q207", text: "Hidup itu seperti bermain piano, kamu harus menggunakan tuts hitam dan putih untuk menghasilkan musik yang indah.", author: "Pepatah Umum", title: "Kebijaksanaan Populer", category: "kehidupan" },
  { id: "Q208", text: "Saya belajar bahwa keberanian bukan ketidakhadiran rasa takut, tetapi kemenangan atas rasa takut itu.", author: "Nelson Mandela", title: "Presiden Afrika Selatan", category: "kehidupan" },
  { id: "Q209", text: "Kebijaksanaan terbesar adalah mengetahui bahwa kamu tidak mengetahui segalanya.", author: "Socrates", title: "Filsuf, Yunani", category: "kehidupan" },
  { id: "Q210", text: "Hiduplah dengan sederhana, agar orang lain bisa hidup.", author: "Mahatma Gandhi", title: "Tokoh Kemerdekaan India", category: "kehidupan" },
  { id: "Q211", text: "Tujuan hidup bukanlah menjadi sempurna, tetapi menjadi utuh dan jujur pada diri sendiri.", author: "Carl Jung", title: "Psikiater, Swiss", category: "kehidupan" },
  { id: "Q212", text: "Hidup adalah perjalanan, bukan tujuan, jadi nikmatilah setiap langkahnya.", author: "Ralph Waldo Emerson", title: "Penulis & Filsuf, Amerika Serikat", category: "kehidupan" },
  { id: "Q213", text: "Saya tidak peduli seberapa lambat kamu berjalan, selama kamu tidak berhenti.", author: "Confucius", title: "Filsuf, Tiongkok", category: "kehidupan" },
  { id: "Q214", text: "Hal yang paling berharga dalam hidup bukanlah harta, melainkan waktu yang kita habiskan dengan orang yang kita cintai.", author: "Steve Jobs", title: "Pendiri Apple Inc., Amerika Serikat", category: "kehidupan" },
  { id: "Q215", text: "Kebahagiaan sejati ditemukan dalam memberi, bukan dalam menerima.", author: "Buddha", title: "Pendiri Ajaran Buddha, Nepal-India", category: "kehidupan" },
  { id: "Q216", text: "Kehidupan yang tidak pernah kamu refleksikan adalah kehidupan yang setengah kamu jalani.", author: "Socrates", title: "Filsuf, Yunani", category: "kehidupan" },
  { id: "Q217", text: "Jangan menunda kebaikan, karena kamu tidak pernah tahu kapan kesempatan itu hilang selamanya.", author: "Buya Hamka", title: "Ulama & Sastrawan, Indonesia", category: "kehidupan" },
  { id: "Q218", text: "Saya tidak mengukur kekayaan dari berapa banyak yang saya peroleh, tetapi dari berapa banyak yang saya bisa relakan.", author: "Bob Sadino", title: "Pengusaha & Pendiri Kemfood-Kemchick, Indonesia", category: "kehidupan" },
  { id: "Q219", text: "Hidup memberi kita apa yang kita butuhkan untuk tumbuh, bukan selalu apa yang kita inginkan.", author: "Eleanor Roosevelt", title: "Ibu Negara & Aktivis Hak Asasi Manusia, Amerika Serikat", category: "kehidupan" },
  { id: "Q220", text: "Kebenaran mungkin pahit, tetapi kebohongan selalu lebih mahal pada akhirnya.", author: "Gus Dur", title: "Presiden ke-4 Indonesia", category: "kehidupan" },

  // Bagian 9: Keberanian & Tekad
  { id: "Q221", text: "Keberanian bukan tidak adanya rasa takut, melainkan keputusan untuk melangkah meski merasa takut.", author: "Nelson Mandela", title: "Presiden Afrika Selatan", category: "keberanian" },
  { id: "Q222", text: "Hanya mereka yang berani gagal besar yang bisa mencapai sesuatu yang besar.", author: "Robert F. Kennedy", title: "Senator & Aktivis, Amerika Serikat", category: "keberanian" },
  { id: "Q223", text: "Jangan biarkan ketakutan akan kehilangan menjadi lebih besar daripada keinginan untuk menang.", author: "Robert Kiyosaki", title: "Penulis & Investor, Amerika Serikat", category: "keberanian" },
  { id: "Q224", text: "Saya tidak pernah mundur dari tantangan, karena tantangan adalah tempat saya bertumbuh.", author: "Sri Mulyani Indrawati", title: "Menteri Keuangan Republik Indonesia", category: "keberanian" },
  { id: "Q225", text: "Keberanian adalah kualitas pertama manusia, karena tanpanya kualitas lain tidak akan ada artinya.", author: "Winston Churchill", title: "Perdana Menteri Inggris", category: "keberanian" },
  { id: "Q226", text: "Tekad yang kuat bisa mengubah keterbatasan menjadi peluang.", author: "Helen Keller", title: "Penulis & Aktivis, Amerika Serikat", category: "keberanian" },
  { id: "Q227", text: "Saya memilih untuk tidak takut, karena ketakutan hanya akan memperlambat langkah saya menuju mimpi.", author: "Malala Yousafzai", title: "Aktivis Pendidikan, Pakistan", category: "keberanian" },
  { id: "Q228", text: "Jangan tunggu sampai semua kondisi sempurna untuk memulai, karena kesempurnaan tidak pernah benar-benar datang.", author: "Bob Sadino", title: "Pengusaha & Pendiri Kemfood-Kemchick, Indonesia", category: "keberanian" },
  { id: "Q229", text: "Keberanian adalah melakukan apa yang kamu takutkan, tanpa keberanian tidak ada keberanian sama sekali.", author: "Eddie Rickenbacker", title: "Penerbang & Pengusaha, Amerika Serikat", category: "keberanian" },
  { id: "Q230", text: "Saya lebih memilih gagal karena mencoba daripada menyesal karena tidak pernah mencoba sama sekali.", author: "Sandiaga Uno", title: "Pengusaha & Wakil Menteri Pariwisata Indonesia", category: "keberanian" },
  { id: "Q231", text: "Hanya orang yang berani mengambil risiko besar yang bisa mencapai pencapaian besar.", author: "Robert Kennedy", title: "Senator & Aktivis, Amerika Serikat", category: "keberanian" },
  { id: "Q232", text: "Jangan minta keadaan menjadi lebih mudah, mintalah dirimu menjadi lebih kuat.", author: "Jim Rohn", title: "Penulis & Motivator, Amerika Serikat", category: "keberanian" },
  { id: "Q233", text: "Tekad mengalahkan talenta ketika talenta tidak punya tekad.", author: "Tim Notke", title: "Pelatih Basket, Amerika Serikat", category: "keberanian" },
  { id: "Q234", text: "Saya percaya, satu-satunya hal yang harus kita takuti adalah rasa takut itu sendiri.", author: "Franklin D. Roosevelt", title: "Presiden ke-32 Amerika Serikat", category: "keberanian" },
  { id: "Q235", text: "Keberanian terbesar bukan saat kita menang, tetapi saat kita bangkit setelah dipermalukan oleh kekalahan.", author: "Soekarno", title: "Presiden Pertama Indonesia", category: "keberanian" },

  // Bagian 10: Olahraga & Semangat Juara
  { id: "Q236", text: "Saya tidak pernah berhenti berlatih hanya karena saya sudah menjadi juara, justru karena itulah saya berlatih lebih keras lagi.", author: "Michael Jordan", title: "Legenda Basket NBA, Amerika Serikat", category: "olahraga" },
  { id: "Q237", text: "Juara dibentuk bukan di atas ring atau lapangan, tetapi jauh sebelum itu, di tempat latihan yang sunyi.", author: "Muhammad Ali", title: "Petinju Legendaris, Amerika Serikat", category: "olahraga" },
  { id: "Q238", text: "Saya gagal lebih dari 9.000 tembakan dalam karier saya dan kalah hampir 300 pertandingan, tetapi itulah yang membuat saya sukses.", author: "Michael Jordan", title: "Legenda Basket NBA, Amerika Serikat", category: "olahraga" },
  { id: "Q239", text: "Bakat memenangkan pertandingan, tetapi kerja sama tim dan kecerdasan memenangkan kejuaraan.", author: "Michael Jordan", title: "Legenda Basket NBA, Amerika Serikat", category: "olahraga" },
  { id: "Q240", text: "Olahraga mengajarkan saya bahwa kekalahan bukan akhir, melainkan bagian dari perjalanan menuju kemenangan.", author: "Cristiano Ronaldo", title: "Pesepak Bola, Portugal", category: "olahraga" },
  { id: "Q241", text: "Saya bermain bukan untuk dibandingkan dengan orang lain, saya bermain untuk menjadi versi terbaik dari diri saya sendiri.", author: "Lionel Messi", title: "Pesepak Bola, Argentina", category: "olahraga" },
  { id: "Q242", text: "Mental juara adalah ketika kamu tetap bangun pukul empat pagi meski semalam kamu kalah telak.", author: "Kobe Bryant", title: "Legenda Basket NBA, Amerika Serikat", category: "olahraga" },
  { id: "Q243", text: "Saya tidak takut kalah, saya hanya takut tidak memberikan yang terbaik dari diri saya.", author: "Serena Williams", title: "Petenis, Amerika Serikat", category: "olahraga" },
  { id: "Q244", text: "Atlet hebat tahu bagaimana mengubah rasa sakit menjadi bahan bakar untuk berlatih lebih keras esok hari.", author: "Usain Bolt", title: "Pelari Tercepat Dunia, Jamaika", category: "olahraga" },
  { id: "Q245", text: "Sepak bola adalah permainan sederhana yang membutuhkan kerja keras, disiplin, dan kerendahan hati setiap hari di lapangan.", author: "Pep Guardiola", title: "Pelatih Sepak Bola, Spanyol", category: "olahraga" },
  { id: "Q246", text: "Saya selalu percaya, bulu tangkis bukan hanya soal raga, tetapi soal mental yang lebih kuat dari lawan.", author: "Susy Susanti", title: "Legenda Bulu Tangkis, Indonesia", category: "olahraga" },
  { id: "Q247", text: "Kemenangan terbesar saya bukan medali, tetapi keyakinan generasi muda bahwa Indonesia bisa juara di kancah dunia.", author: "Taufik Hidayat", title: "Legenda Bulu Tangkis, Indonesia", category: "olahraga" },
  { id: "Q248", text: "Setiap pertandingan yang saya kalahkan mengajarkan saya lebih banyak daripada setiap pertandingan yang saya menangkan.", author: "Rafael Nadal", title: "Petenis, Spanyol", category: "olahraga" },
  { id: "Q249", text: "Saya tidak bermain untuk uang atau ketenaran, saya bermain karena saya jatuh cinta pada permainan ini sejak kecil.", author: "Pelé", title: "Legenda Sepak Bola, Brasil", category: "olahraga" },
  { id: "Q250", text: "Sepak bola Indonesia akan besar jika kita berani memberi kesempatan pada pemain muda sejak usia dini.", author: "Indra Sjafri", title: "Pelatih Sepak Bola, Indonesia", category: "olahraga" },
  { id: "Q251", text: "Sebuah klub sepak bola bukan hanya tentang trofi, ia adalah identitas dan kebanggaan sebuah kota.", author: "Sir Alex Ferguson", title: "Pelatih Sepak Bola, Skotlandia", category: "olahraga" },
  { id: "Q252", text: "Saya pernah dianggap terlalu kecil untuk jadi pemain hebat, tapi saya buktikan ukuran tubuh tidak menentukan besarnya hati seorang pemain.", author: "Lionel Messi", title: "Pesepak Bola, Argentina", category: "olahraga" },
  { id: "Q253", text: "Atlet sejati berlatih bukan hanya saat ada yang menonton, tetapi terutama saat tidak ada satu pun yang melihat.", author: "Michael Phelps", title: "Perenang, Amerika Serikat", category: "olahraga" },
  { id: "Q254", text: "Saya percaya, olahraga adalah bahasa universal yang bisa menyatukan bangsa yang paling terpecah.", author: "Nelson Mandela", title: "Presiden Afrika Selatan", category: "olahraga" },

  // Bagian 11: Cinta Tanah Air & Kebangsaan
  { id: "Q255", text: "Bangsa yang besar adalah bangsa yang mau menghargai jasa pahlawannya, jangan sekali-kali meninggalkan sejarah.", author: "Ir. Soekarno", title: "Presiden Pertama Indonesia", category: "tanah-air" },
  { id: "Q256", text: "Saya lebih suka menjadi orang Indonesia yang dibenci daripada menjadi orang asing yang dipuji.", author: "Mohammad Hatta", title: "Wakil Presiden Pertama Indonesia", category: "tanah-air" },
  { id: "Q257", text: "Merdeka atau mati.", author: "Bung Tomo", title: "Pahlawan Nasional Indonesia", category: "tanah-air" },
  { id: "Q258", text: "Indonesia bukan hanya negara, ia adalah persatuan dari ribuan suku, bahasa, dan pulau yang memilih untuk bersatu.", author: "Soekarno", title: "Presiden Pertama Indonesia", category: "tanah-air" },
  { id: "Q259", text: "Sejarah adalah guru terbaik bagi bangsa yang ingin melangkah maju tanpa kehilangan jati dirinya.", author: "Tan Malaka", title: "Tokoh Pergerakan Kemerdekaan Indonesia", category: "tanah-air" },
  { id: "Q260", text: "Bangsa yang tidak mengenal sejarahnya sendiri seperti pohon yang tidak punya akar.", author: "Tan Malaka", title: "Tokoh Pergerakan Kemerdekaan Indonesia", category: "tanah-air" },
  { id: "Q261", text: "Kemerdekaan bukan hadiah, ia adalah hasil dari perjuangan yang harus terus kita jaga setiap generasi.", author: "Mohammad Hatta", title: "Wakil Presiden Pertama Indonesia", category: "tanah-air" },
  { id: "Q262", text: "Cinta tanah air bukan hanya soal mengangkat senjata, tetapi soal bagaimana kita membangun negeri ini setiap hari dengan karya nyata.", author: "B.J. Habibie", title: "Presiden ke-3 Indonesia", category: "tanah-air" },
  { id: "Q263", text: "Indonesia akan menjadi besar bukan karena kekayaan alamnya, tetapi karena kualitas manusia yang ada di dalamnya.", author: "Joko Widodo", title: "Presiden ke-7 Indonesia", category: "tanah-air" },
  { id: "Q264", text: "Saya percaya, masa depan Indonesia ditentukan oleh seberapa berani generasi mudanya berinovasi hari ini.", author: "Nadiem Makarim", title: "Pendiri Gojek & Menteri Pendidikan Indonesia", category: "tanah-air" },
  { id: "Q265", text: "Tanah air ini bukan warisan dari nenek moyang yang tinggal kita nikmati, tetapi titipan untuk anak cucu yang harus kita jaga.", author: "R.A. Kartini", title: "Pelopor Emansipasi Perempuan Indonesia", category: "tanah-air" },
  { id: "Q266", text: "Nasionalisme sejati adalah ketika kita mencintai bangsa sendiri tanpa harus membenci bangsa lain.", author: "Soekarno", title: "Presiden Pertama Indonesia", category: "tanah-air" },
  { id: "Q267", text: "Saya ingin Indonesia dikenal dunia bukan hanya karena keindahan alamnya, tetapi karena prestasi anak-anak bangsanya.", author: "Susi Pudjiastuti", title: "Mantan Menteri Kelautan dan Perikanan Indonesia", category: "tanah-air" },
  { id: "Q268", text: "Persatuan Indonesia tidak lahir dari kesamaan, tetapi dari kesediaan untuk menghargai perbedaan.", author: "Abdurrahman Wahid (Gus Dur)", title: "Presiden ke-4 Indonesia", category: "tanah-air" },
  { id: "Q269", text: "Bhinneka Tunggal Ika bukan slogan kosong, ia adalah janji setiap generasi untuk terus merawat keberagaman.", author: "Soekarno", title: "Presiden Pertama Indonesia", category: "tanah-air" },

  // Bagian 12: Kreativitas & Seni
  { id: "Q270", text: "Kreativitas adalah kecerdasan yang sedang bersenang-senang.", author: "Albert Einstein", title: "Fisikawan, Jerman-Amerika Serikat", category: "kreativitas" },
  { id: "Q271", text: "Setiap anak adalah seniman, masalahnya adalah bagaimana ia tetap menjadi seniman setelah dewasa.", author: "Pablo Picasso", title: "Pelukis, Spanyol", category: "kreativitas" },
  { id: "Q272", text: "Seni membersihkan debu kehidupan sehari-hari dari jiwa kita.", author: "Pablo Picasso", title: "Pelukis, Spanyol", category: "kreativitas" },
  { id: "Q273", text: "Kesederhanaan adalah kecanggihan tertinggi.", author: "Leonardo da Vinci", title: "Seniman & Ilmuwan, Italia", category: "kreativitas" },
  { id: "Q274", text: "Saya tidak melukis apa yang saya lihat, saya melukis apa yang saya rasakan.", author: "Vincent van Gogh", title: "Pelukis, Belanda", category: "kreativitas" },
  { id: "Q275", text: "Kreativitas membutuhkan keberanian untuk melepaskan kepastian.", author: "Erich Fromm", title: "Psikolog & Filsuf, Jerman-Amerika Serikat", category: "kreativitas" },
  { id: "Q276", text: "Imajinasi adalah pratinjau dari hal-hal hebat yang akan terjadi dalam hidup kita.", author: "Albert Einstein", title: "Fisikawan, Jerman-Amerika Serikat", category: "kreativitas" },
  { id: "Q277", text: "Menulis adalah cara saya memahami dunia yang terlalu rumit untuk dijelaskan dengan kata-kata biasa.", author: "Pramoedya Ananta Toer", title: "Sastrawan, Indonesia", category: "kreativitas" },
  { id: "Q278", text: "Saya menulis bukan untuk dikenang, tetapi karena saya tidak tahan untuk tidak menulis.", author: "Pramoedya Ananta Toer", title: "Sastrawan, Indonesia", category: "kreativitas" },
  { id: "Q279", text: "Seni sejati selalu lahir dari kejujuran terhadap diri sendiri, bukan dari keinginan untuk menyenangkan semua orang.", author: "Frida Kahlo", title: "Pelukis, Meksiko", category: "kreativitas" },

  // Bagian 13: Perubahan & Adaptasi
  { id: "Q280", text: "Bukan spesies yang paling kuat yang akan bertahan, melainkan yang paling mampu beradaptasi dengan perubahan.", author: "Charles Darwin", title: "Ilmuwan, Inggris", category: "perubahan" },
  { id: "Q281", text: "Jadilah perubahan yang ingin kamu lihat di dunia ini.", author: "Mahatma Gandhi", title: "Tokoh Kemerdekaan India", category: "perubahan" },
  { id: "Q282", text: "Satu-satunya hal yang konstan dalam hidup adalah perubahan itu sendiri.", author: "Heraclitus", title: "Filsuf, Yunani", category: "perubahan" },
  { id: "Q283", text: "Perusahaan yang tidak berani berubah akan ditinggalkan oleh zaman, secepat zaman itu berubah.", author: "Jack Welch", title: "Mantan CEO General Electric, Amerika Serikat", category: "perubahan" },
  { id: "Q284", text: "Saya tidak takut pada perubahan, saya hanya takut tertinggal karena terlalu lama mempertahankan cara lama.", author: "Jack Ma", title: "Pendiri Alibaba Group, Tiongkok", category: "perubahan" },
  { id: "Q285", text: "Dunia ini berubah begitu cepat, satu-satunya cara untuk bertahan adalah dengan terus belajar dan tidak pernah merasa cukup.", author: "Bill Gates", title: "Pendiri Microsoft, Amerika Serikat", category: "perubahan" },
  { id: "Q286", text: "Krisis adalah momen terbaik untuk berinovasi, karena di saat itulah orang paling terbuka pada cara baru.", author: "Sri Mulyani Indrawati", title: "Menteri Keuangan Republik Indonesia", category: "perubahan" },
  { id: "Q287", text: "Perubahan selalu menyakitkan pada awalnya, berantakan di tengah jalan, tetapi indah pada akhirnya.", author: "Robin Sharma", title: "Penulis & Pembicara, Kanada", category: "perubahan" },
  { id: "Q288", text: "Jangan menolak perubahan, tunggangi gelombangnya sebelum gelombang itu menenggelamkanmu.", author: "Howard Schultz", title: "Mantan CEO Starbucks, Amerika Serikat", category: "perubahan" },
  { id: "Q289", text: "Saya percaya, krisis BPOM yang kami hadapi justru menjadi titik balik untuk membangun kepercayaan yang lebih kuat dari sebelumnya.", author: "Lo Kheng Hong", title: "Investor Saham, Indonesia", category: "perubahan" },

  // Bagian 14: Kerendahan Hati & Integritas
  { id: "Q290", text: "Karakter adalah apa yang kamu lakukan ketika tidak ada seorang pun yang melihat.", author: "J.C. Watts", title: "Politisi & Mantan Pemain Football, Amerika Serikat", category: "integritas" },
  { id: "Q291", text: "Integritas adalah melakukan hal yang benar, bahkan ketika tidak ada yang melihat.", author: "C.S. Lewis", title: "Penulis, Irlandia", category: "integritas" },
  { id: "Q292", text: "Kerendahan hati bukan tentang berpikir lebih rendah tentang diri sendiri, tetapi tentang berpikir lebih sedikit tentang diri sendiri.", author: "C.S. Lewis", title: "Penulis, Irlandia", category: "integritas" },
  { id: "Q293", text: "Saya belajar bahwa kejujuran selalu menjadi kebijakan terbaik, meskipun sering kali menjadi yang paling sulit dijalankan.", author: "Warren Buffett", title: "CEO Berkshire Hathaway, Amerika Serikat", category: "integritas" },
  { id: "Q294", text: "Reputasi membutuhkan waktu dua puluh tahun untuk dibangun, dan hanya lima menit untuk dihancurkan.", author: "Warren Buffett", title: "CEO Berkshire Hathaway, Amerika Serikat", category: "integritas" },
  { id: "Q295", text: "Saya tidak ingin diingat sebagai orang terkaya, saya ingin diingat sebagai orang yang jujur pada janjinya.", author: "Bob Sadino", title: "Pengusaha & Pendiri Kemfood-Kemchick, Indonesia", category: "integritas" },
  { id: "Q296", text: "Kepercayaan dibangun dengan konsistensi, bukan dengan kata-kata manis sesaat.", author: "Lincoln Chafee", title: "Politisi, Amerika Serikat", category: "integritas" },
  { id: "Q297", text: "Jangan pernah mengorbankan integritasmu demi keuntungan jangka pendek, karena nama baik adalah aset paling mahal yang kamu punya.", author: "Chairul Tanjung", title: "Pendiri CT Corp, Indonesia", category: "integritas" },
  { id: "Q298", text: "Saya belajar bahwa pemimpin yang baik mengakui kesalahannya di depan umum, bukan menyembunyikannya.", author: "B.J. Habibie", title: "Presiden ke-3 Indonesia", category: "integritas" },
  { id: "Q299", text: "Kehormatan sejati datang dari konsistensi antara apa yang kamu katakan dan apa yang kamu lakukan.", author: "Mahatma Gandhi", title: "Tokoh Kemerdekaan India", category: "integritas" },

  // Bagian 15: Manajemen Waktu & Produktivitas
  { id: "Q300", text: "Waktu adalah sumber daya paling berharga yang kita semua punya secara setara, tetapi paling sedikit kita sadari nilainya.", author: "Jim Rohn", title: "Penulis & Motivator, Amerika Serikat", category: "waktu" },
  { id: "Q301", text: "Jangan menghitung hari yang berlalu, hitunglah apa yang telah kamu capai dalam hari-hari itu.", author: "Muhammad Ali", title: "Petinju Legendaris, Amerika Serikat", category: "waktu" },
  { id: "Q302", text: "Saya membagi waktu saya menjadi blok-blok lima menit, karena setiap menit yang terbuang adalah peluang yang hilang.", author: "Elon Musk", title: "CEO Tesla & SpaceX, Amerika Serikat", category: "waktu" },
  { id: "Q303", text: "Produktivitas bukan tentang melakukan lebih banyak hal, tetapi tentang melakukan hal yang benar-benar penting.", author: "Tim Ferriss", title: "Penulis & Pengusaha, Amerika Serikat", category: "waktu" },
  { id: "Q304", text: "Rencanakan hari esokmu malam ini, agar kamu bangun dengan tujuan, bukan dengan kebingungan.", author: "Benjamin Franklin", title: "Salah Satu Pendiri Amerika Serikat", category: "waktu" },
  { id: "Q305", text: "Saya tidak percaya pada multitasking, saya percaya pada fokus penuh pada satu hal sampai selesai dengan baik.", author: "Steve Jobs", title: "Pendiri Apple Inc., Amerika Serikat", category: "waktu" },
  { id: "Q306", text: "Waktu yang kamu nikmati bukanlah waktu yang terbuang.", author: "Bertrand Russell", title: "Filsuf, Inggris", category: "waktu" },
  { id: "Q307", text: "Disiplin terhadap waktu adalah bentuk penghormatan tertinggi terhadap diri sendiri dan orang lain.", author: "Indra Nooyi", title: "Mantan CEO PepsiCo, India-Amerika Serikat", category: "waktu" },
  { id: "Q308", text: "Saya bekerja dengan prinsip sederhana, kerjakan hal yang paling penting dulu, sisanya menyesuaikan.", author: "Sundar Pichai", title: "CEO Alphabet & Google, India-Amerika Serikat", category: "waktu" },
  { id: "Q309", text: "Kunci produktivitas bukan bekerja lebih lama, tetapi bekerja dengan prioritas yang lebih jelas.", author: "Peter Drucker", title: "Pakar Manajemen, Austria-Amerika Serikat", category: "waktu" },

  // Bagian 16: Persahabatan & Hubungan
  { id: "Q310", text: "Persahabatan sejati adalah ketika kamu bisa diam bersama seseorang dan tetap merasa dimengerti.", author: "Dave Tyson", title: "Penulis, Amerika Serikat", category: "persahabatan" },
  { id: "Q311", text: "Tidak ada kekayaan yang lebih besar daripada memiliki teman yang setia di saat susah maupun senang.", author: "Buya Hamka", title: "Ulama & Sastrawan, Indonesia", category: "persahabatan" },
  { id: "Q312", text: "Saya tidak akan sampai di titik ini tanpa tim dan keluarga yang percaya pada saya bahkan ketika saya sendiri ragu.", author: "Nadiem Makarim", title: "Pendiri Gojek & Menteri Pendidikan Indonesia", category: "persahabatan" },
  { id: "Q313", text: "Hubungan yang baik dibangun dari kepercayaan, dan kepercayaan dibangun dari konsistensi kecil setiap hari.", author: "Stephen Covey", title: "Penulis 7 Habits, Amerika Serikat", category: "persahabatan" },
  { id: "Q314", text: "Keluarga adalah alasan saya bangun setiap pagi dan bekerja lebih keras dari hari kemarin.", author: "Tony Robbins", title: "Penulis & Motivator, Amerika Serikat", category: "persahabatan" },
  { id: "Q315", text: "Tidak ada kesuksesan yang sepadan jika kita mengabaikan orang-orang terdekat di sepanjang jalan menuju kesuksesan itu.", author: "Indra Nooyi", title: "Mantan CEO PepsiCo, India-Amerika Serikat", category: "persahabatan" },
  { id: "Q316", text: "Saya percaya, tim yang hebat dibangun dari kepercayaan, bukan dari rasa takut.", author: "Satya Nadella", title: "CEO Microsoft, India-Amerika Serikat", category: "persahabatan" },
  { id: "Q317", text: "Sahabat sejati adalah mereka yang tetap berdiri di sampingmu bahkan setelah mengetahui semua kesalahanmu.", author: "Bertrand Russell", title: "Filsuf, Inggris", category: "persahabatan" },
  { id: "Q318", text: "Saya belajar bahwa kerja tim yang kuat selalu mengalahkan individu yang brilian tetapi bekerja sendirian.", author: "Steve Jobs", title: "Pendiri Apple Inc., Amerika Serikat", category: "persahabatan" },
  { id: "Q319", text: "Hubungan yang sehat adalah ketika dua orang bisa tumbuh bersama, bukan saling membatasi satu sama lain.", author: "Maya Angelou", title: "Penyair & Aktivis, Amerika Serikat", category: "persahabatan" },

  // Bagian 17: Kepercayaan Diri & Jati Diri
  { id: "Q320", text: "Jadilah dirimu sendiri, karena semua orang lain sudah ada yang menjadi diri mereka.", author: "Oscar Wilde", title: "Penulis, Irlandia", category: "percaya-diri" },
  { id: "Q321", text: "Kepercayaan diri bukan tentang merasa lebih baik dari orang lain, tetapi tentang merasa cukup dengan diri sendiri.", author: "Maya Angelou", title: "Penyair & Aktivis, Amerika Serikat", category: "percaya-diri" },
  { id: "Q322", text: "Saya tidak peduli pendapat orang lain tentang saya, karena saya tahu siapa diri saya sebenarnya.", author: "Muhammad Ali", title: "Petinju Legendaris, Amerika Serikat", category: "percaya-diri" },
  { id: "Q323", text: "Tidak ada yang bisa membuatmu merasa rendah diri tanpa izinmu sendiri.", author: "Eleanor Roosevelt", title: "Ibu Negara & Aktivis Hak Asasi Manusia, Amerika Serikat", category: "percaya-diri" },
  { id: "Q324", text: "Jangan biarkan suara orang lain membungkam suara hatimu sendiri.", author: "Steve Jobs", title: "Pendiri Apple Inc., Amerika Serikat", category: "percaya-diri" },
  { id: "Q325", text: "Saya menemukan kekuatan saya yang sebenarnya ketika saya berhenti berusaha menjadi orang lain.", author: "Lady Gaga", title: "Musisi, Amerika Serikat", category: "percaya-diri" },
  { id: "Q326", text: "Percaya diri adalah hasil dari latihan yang konsisten, bukan bawaan lahir semata.", author: "Cristiano Ronaldo", title: "Pesepak Bola, Portugal", category: "percaya-diri" },
  { id: "Q327", text: "Jati diri sejati ditemukan saat kamu berhenti mencari validasi dari luar dirimu.", author: "Carl Jung", title: "Psikiater, Swiss", category: "percaya-diri" },
  { id: "Q328", text: "Saya percaya, perempuan Indonesia bisa menjadi apa pun yang mereka mau, selama mereka berani percaya pada diri sendiri.", author: "R.A. Kartini", title: "Pelopor Emansipasi Perempuan Indonesia", category: "percaya-diri" },
  { id: "Q329", text: "Saya menerima diri saya yang penuh kekurangan, karena dari situlah saya menemukan keberanian sejati.", author: "Brené Brown", title: "Peneliti & Penulis, Amerika Serikat", category: "percaya-diri" },

  // Bagian 18: Kebijaksanaan Lintas Bangsa
  { id: "Q330", text: "Orang yang menggerakkan gunung dimulai dengan memindahkan batu-batu kecil.", author: "Confucius", title: "Filsuf, Tiongkok", category: "lintas-bangsa" },
  { id: "Q331", text: "Air yang tenang menghanyutkan, tetapi air yang lembut juga bisa menembus batu yang paling keras jika cukup lama menetes.", author: "Lao Tzu", title: "Filsuf, Tiongkok", category: "lintas-bangsa" },
  { id: "Q332", text: "Perjalanan seribu mil dimulai dengan satu langkah kecil.", author: "Lao Tzu", title: "Filsuf, Tiongkok", category: "lintas-bangsa" },
  { id: "Q333", text: "Sebelum kamu memulai perjalanan balas dendam, gali dulu dua kuburan.", author: "Confucius", title: "Filsuf, Tiongkok", category: "lintas-bangsa" },
  { id: "Q334", text: "Bambu yang lentur lebih kuat daripada pohon ek yang kaku, karena ia tahu kapan harus menyerah pada angin.", author: "Pepatah Jepang", title: "Kebijaksanaan Populer, Jepang", category: "lintas-bangsa" },
  { id: "Q335", text: "Keindahan sejati sebuah bunga sakura terletak pada betapa singkatnya ia mekar, mengajarkan kita menghargai setiap momen.", author: "Pepatah Jepang", title: "Kebijaksanaan Populer, Jepang", category: "lintas-bangsa" },
  { id: "Q336", text: "Pohon besar tumbuh dari biji kecil yang berani ditanam di tanah yang keras.", author: "Pepatah Afrika", title: "Kebijaksanaan Populer, Afrika", category: "lintas-bangsa" },
  { id: "Q337", text: "Jika kamu ingin berjalan cepat, berjalanlah sendiri. Jika kamu ingin berjalan jauh, berjalanlah bersama-sama.", author: "Pepatah Afrika", title: "Kebijaksanaan Populer, Afrika", category: "lintas-bangsa" },
  { id: "Q338", text: "Gajah tidak merasa berat dengan gadingnya sendiri, demikian pula seseorang tidak akan terbebani oleh tanggung jawab yang ia pilih dengan ikhlas.", author: "Pepatah India", title: "Kebijaksanaan Populer, India", category: "lintas-bangsa" },
  { id: "Q339", text: "Sungai yang paling dalam mengalir paling tenang, begitu juga orang yang paling bijaksana berbicara paling sedikit.", author: "Pepatah Tiongkok", title: "Kebijaksanaan Populer, Tiongkok", category: "lintas-bangsa" },

  // Bagian 19: Semangat & Harapan
  { id: "Q340", text: "Harapan adalah hal dengan bulu yang bertengger di jiwa dan menyenandungkan lagu tanpa kata, tanpa pernah berhenti sama sekali.", author: "Emily Dickinson", title: "Penyair, Amerika Serikat", category: "harapan" },
  { id: "Q341", text: "Selama masih ada matahari yang terbit esok hari, selalu ada alasan untuk berharap dan mencoba lagi.", author: "Anne Frank", title: "Penulis Diary Anne Frank, Jerman-Belanda", category: "harapan" },
  { id: "Q342", text: "Saya percaya, secercah cahaya kecil cukup untuk mengusir kegelapan yang paling pekat sekalipun.", author: "Desmond Tutu", title: "Uskup & Aktivis Hak Asasi Manusia, Afrika Selatan", category: "harapan" },
  { id: "Q343", text: "Harapan bukan keyakinan bahwa semuanya akan berjalan baik, tetapi keyakinan bahwa semua ini masuk akal, apa pun hasilnya.", author: "Václav Havel", title: "Presiden Republik Ceko", category: "harapan" },
  { id: "Q344", text: "Saya tidak pernah kehilangan harapan, karena saya tahu setiap malam yang gelap akan diikuti oleh pagi yang terang.", author: "Martin Luther King Jr.", title: "Tokoh Hak Sipil, Amerika Serikat", category: "harapan" },
  { id: "Q345", text: "Jaga selalu nyala kecil harapan dalam dirimu, karena dari nyala kecil itulah api besar perubahan bisa lahir.", author: "Soekarno", title: "Presiden Pertama Indonesia", category: "harapan" },
  { id: "Q346", text: "Hidup ini akan selalu memberi kesempatan baru bagi mereka yang tidak berhenti berusaha dan percaya.", author: "Anne Frank", title: "Penulis Diary Anne Frank, Jerman-Belanda", category: "harapan" },
  { id: "Q347", text: "Saya percaya pada kekuatan mimpi yang dijaga dengan kerja keras dan doa yang tak pernah putus.", author: "Buya Hamka", title: "Ulama & Sastrawan, Indonesia", category: "harapan" },
  { id: "Q348", text: "Masa depan selalu lebih cerah bagi mereka yang berani membangunnya hari ini, sekecil apa pun langkah pertamanya.", author: "B.J. Habibie", title: "Presiden ke-3 Indonesia", category: "harapan" },
  { id: "Q349", text: "Selama kita masih punya napas untuk bermimpi dan tangan untuk bekerja, tidak ada yang benar-benar mustahil.", author: "Soekarno", title: "Presiden Pertama Indonesia", category: "harapan" },

  // Bagian 20: Pelengkap
  { id: "Q350", text: "Satu langkah kecil bagi manusia, satu lompatan besar bagi umat manusia.", author: "Neil Armstrong", title: "Astronaut Pertama di Bulan, Amerika Serikat", category: "pelengkap" },
  { id: "Q351", text: "Kita memilih pergi ke Bulan bukan karena itu mudah, tetapi justru karena itu sulit.", author: "John F. Kennedy", title: "Presiden ke-35 Amerika Serikat", category: "pelengkap" },
  { id: "Q352", text: "Semua orang adalah jenius, tetapi jika kamu menilai ikan dari kemampuannya memanjat pohon, ia akan merasa bodoh sepanjang hidupnya.", author: "Albert Einstein", title: "Fisikawan, Jerman-Amerika Serikat", category: "pelengkap" },
  { id: "Q353", text: "Logika akan membawamu dari A ke B, tetapi imajinasi akan membawamu ke mana pun kamu mau.", author: "Albert Einstein", title: "Fisikawan, Jerman-Amerika Serikat", category: "pelengkap" },
  { id: "Q354", text: "Saya tidak punya rumus rahasia untuk sukses, hanya kerja keras, ketekunan, dan belajar dari setiap kegagalan.", author: "Colonel Sanders", title: "Pendiri KFC, Amerika Serikat", category: "pelengkap" },
  { id: "Q355", text: "Usia bukan penghalang, saya memulai bisnis ayam goreng saya di usia enam puluh lima tahun.", author: "Colonel Sanders", title: "Pendiri KFC, Amerika Serikat", category: "pelengkap" },
  { id: "Q356", text: "Saya percaya, tidak pernah terlambat untuk memulai sesuatu yang besar, selama kamu masih punya tekad untuk mencobanya.", author: "Vera Wang", title: "Perancang Busana, Amerika Serikat", category: "pelengkap" },
  { id: "Q357", text: "Kreativitas terbesar lahir dari keterbatasan, bukan dari kebebasan tanpa batas.", author: "Akira Kurosawa", title: "Sutradara Film, Jepang", category: "pelengkap" },
  { id: "Q358", text: "Saya menulis untuk menemukan apa yang saya pikirkan, bukan menulis karena saya sudah tahu apa yang saya pikirkan.", author: "Joan Didion", title: "Penulis, Amerika Serikat", category: "pelengkap" },
  { id: "Q359", text: "Cita-cita besar dimulai dari keberanian untuk berbeda dari kebanyakan orang di sekitarmu.", author: "Steve Jobs", title: "Pendiri Apple Inc., Amerika Serikat", category: "pelengkap" },
  { id: "Q360", text: "Jangan biarkan kebisingan pendapat orang lain menenggelamkan suara hati kecilmu sendiri.", author: "Steve Jobs", title: "Pendiri Apple Inc., Amerika Serikat", category: "pelengkap" },
  { id: "Q361", text: "Saya percaya, kesuksesan terbaik adalah ketika kita membantu orang lain ikut sukses bersama kita.", author: "Howard Schultz", title: "Mantan CEO Starbucks, Amerika Serikat", category: "pelengkap" },
  { id: "Q362", text: "Tidak ada yang lebih memuaskan daripada melihat orang yang kita bimbing tumbuh lebih besar dari kita.", author: "Indra Nooyi", title: "Mantan CEO PepsiCo, India-Amerika Serikat", category: "pelengkap" },
  { id: "Q363", text: "Setiap pagi kita punya dua pilihan, melanjutkan tidur dengan mimpi, atau bangun dan mengejarnya.", author: "Pepatah Umum", title: "Kebijaksanaan Populer", category: "pelengkap" },
  { id: "Q364", text: "Kesuksesan bukan tujuan akhir, kegagalan bukan akhir dari segalanya, yang penting adalah keberanian untuk terus melangkah.", author: "Winston Churchill", title: "Perdana Menteri Inggris", category: "pelengkap" },
  { id: "Q365", text: "Saya percaya, generasi muda hari ini punya kesempatan lebih besar dari generasi mana pun sebelumnya untuk mengubah dunia, asal mereka berani memulai.", author: "Malala Yousafzai", title: "Aktivis Pendidikan, Pakistan", category: "pelengkap" },
];
